### PR TITLE
Improved PR#751

### PR DESCRIPTION
**Pull request by guedou**
See #751

### CODE REVIEW

**Comment by guedou** [comment]
@gpotter2 do you understand why it fails on windows ?

**Comment by gpotter2** [comment]
Seems there is a difference between windows and linux, i'm getting:
'0x80000dc3L'
so you should use
`.rstrip("L")` to fix that

**Comment by p-l-** [comment]
@gpotter2 @guedou we don't want to test / depend on `hex()`. I think it would be better to test the value rather than the output of `hex()`.

**Comment by guedou** [comment]
Nice catch ! This did not catch my eye. I removed calls to `hex()`.

**Pull request merged**
