### PR TITLE
Unit-Tests for SocketCAN

### PR DESCRIPTION
**Pull request by polybassa**

### CODE REVIEW

**Comment by polybassa** [comment]
CANSocket requires python3. Is it possible to exclude python 2.7 from this unit tests?

**Comment by gpotter2** [comment]
`~ FIXME_py3` for now

**Comment by guedou** [comment]
@polybassa your module must support 2.7 and 3.*

**Comment by polybassa** [comment]
Hi @guedou,
unfortunatly, AF_CAN and PF_CAN is only available in Python >= 3.3
https://python.readthedocs.io/en/latest/library/socket.html
Greetings, Nils

**Comment by guedou** [comment]
What is the difference with #1205  ? I am really confused as your are interacting on both of them. I will close this one for now and discuss on #1205 instead.

Reopen this one if I am wrong.

**Pull request closed without merging**
