### PR TITLE
Test send / sendp and sniff

### PR DESCRIPTION
**Pull request by p-l-**
Also adds a codecov badge to README.

### CODE REVIEW

**Comment by gpotter2** [comment]
Nice, but how about making it work on windows too ?

Here's the patch, that contains the same tests as yours, but remade to run on windows (as `os.fork()` is unavailable)

**First: https://github.com/secdev/scapy/pull/455 is required**
then the test for windows only:
```
= send() and sniff()
~ netaccess
import time
import os
from threading import Thread

def windows_fork(function):
    def run_function(pid, thread, results):
        function(pid, thread)
        results.put(True)
    results = Queue.Queue()
    t_parent = Thread(target=run_function, args=(0, None, results))
    t_child = Thread(target=run_function, args=(1, t_parent, results))
    t_parent.start()
    t_child.start()
    t_parent.join()
    t_child.join()
    assert results.qsize() >= 2
    while not results.empty():
        assert results.get()

def send_and_sniff(pkt, timeout=2, flt=None, _iface=None):
    """Send a packet, sniff, and check the packet has been seen"""
    iface = _iface if _iface else conf.iface
    def test_func(pid, t_other):
        assert pid != -1
        if pid == 0:
            time.sleep(1)
            (sendp if isinstance(pkt, (Ether, Dot3)) else send)(pkt, iface=iface)
            return
        else:
            spkt = str(pkt)
            pkts = sniff(
                timeout=timeout, iface=iface, filter=flt,
                stop_filter=lambda p: pkt.__class__ in p and str(p[pkt.__class__]) == spkt
            )
            t_other.join()
        assert str(pkt) in (str(p[pkt.__class__]) for p in pkts if pkt.__class__ in p)
    windows_fork(test_func)

send_and_sniff(IP(dst="secdev.org")/ICMP())
send_and_sniff(IP(dst="secdev.org")/ICMP(), flt="icmp")
send_and_sniff(Ether()/IP(dst="secdev.org")/ICMP())
```

**Comment by p-l-** [comment]
Thanks @gpotter2! I have integrated your solution to the `fork()` one to avoid special cases.

@guedou should be good to merge now!

**Comment by guedou** [comment]
@p-l- looks good to me ! Why not using threading on all OSes ?

**Comment by gpotter2** [comment]
@guedou The threading solution is actually quite slow to start :/ os.fork() will be much quicker...
I guess this will be better for Travis ci builds

**Comment by p-l-** [comment]
@guedou: I prefer to keep a simple interface for Unix systems, in case one day we get a simple Windows-specific interface... I did not run the tests but trust @gpotter2 for the performances.

**Comment by p-l-** [comment]
Since #450 has been merged, I'm adding tests for `L2ListenTcpdump`.

**Pull request merged**
