### PR TITLE
Write a PCAP header when no packets are provided

### LINKED ISSUE #1242: wrpcap regression
`wrpcap('/tmp/empty.pcap', [])`
should write a pcap header but the file is empty instead

scapy==2.4rc5 is wrong, scapy==2.4rc4 and below was OK

### PR DESCRIPTION
**Pull request by guedou**
This PR fixes #1242

### CODE REVIEW

**Comment by p-l-** [comment]
@guedou this breaks the tests

**Comment by guedou** [comment]
@p-l- it looks ok now. I moved the unit test to a different location.

**Comment by karpierz** [comment]
Try to move it at the end of file.
I had the same problem with #1238 and still very often have with #1240 (despite the fact that I did not change anything in the tests)

**Comment by karpierz** [comment]
Please take a look at #1256 and please confirm and it for merge.

**Comment by p-l-** [comment]
@guedou Can you rebase against current master?

**Pull request merged**
