### PR TITLE
macOS catalina support

### LINKED ISSUE #2134: Mac OS Catalina
**From:** https://stackoverflow.com/q/56936549/5459467

> I'm trying to create a sniffer from the scapy module. I'm running Python 3.7 on macOS Catalina. Assuming that it's something with the macOS Catalina public beta version. I just wanna know what's causing the problem if so. I'm trying hard to understand why scapy throws an index out of bounds trace:
> 
> **main.py**
> 
> ```
> import scapy.all as scapy
> 
> p = scapy.sniff()
> 
> p.summary()
> Result:
> 
> Traceback (most recent call last):
>   File "/Users/tom/PycharmProjects/sniffer/main.py", line 2, in <module>
>     import scapy.all as scapy
>   File "/Users/tom/PycharmProjects/sniffer/venv/lib/python3.7/site-packages/scapy/sendrecv.py", line 33, in <module>
>     import scapy.route  # noqa: F401
>   File "/Users/tom/PycharmProjects/sniffer/venv/lib/python3.7/site-packages/scapy/route.py", line 194, in <module>
>     conf.route = Route()
>   File "/Users/tom/PycharmProjects/sniffer/venv/lib/python3.7/site-packages/scapy/route.py", line 27, in __init__
>     self.resync()
>   File "/Users/tom/PycharmProjects/sniffer/venv/lib/python3.7/site-packages/scapy/route.py", line 35, in resync
>     self.routes = read_routes()
>   File "/Users/tom/PycharmProjects/sniffer/venv/lib/python3.7/site-packages/scapy/arch/unix.py", line 82, in read_routes
>     netif = rt[4 + mtu_present + prio_present + refs_present + locked]
> IndexError: list index out of range
> ```

I'd guess it is indeed related to Catalina, but am no expert. @guedou Could you please have a look?

### PR DESCRIPTION
**Pull request by guedou**
This fixes #2134 and adds mocked test for read_routes on 10.13.

### CODE REVIEW

**Comment by gpotter2** [comment]
All good to me ! Thanks for the quick fix

**Comment by gpotter2** [comment]
Could you also add the tests for IPv6 ?
The routes were also provided in the results I posted previously

**Comment by guedou** [comment]
It is the same output as the currently mocked read_routes6() for 10.9.5

**Comment by Tom73525** [comment]
I was working on the same project on ubuntu for a while and then got back here on Catalina to update scapy. Worked like a charm. Thanks for the fix!

**Pull request merged**
