### PR TITLE
DoIp: fix socket not handling IPv6 link-local address

### PR DESCRIPTION
**Pull request by sa-isd**
Fix for the issue where calling ```s.connect()``` via ```UDS_DoIPSocket6()``` on a ipv6 link local address will result in the error
```OSError: [Errno 22] Invalid argument```

transmission over ipv6 link local addresses cannot be done until their scope ids/zone ids are also mentioned.

This can be easily obtained using ```getaddrinfo``` which also works for any ipv4 address.
e.g)
```
>>> addrinfo = socket.getaddrinfo("fe80::9480:f529:aa6c:c2ba%enp0s3", None, proto=socket.IPPROTO_TCP)
>>> print(addrinfo[0][-1])
('fe80::9480:f529:aa6c:c2ba', 0, 0, 2)
```
2 is the scope id for my iface name enp0s3.

### CODE REVIEW

**Comment by polybassa** [comment]
LGTM. @guedou what do you think?

**Review by KhazAkar — COMMENTED** [review]
Looks good to me. If it works for IPv4 as well, maybe having it in v4 socket version, done also here, would be appropriate. What do you thing @polybassa ?

**Comment by sa-isd** [comment]
is there something left that I have to do for the merge?

**Comment by KhazAkar** [comment]
@sa-isd Can you make something similar, but for IPv4 as well? @gpotter2 do you agree on this?

**Comment by gpotter2** [comment]
No, this is completely irrelevant

**Review by gpotter2 — APPROVED** [review]

**Pull request merged**
