### PR TITLE
Improve parsing of UDS DTC Snapshots and ExtendedData

### PR DESCRIPTION
**Pull request by polybassa**
This PR changes the definition of DTCs inside the UDS_RDTCI packet to have a better representation of the DTC. Additionally, a DTC Snapshot Packet class is introduced to allow customization of DTC Snapshot records for individual ECUs

### CODE REVIEW

**Comment by polybassa** [comment]
@gpotter2 @guedou Can this PR get merged, please?

**Comment by gpotter2** [comment]
It's a bad practice to start PRs with no description. Generally when I see stuff like that I think that it's a draft.

**Comment by polybassa** [comment]
> It's a bad practice to start PRs with no description. Generally when I see stuff like that I think that it's a draft.

Sorry

**Comment by polybassa** [comment]
@gpotter2 @guedou Can this PR get merged, please?

**Review by guedou — APPROVED** [review]

**Pull request merged**
