### PR TITLE
OBD_Scanner and ISOTP improvements and speedup

### PR DESCRIPTION
**Pull request by polybassa**
Improvement of `obdscanner.uts`, `isotp.uts` and `isotp_scan.uts`. Some bugs in `obdscanner.py` and a bug in `isotpscan` will be fixed.

### CODE REVIEW

**Comment by p-l-** [comment]
Hi!
Can you rebase against current master?
Thanks!

**Comment by polybassa** [comment]
Done

**Comment by gpotter2** [comment]
Assuming the log files are a mistake ?

**Comment by polybassa** [comment]
I want to add some more unit tests based on these log files in the next days. They are there on purpose, but not used, yet. If this is a issue, I'll remove them.

**Comment by p-l-** [comment]
It's OK for me to keep those log files if you intend to use them. @gpotter2 what do you think?

**Comment by gpotter2** [comment]
I'm not a fan of having unused giant files lying around, I'd rather have them removed

**Comment by polybassa** [comment]
Alright, I will remove them. Wheo I use them, I'll make same as small as possible.


-- 
Viele Grüße

Nils Weiß

**Comment by polybassa** [comment]
Logs removed. Ready

**Comment by polybassa** [comment]
I'm investigation the failure on pypy3

**Pull request merged**
