### PR TITLE
DRAFT: Add support for MPTCP

### LINKED ISSUE #3333: Add support for MPTCP
Add support for MPTCP as described in [RFC 8684](https://datatracker.ietf.org/doc/html/rfc8684).

I've already implemented the dissection of the options for a personal use case, and I would like to continue the work and contribute with full support to Scapy. However since MPTCP is a more complex TCP option I was not sure what approach I should use to implement it fitting the already existing TCP options. 

Therefore before carrying on I would like to know if the approach I used is valid or if a should refactor it, and if so, what is the best/correct way for doing it.

Thanks.

### PR DESCRIPTION
**Pull request by RuiCunhaM**
**Checklist:**

-   [x] If you are new to Scapy: I have checked [CONTRIBUTING.md](https://github.com/secdev/scapy/blob/master/CONTRIBUTING.md) (esp. section submitting-pull-requests)
-   [ ] I squashed commits belonging together
-   [ ] I added unit tests or explained why they are not relevant
-   [ ] I executed the regression tests for Python2 and Python3 (using `tox` or, `cd test && ./run_tests_py2, cd test && ./run_tests_py3`)
-   [x] If the PR is still not finished, please create a [Draft Pull Request](https://github.blog/2019-02-14-introducing-draft-pull-requests/)

fixes #3333

### CODE REVIEW

**Comment by gpotter2** [comment]
Hi & thanks for the PR ! A few comments:
- you can re-implement your MPTCP dissection module by creating a Scapy packet layer. This will be much faster and will already support building (+ it's much closer to the "scapy spirit")
- you can probably implement that directly into `scapy/layers/inet.py`

Supporting this extension would be a nice feature ! Thanks for your interest on that

**Comment by RuiCunhaM** [comment]
Hi! Thank you for your answer!
I think I understand what you're suggesting, once I have the time again I'll give it a try.

**Comment by RuiCunhaM** [comment]
@gpotter2 Sorry for tagging you but I finally had the time to get back to this, and I must confess that I'm now confused by what you suggested before.

I can't quite figure out how I'm supposed to use a Scapy packet layer in the current options parsing of the TCP. I know that at some point there was something like a TcpOption class that could be extended, but now, with the current format, using structs directly when parsing and encoding options I don't understand how this would fit. Should I call directly decode/encode methods from the Packet class or something similar?

I'm sorry if this is something trivial that I'm missing, but if you could elaborate a bit more on how a Packet layer can be used directly with the current logic I would appreciate it.

Thanks in advance.

**Comment by stryngs** [comment]
@RuiCunhaM Do you have an example pcap handy?

**Comment by RuiCunhaM** [comment]
Hello @stryngs. I believe the ones in the [tcpdump tests](https://github.com/the-tcpdump-group/tcpdump/tree/master/tests) cover most of the options in the protocol.

**Comment by matttbe** [comment]
Hello,

Just in case you need more MPTCP (mostly v1) traces, feel free to look at: https://github.com/multipath-tcp/packetdrill/files/7958963/traces.tar.gz (from https://github.com/multipath-tcp/packetdrill/pull/76)

**Comment by gpotter2** [comment]
Closing for inactivity.

**Pull request closed without merging**
