### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ilqxejraha**
在使用的的过程中，出现了很多错误，最后找到的解决方案就是这个，所以把这一句加入到了文档里面，这个可以帮助到很多在windows下的用户。

### CODE REVIEW

**Comment by gpotter2** [comment]
From google translate:

>In the process of using, there are a lot of mistakes, >and finally found the solution is this, so this sentence >added to the document inside, this can help a lot of >users under the windows.

**Comment by guedou** [comment]
I would like to keep the README short. Could you add this to the documentation: https://github.com/secdev/scapy/blob/master/doc/scapy/installation.rst

Also, please write in english.

**Comment by ilqxejraha** [comment]
Ok, thank you. 
I wrote something in English in install.rst. I don't know how you feel?
I used this project a long time ago. I hope that the author will be able to migrate to the version of python3.

**Comment by guedou** [comment]
Please submit another PR, and I will review it.

**Pull request closed without merging**
