### PR TITLE
Attempt to set Packet.explicit to True as often as possible

### PR DESCRIPTION
**Pull request by p-l-**
@guedou I did not run performance tests to check whether the new code is faster. I suppose it will, when defining (not from a string) the sending or writing a lot of packets, but since this PR makes the code more complex, I think it's worth testing it before considering it. What do you think?

### CODE REVIEW

**Comment by gpotter2** [comment]
I personnally used:
```
from scapy.all import *
import time

beg = int(round(time.time() * 1000))

for i in range(1,10000):
     # this has no sense...
     packet = Ether(dst="127.0.0.1", src="127.0.0.1")/IP("")/TCP(options={"XXX"})/Ether()/IP()/TCP()
     l = packet/packet
     
end = int(round(time.time() * 1000))

print "Took " + str(end-beg) + " ms"
```

And i got:
- Without this PR:
```
PS Z:\github> python .\speedtest.py
Took 16433 ms
PS Z:\github> python .\speedtest.py
Took 16668 ms
```
- With this PR:
```
PS Z:\github> python .\speedtest.py
Took 19133 ms
PS Z:\github> python .\speedtest.py
Took 20458 ms
```

**Comment by p-l-** [comment]
@gpotter2 the purpose of this PR is to increase calls to `str()` or `send()`, for example.

**Comment by gpotter2** [comment]
@p-l- Here are my new tests:

- This PR:
```
[...]
Sent 1 packets.
Took 4704 ms
```

```
[...]
Sent 1 packets.
Took 4886 ms
```

- master:
```
[...]
Sent 1 packets.
Took 4906 ms
```

```
[...]
Sent 1 packets.
Took 4737 ms
```

Using:
```
from scapy.all import *
import time

beg = int(round(time.time() * 1000))

for i in range(1,2000):
     packet = Ether()/IP(dst="1.2.3.4")/ICMP()
     send(packet)
     
end = int(round(time.time() * 1000))

print "Took " + str(end-beg) + " ms"
```

**Comment by p-l-** [comment]
This makes things really worse:
Without:
```
>>> timeit.timeit("str(Ether()/IP()/UDP())", number=10000)
7.781938791275024
```
With:
```
>>> timeit.timeit("str(Ether()/IP()/UDP())", number=10000)
8.35347604751587
```

**Pull request closed without merging**
