### PR TITLE
Fix #3197

### LINKED ISSUE #3197: 100% CPU load while sniffing traffic on 2.4.5
#### Brief description

While sniffing for probe requests on a wireless interface on a Raspberry Pi 4 Model B Rev 1.4, one CPU core is constantly 100% busy.

#### Environment

-   Scapy version: 2.4.5 / master branch
-   Python version: 3.7.3
-   Operating System: Raspbian GNU/Linux 10 (buster)

#### How to reproduce

1. Put the wireless interface in monitor mode:
```bash
ip link set wlanX down
iw dev wlanX set type monitor
ip link set wlanX up
```

2. Start sniffing for probe requests:
```python
source = SniffSource(iface='wlanX', filter='type mgt subtype probe-req')
sink = ConsoleSink()
source > sink

p = PipeEngine(source)
p.start()
p.wait_and_stop()
```

#### Actual result

Now start top in another session and watch CPU load:
```
top - 20:50:42 up 6 days,  2:46,  2 users,  load average: 0.74, 0.24, 0.09
Tasks: 120 total,   1 running, 119 sleeping,   0 stopped,   0 zombie
%Cpu0  : 66.1 us, 33.6 sy,  0.0 ni,  0.0 id,  0.0 wa,  0.0 hi,  0.3 si,  0.0 st
%Cpu1  :  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu2  :  3.0 us,  0.0 sy,  0.0 ni, 97.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu3  :  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
MiB Mem :   7875.3 total,   7303.0 free,     97.1 used,    475.1 buff/cache
MiB Swap:    100.0 total,    100.0 free,      0.0 used.   7526.4 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
26761 root      20   0   44948  27364   9028 S 100.0   0.3   1:21.48 scapy
...
```

#### Expected result

Expected CPU load to be far less than 100%.

#### Additional information
1. Downgrading to 2.4.4 solves the issue. CPU load is just a few percent, depending on how many frames are actually received by the frame filter
2. Both 2.4.5 and master branch expose this issue
3. Only dissecting the packets with scapy 2.4.5 (using pcapy to capture with frame filter) does not show the same CPU load. Tested with:
```python
import pcapy
from scapy.all import *
import sys

def pkt_callback(hdr, data):
    rt = RadioTap(data)
    rt.show()
    pr = rt.getlayer(Dot11ProbeReq)
    print(f"type:{rt.type} subtype:{rt.subtype} ts:{rt.time} signal:{rt.dBm_AntSignal}dBm rate:{rt.Rate} ant:{rt.Antenna} s_mac:{rt.addr2} BSSID:{pr.info.decode('utf-8')}")

def main():
    packets = pcapy.open_live(sys.argv[1], 1514, 1, 10)
    packets.setfilter('subtype probe-req')
    packets.loop(-1, pkt_callback)

if __name__ == '__main__':
    main()
```

### PR DESCRIPTION
**Pull request by polybassa**
fixes #3197

### CODE REVIEW

**Comment by gpotter2** [comment]
Hmm. We should have set something like 0.5 instead. Would you mind checking if the CPU load is still alright with such a value? I'm currently not on Linux.

**Comment by polybassa** [comment]
0.5 is ok, even 0.1 is ok. what do you want in the PR?

**Comment by gpotter2** [comment]
Hmm, depends how responsive we want `stop()` to be. Any value between 0.5 and 0.1 is fine by me

**Comment by polybassa** [comment]
I'll put it to 0.5. I don't have any preference here.

**Comment by polybassa** [comment]
opened another PR with 0.5  #3199

**Pull request merged**
