### PR TITLE
Uds fix

### PR DESCRIPTION
**Pull request by superuserx**

### CODE REVIEW

**Comment by polybassa** [comment]
This PR was developed together with me. I approve it.

**Comment by gpotter2** [comment]
Please rebase against master to fix the mypy test

**Comment by superuserx** [comment]
done

**Comment by gpotter2** [comment]
Thanks. What does this PR do?

We usually require some sort of explanation. Because this is automative-related and endorsed by polybassa we don't ask too many questions but it would be nice to have one FTR (this also applies to all automative-based PRs).

**Comment by polybassa** [comment]
During some work with the `ECU_am` we discovered a undesired behaviour. Here a example
```python
#Good example:
req:   UDS(service=0x22)/UDS_RDBI(identifiers=[0x1234])
resp: UDS(service=0x62)/UDS_RDBIPR(dataIdentifier=0x1234)/Raw(load=b"someSecret")
#Bad example:
req:   UDS(service=0x22)
resp: UDS(service=0x62)/UDS_RDBIPR(dataIdentifier=0x1234)/Raw(load=b"someSecret")
#General Response example:
req:   UDS(service=0x22)/UDS_RDBI(identifiers=[0x1234])
resp: UDS(service=0x62)
```
An ECU_am holds a list of possible responses. As soon the answering machine receives a req, it searches in a list of possible responses to find a proper one. Here it evaluates `answers` to find a proper response for a request. Assume we have a answering machine with the response mentioned in my example. The good case describes the default behaviour. Some one asks for a data identifier through `ReadDataByIdentifier`. The answer to that is a `ReadDataByIdentifierPositiveResponse` with some payload. Unfortunately also the bad example worked in our case, and the payload was sent. Even without specifying a data identifier. This happened through answers. The code of answers of `UDS` tries to delegate the evaluation to the lower layer. This is only possible, if both classes (req and resp) have a lower layer. If one of req and resp do not have a lower layer, I just evaluated the field `service` to determine, if a resp answers a req. This default behaviour was wrong. 
The new behaviour considers the length of a response and a request. If a response has more information than the service, the response can not answer to the request. If both have the same length (in UDS it has to be 1) the response answers the request. If I added a general response like in the last example, to my answering machine, it's also desired to answer on requests which have more data. Here I need to take care about the order of responses in my answering machine.

**Comment by polybassa** [comment]
Sorry for not providing a description in the first place. I will force to make better PRs.

**Pull request merged**
