### PR TITLE
Fix handle inheritance for Python2 (more appropriate and safe version of #1138 hack, fixes #1136)

### LINKED ISSUE #1136: [Windows] POWERSHELL_MANAGER is never closed explicitly
scapy-2.4.0rc4.dev58-py2.7
Windows 7

POWERSHELL_MANAGER isn't closed in arch/windows/__init__.py

That's a problem, because subprocess used inherits open files. The files can't be deleted without waiting for scapy to end (sleep-wait-repeat).

I've added POWERSHELL_MANAGER.close() near the bottom of __init__.py and it solved the problem.

Steps to reproduce:
1. Create a file.
2. Replace sys.stdout/stderr with it (I'm doing a tee)
3. Import scapy
4. Try to remove created file after closing it

Observed behaviour:
- exception - file in use, can't be deleted

Expected behaviour:
- file is deleted just fine

Reproducible:
- always

### PR DESCRIPTION
**Pull request by karpierz**
Scapy Version: 2.4.0rc5-28
System: Windows7/Windows10
Python Version: 2.7.14/3.4.4/3.6.4

Fix a handle inheritance for Python2 (more appropriate and safe version of #1138 hack, fixes #1136)
Fix an error of '_windows_title()' for Python2

Thanks,
Adam Karpierz

### CODE REVIEW

**Comment by karpierz** [comment]
Manual tests (automatic tests cannot be performed because it is launched _after_ scapy starts):

```
import os
import scapy.arch.windows

def test():
    open("ZZZ", "w").write("ddddd")
    with open("ZZZ") as f:
        POWERSHELL_PROCESS = scapy.arch.windows._PowershellManager()
    os.remove("ZZZ")

print("\nWith preventing file handles inheritance")
test()
print("OK")

print("\nWithout preventing file handles inheritance")
scapy.arch.windows._suppress_file_handles_inheritance = lambda r=1000: []
test()
print("OK")
```

Output is:
```

D:\_DiskP_\Py\scapy_fork>pipi27 .
Processing d:\_diskp_\py\scapy_fork
Installing collected packages: scapy
  Running setup.py install for scapy ... done
Successfully installed scapy-2.4.0rc5.dev30

D:\_DiskP_\Py\scapy_fork>pipi34 .
Processing d:\_diskp_\py\scapy_fork
Installing collected packages: scapy
  Running setup.py install for scapy ... done
Successfully installed scapy-2.4.0rc5.dev30

D:\_DiskP_\Py\scapy_fork>pipi36 .
Processing d:\_diskp_\py\scapy_fork
Installing collected packages: scapy
  Running setup.py install for scapy ... done
Successfully installed scapy-2.4.0rc5.dev30

D:\_DiskP_\Py\scapy_fork>py27 z.py

With prevent file handles inheritance
OK

Without prevent file handles inheritance
Traceback (most recent call last):
  File "z.py", line 16, in <module>
    test()
  File "z.py", line 8, in test
    os.remove("ZZZ")
WindowsError: [Error 32] Proces nie mo┐e uzyskaŠ dostŕpu do pliku, poniewa┐ jest on u┐ywany przez inny proces: 'ZZZ'

D:\_DiskP_\Py\scapy_fork>py34 z.py

With prevent file handles inheritance
OK

Without prevent file handles inheritance
OK

D:\_DiskP_\Py\scapy_fork>py36 z.py

With prevent file handles inheritance
OK

Without prevent file handles inheritance
OK

D:\_DiskP_\Py\scapy_fork>
```

**Comment by karpierz** [comment]
:> Sorry I don't understand what's not working.
:> Could you please provide a sample of something that crashes with current code ?

I tested the scripts you provided and could not make it crash :/
:> I tested the scripts you provided and could not make it crash :/

Because I'v changed a name of the function but you - I suppose - used a master - not my branch.
Just now I'v restored original: in the repo and in the example test. Please try again. 

I cannot attach the code because it is production code of our customers - code that opens a lot of files and redirecting stdout/stderr by a different ways.
Simply: your patch changes inheritance mode for handlers  and does not restored it (my only realized such weakness).
It is subtle but real breaking of backward compatibility against scapy<=2.3.2.
Why? Missing of restoring inheritance mode may and have influence for other "foreign" subprocesses.
It is even not compatible with Py3 where handle inheritance protection is being implemented by other way than change inheritance mode - by the appropraiate parameter of CreateProcess WINAPI function.

**Comment by karpierz** [comment]
Reopen due to Travis problem/fail.

**Comment by karpierz** [comment]
Reopen again due to Travis problem/fail.

**Comment by karpierz** [comment]
PR is ready for review and merge to the master.

**Comment by karpierz** [comment]
Manual test code for verify an error of '_windows_title()':

```
from scapy.config import conf
import scapy.arch.windows

conf.interactive = True
scapy.arch.windows._windows_title("Title is OK!")
input()
```

On original master for Python2 it gets improper result (can even cause GPF).

**Comment by karpierz** [comment]
PR is ready for review and merge to the master.

**Comment by karpierz** [comment]
scapy

**Comment by karpierz** [comment]
PR is ready for review and for merge to the master.

**Comment by guedou** [comment]
@gpotter2 It looks fine. Do you agree to merge it?

**Pull request merged**
