### PR TITLE
[isis.py] Add support for some SubTLVs

### PR DESCRIPTION
**Pull request by mkaliszan**

### CODE REVIEW

**Comment by guedou** [comment]
Thanks for your patch. Could you add the corresponding unit tests in the `isis.uts` file ?

**Comment by mkaliszan** [comment]
The units were extended to cover the Sub-TLV support. Some issues in isis.py and ospf.py were also fixed.

**Comment by mkaliszan** [comment]
Hi, I fixed a couple of issues and extended the module and the unit 
tests. Should I start a new pull request?

**Comment by mkaliszan** [comment]
Tests run fine in Travis CI after merging recent commits from secdev:master onto this branch.

**Comment by p-l-** [comment]
Hi,

Thanks for this patch! For your next PR it's better to rebase against master rather than adding a merge commit.

**Pull request merged**
