### PR TITLE
Add run on repl.it badge to README

### PR DESCRIPTION
**Pull request by yoloforreal**
This pull request adds a  badge to the . This will allow users to easily run this repository in their browser, without having to set up an environment. You can learn more about Repl.it [here](https://repl.it).

**Checklist:**

-   [ ] If you are new to Scapy: I have checked [CONTRIBUTING.md](https://github.com/secdev/scapy/blob/master/CONTRIBUTING.md) (esp. section submitting-pull-requests)
-   [ ] I squashed commits belonging together
-   [ ] I added unit tests or explained why they are not relevant
-   [ ] I executed the regression tests for Python2 and Python3 (using `tox` or, `cd test && ./run_tests_py2, cd test && ./run_tests_py3`)
-   [ ] If the PR is still not finished, please create a [Draft Pull Request](https://github.blog/2019-02-14-introducing-draft-pull-requests/)

fixes #xxx

### CODE REVIEW

**Comment by guedou** [comment]
Why did you modify the complete README?

**Comment by p-l-** [comment]
> Why did you modify the complete README?

I think it's just a mess-up with the symlink `README -> README.md`.

**Comment by guedou** [comment]
I tried repl.it. It looks nice but I do no see the benefit of adding a badge to our README without any explanation. I would rather accept a small documentation that explains how to experiment with Scapy on this website.

**Comment by p-l-** [comment]
I'm not *per se* against this badge, but I'd rather have it after the existing ones. Also, a bit of documentation would help, I agree!

**Comment by guedou** [comment]
Closed due to no activity. Feel free to reopen if you can work on the suggestions.

**Pull request closed without merging**
