### PR TITLE
Drop DNET & cleanup travis/tox

### PR DESCRIPTION
**Pull request by gpotter2**
- drop deprecated dnet support (2years)
- finish grouping sudo/non-sudo travis tests (some where already)
- cleanup tox
- update travis ci config format
- fix linux_warning test
- automatically disable tests that require root when running non root within UTscapy
- fix cryptography deprecations
- fix some python3-only buggy tests

This should speed up travis builds a lot

### CODE REVIEW

**Comment by gpotter2** [comment]
@guedou Ready for review

**Comment by gpotter2** [comment]
@guedou @p-l- Please review, should be ready to merge.

**Comment by polybassa** [comment]
This PR skips the tests for obdscanner and isotpscanner. I think all tests with native isotpsockets are skipped.
-- 
Viele Grüße

Nils Weiß

**Comment by gpotter2** [comment]
@polybassa It seems that the vcan module was actually never on, and never had in unit tests because of a depedency issue (or something similar). Fixing that apparently brings new issues that are unrelated to the changes in this PR. Could you please have a loot ? Thanks

**Comment by polybassa** [comment]
I will have a look!
-- 
Viele Grüße

Nils Weiß

**Comment by polybassa** [comment]
Apparently, pypy3 doesn't support `PF_CAN`. Is there a simple way for you to remove this tests on pypy3? On pypy2 they are removed already. 
The following diff fixes the test on the isotp-kernel-module build
```
diff --git a/test/contrib/isotp.uts b/test/contrib/isotp.uts
index e5043fdd..700bb166 100644
--- a/test/contrib/isotp.uts
+++ b/test/contrib/isotp.uts
@@ -142,6 +142,8 @@ if p.wait() == 0:
 conf.contribs['ISOTP'] = {'use-can-isotp-kernel-module': False}
 load_contrib("isotp")
 
+ISOTPSocket = ISOTPSoftSocket
+
 + ISOTP packet check
 
 = Creation of an empty ISOTP packet
```

**Comment by polybassa** [comment]
I will investigate the failing tests. Sorry for the inconvenience

**Comment by polybassa** [comment]
Apparently, pypy3 has a reliable deadlock at this line: https://github.com/secdev/scapy/blob/0984c0053f3a85ad7a7d3706a82ab074728b578d/scapy/contrib/cansocket_python_can.py#L106
I've tested this on my system. Surprisingly the python3 interpreter doesn't fail. Do you know if pypy3 does the handling of `with` different than python3?

**Comment by gpotter2** [comment]
Pypy3 is likely never to call the `__del__` functions. Other than that it should be the same. Are you actively depending on 
https://github.com/secdev/scapy/blob/701be894b3b90b25c644f484b68d690a05d49cbf/scapy/contrib/isotp.py#L1126
?

**Comment by polybassa** [comment]
@epozzobon and me just found the bug. Here is a patch:
```
diff --git a/test/contrib/isotp.uts b/test/contrib/isotp.uts
index 86452dea..8eb8fefb 100644
--- a/test/contrib/isotp.uts
+++ b/test/contrib/isotp.uts
@@ -1285,33 +1285,33 @@ assert (isotp.dst == 0x241)
 
 = Receive a two-frame ISOTP message
 with new_can_socket0() as isocan, ISOTPSocket(isocan, sid=0x641, did=0x241) as s:
-    cans = new_can_socket(iface0)
-    cans.send(CAN(identifier = 0x241, data = dhex("10 0B 01 02 03 04 05 06")))
-    cans.send(CAN(identifier = 0x241, data = dhex("21 07 08 09 10 11")))
+    with new_can_socket(iface0) as cans:
+        cans.send(CAN(identifier = 0x241, data = dhex("10 0B 01 02 03 04 05 06")))
+        cans.send(CAN(identifier = 0x241, data = dhex("21 07 08 09 10 11")))
     isotp = s.recv()
     assert(isotp.data == dhex("01 02 03 04 05 06 07 08 09 10 11"))
 
 = Check what happens when a CAN frame with wrong identifier gets received
 with new_can_socket0() as isocan, ISOTPSocket(isocan, sid=0x641, did=0x241) as s:
-    cans = new_can_socket(iface0)
-    cans.send(CAN(identifier = 0x141, data = dhex("05 01 02 03 04 05")))
+    with new_can_socket(iface0) as cans:
+        cans.send(CAN(identifier = 0x141, data = dhex("05 01 02 03 04 05")))
     assert(s.ins.rx_queue.empty())
 
 + Testing ISOTPSocket timeouts
 
 = Check if not sending the last CF will make the socket timeout
 with new_can_socket0() as isocan, ISOTPSocket(isocan, sid=0x641, did=0x241) as s:
-    cans = new_can_socket(iface0)
-    cans.send(CAN(identifier = 0x241, data = dhex("10 11 01 02 03 04 05 06")))
-    cans.send(CAN(identifier = 0x241, data = dhex("21 07 08 09 0A 0B 0C 0D")))
+    with new_can_socket(iface0) as cans:
+        cans.send(CAN(identifier = 0x241, data = dhex("10 11 01 02 03 04 05 06")))
+        cans.send(CAN(identifier = 0x241, data = dhex("21 07 08 09 0A 0B 0C 0D")))
     isotp = s.sniff(timeout=1)
 
 assert(len(isotp) == 0)
 
 = Check if not sending the first CF will make the socket timeout
 with new_can_socket0() as isocan, ISOTPSocket(isocan, sid=0x641, did=0x241) as s:
-    cans = new_can_socket(iface0)
-    cans.send(CAN(identifier = 0x241, data = dhex("10 11 01 02 03 04 05 06")))
+    with new_can_socket(iface0) as cans:
+        cans.send(CAN(identifier = 0x241, data = dhex("10 11 01 02 03 04 05 06")))
     isotp = s.sniff(timeout=1)
 
 assert(len(isotp) == 0)
@@ -1649,9 +1649,9 @@ with new_can_socket0() as cs1, ISOTPSocket(cs1, sid=0x641, did=0x241) as s1, \
 
 = Send a single frame ISOTP message with padding
 with new_can_socket0() as cs1, ISOTPSocket(cs1, sid=0x641, did=0x241, padding=True) as s:
-    cans = new_can_socket(iface0)
-    s.send(ISOTP(data=dhex("01")))
-    res = cans.sniff(timeout=1, count=1)[0]
+    with new_can_socket(iface0) as cans:
+        s.send(ISOTP(data=dhex("01")))
+        res = cans.sniff(timeout=1, count=1)[0]
     assert(res.length == 8)
 
```

Basically, the problem was that some sockets weren't closed correctly. This should be fixed now. 
You can see the changes here, as well: https://github.com/polybassa/scapy-1/commit/fdf16db48a8279be08edd52dceacf319f2d8c71f

Hope that helps!

**Comment by gpotter2** [comment]
Thanks for the fix, that's what i had in mind.

**Comment by polybassa** [comment]
Apparently, the tests for `tools/obdscanner.uts` didn't get updated during the python-can refactoring. You can disable this tests and write an issue for me. I'll fix that.

**Comment by gpotter2** [comment]
I managed to fix that. It was due to using PyPy.
However i spotted that those happen consistently on all PyPy2 and 3 tests (maybe other tests too ?)

```
passed E11844EE 030.12s Test extended ISOTPScan(output_format=None)
3909Test failed. Automatically increase sniff time and retry.
3910passed 5AC729BE 064.36s Test ISOTPScan(output_format=None) random IDs
3911Test failed. Automatically increase sniff time and retry.
3912passed 13A35525 063.08s Test ISOTPScan(output_format=None) random IDs padding
```
A UTscapy test shouldn't take this long. I think I'll add a timeout maxed out at 30seconds in a future PR.

**Comment by polybassa** [comment]
I added #2502 to speed the isotpscan tests up. I would like to keep the retry, so far. I figured out, that the load of the system can influence the tests, which leads to more longer timings for systems under load. I will keep a eye on that tests, to see if I can remove the retry. But for convenience (to not have Travis failing randomly) I would still keep the retry for now.

**Comment by gpotter2** [comment]
Ready

**Pull request merged**
