### PR TITLE
Introduce tcpdump() function

### PR DESCRIPTION
**Pull request by p-l-**
One can now use tcpdump or tshark to dissect packets from
Scapy. This can help, for example, to check Scapy's dissectors

### CODE REVIEW

**Comment by p-l-** [comment]
@guedou can you help me debug what happens under MacOS? I have no MacOS machine to test that.

**Comment by guedou** [comment]
I just tried it, and OS X `tcpdump` flavour does not support reading on stdin =/

**Comment by gpotter2** [comment]
It appears that this is a common issue 
http://apple.stackexchange.com/questions/152682/why-does-tcpdump-not-recognise-piped-input

So i guess the best option is to use a temp file on OSX only

**Comment by p-l-** [comment]
Thanks a lot @gpotter2! I'll check that!

**Comment by p-l-** [comment]
Thanks @guedou & @gpotter2, that's now ready to merge for me.

This PR now takes advantage of the `tcpdump()` function to factorize code for `sniff()` with `filter` parameter set.

**Comment by guedou** [comment]
Good for me.

@p-l- should I squash this one ?

**Comment by p-l-** [comment]
@guedou the commits are units here, so it's better if you just merge if that's fine for you. Thanks!

**Pull request merged**
