### PR TITLE
E275 - Missing whitespace after keyword 

### PR DESCRIPTION
**Pull request by polybassa**

### CODE REVIEW

**Comment by polybassa** [comment]
I've applied some regex based replacements. Let's see if it smokes.

**Comment by guedou** [comment]
Thanks! What is the error message or the PEP number that this PR is fixing ?
It could be relevant to reflect it in the commit message

**Comment by polybassa** [comment]
E275
-- 
Viele Grüße

Nils Weiß

**Comment by guedou** [comment]
A good example if commit message for this kind of change is https://github.com/secdev/scapy/pull/1612

Could you also add the Co-Author-by to reflect the latest author of the line that this PR is modifying?

I know that this is a bit complicated but these as the rules that we defined in https://github.com/secdev/scapy/issues/1277

Thanks

**Comment by polybassa** [comment]
Phuu .. do you have a handy git blame command to obtain that information?
-- 
Viele Grüße

Nils Weiß

**Comment by polybassa** [comment]
Added all the Co-Authors

**Comment by guedou** [comment]
I usually do:
```
flake8 --select=E20 scapy/ > lines.txt
bash pepin.sh > co-authored-by.txt
```
[pepin.sh.txt](https://github.com/secdev/scapy/files/9277110/pepin.sh.txt)

**Review by guedou — APPROVED** [review]

**Comment by polybassa** [comment]
Thanks. Good to know for next time 
-- 
Viele Grüße

Nils Weiß

**Review by gpotter2 — APPROVED** [review]
Freel free to merge @guedou

**Comment by gpotter2** [comment]
Thanks a lot for doing this polybassa !

**Comment by polybassa** [comment]
You are welcome. Thanks to my IDE for search and replace ;-)

**Pull request merged**
