### PR TITLE
Corrected ICV length for AES-GCM and AES-CCM in IPSec layer. Added un…

### PR DESCRIPTION
**Pull request by kinap**
…it tests to the ipsec campaign.

### CODE REVIEW

**Comment by kinap** [comment]
CI is failing because of the tests I added to ipsec.ut and AES-GCM/AES-CCM only being available in pycrypto2.7a1. 

How did you want to handle this? I use these features and would like them to be regressed. Is there a way for UTscapy to skip over unsupported algorithms?

**Comment by kinap** [comment]
@p-l- Any input? Do you wait for CI to pass before looking at PRs?

**Comment by guedou** [comment]
I am OK with using pycrypto2.7a1 for specific features. However, could you add some lines in the documentation explaining how to install it with `pip`, for example ? 
Also, a `warning()` call will be nice when trying to use combined modes with an old module.

Concerning, the failed tests. We could:
- tag the CCM and GCM unit tests with "~ needs_combined_modes" (as done [here](https://github.com/secdev/scapy/blob/fdf35d98b401005805ddecaa144e64647e0aee90/test/edns0.uts#L49)).

- add a new target in `.travis.yml` such as:
```
        - os: linux
          python: 2.7
          env:
            - TEST_COMBINED_MODES=yes
```
- modify `.travis/install.sh `and `.travis/test.sh` to install pycrypto2.7a1 and activate needs_combined_mode when TEST_COMBINED_MODES is set

Do you feel like modifying the travis files ? I could give you some advice.

**Comment by kinap** [comment]
I'm up for making the changes. Haven't dug into travis before, so let me go take a look and I'll come back with questions.

**Comment by guedou** [comment]
You can start with the shell scripts, and mimic Travis behavior by setting environment variables.

**Comment by kinap** [comment]
@guedou Not sure about that last failure. How does the rest of it look?

**Comment by guedou** [comment]
@kinap it is not related to your patch. From time to time sending/receiving packets fail on Travis OS X. We need to restart the tests manually. I just did. Let's see how it goes.

**Comment by p-l-** [comment]
Nice! (sorry for the delay).
One detail, could you change `needs_combined_modes` to `combined_modes`? Since `netaccess`, for example, means "needs net access". Thanks!

**Comment by kinap** [comment]
@guedou I forgot to update the documentation. Let me do that and add it to this PR.

**Comment by kinap** [comment]
Alright I think I got it all in there.

**Comment by guedou** [comment]
@p-l good to merge !

@kinap Could you rebase or tell us if wecan hit the "squash and merge" button on github.

**Comment by kinap** [comment]
Rebased.

**Comment by kinap** [comment]
Any problem getting this merged?

**Comment by guedou** [comment]
@kinap nothing except the 2.3.3 release. We wanted the cool features to be part of the future 2.4.0. Sorry for the delay, everything should be back to normal soon.

**Pull request merged**
