### PR TITLE
Hide powershell window

### PR DESCRIPTION
**Pull request by gpotter2**
Trial of fixing https://github.com/secdev/scapy/issues/1387

### CODE REVIEW

**Comment by p-l-** [comment]
@gpotter2 is this one ready for merge?

**Comment by gpotter2** [comment]
I would like to wait for the fix to be confirmed, unsure about it

**Comment by p-l-** [comment]
@gpotter2 works for me.

**Comment by gpotter2** [comment]
Still happens when launched from the IDLE... Will look for a fix

**Comment by gpotter2** [comment]
Yep, the latest version does not show it anymore
image

@p-l- mergeable

**Comment by p-l-** [comment]
Thanks @gpotter2!

**Pull request merged**
