### PR TITLE
VXLAN improvements

### PR DESCRIPTION
**Pull request by robin-jarry**
VXLAN now has an official RFC: https://tools.ietf.org/html/rfc7348

* Move VXLAN to `scapy.layers` so that it is loaded automatically.
* Add support for Group Policy Extension (https://tools.ietf.org/html/draft-smith-vxlan-group-policy-00)

### CODE REVIEW

**Comment by robin-jarry** [comment]
There is a problem with sourceforge:

```
$ wget http://downloads.sourceforge.net/project/pylibpcap/pylibpcap/0.6.4/pylibpcap-0.6.4.tar.gz
--2016-08-01 16:29:59--  http://downloads.sourceforge.net/project/pylibpcap/pylibpcap/0.6.4/pylibpcap-0.6.4.tar.gz
Resolving downloads.sourceforge.net (downloads.sourceforge.net)... 216.34.181.59
Connecting to downloads.sourceforge.net (downloads.sourceforge.net)|216.34.181.59|:80... connected.
HTTP request sent, awaiting response... 504 Gateway Time-out
2016-08-01 16:30:05 ERROR 504: Gateway Time-out.
```

**Comment by guedou** [comment]
Why do you need to move vxlan from contrib/ to layers/ ?

Usually, we prefer storing _non regular_ protocols in contrib/ unless there is a real need.

Travis on OS X is far from being reliable. We need to manually restart some tests from time to time.

**Comment by robin-jarry** [comment]
With the emergence of Openstack and cloud management systems, VXLAN is now more and more common. Also, there is an official RFC (non-draft).

I feel that VXLAN is as *regular* than some other protocols that are in `scapy.layers` (`llmnr`, `skinny`, `clns`, etc.)

Does this cause a problem as long as the layer works? I think that the more traffic scapy can parse out-of-the-box, the better.

**Comment by p-l-** [comment]
I'm OK with VXLAN moved to `layers`, (I miss the "approve" button we have on Bitbucket) but I'll let @guedou decide ;-).

**Comment by guedou** [comment]
I would prefer to keep VXLAN in `contrib/`, yet I won't strongly fight for it. Moreover, it seems that it is one vote against two, so I already lost =)

The only real problem that I can think of is that `load_contrib("vxlan")` will fail, which is unfortunate. Could you patch load_contrib() so as to fallback to loading from `layers/` if loading from `contrib/` fails ?

**Comment by robin-jarry** [comment]
Hi @guedou ,

I patched `load_contrib()` so that it falls back to loading in `scapy.layers`. Please tell me what do you think.

**Comment by robin-jarry** [comment]
Thanks @guedou !

**Comment by p-l-** [comment]
Nice work @robin-jarry, thanks @guedou!

**Pull request merged**
