### PR TITLE
Introduce 'long_test' keyword in UTscapy

### PR DESCRIPTION
**Pull request by polybassa**
This PR does two things.

First: It enforces that every test with an execution time longer than 10s need to be marked with the keyword long_test.
Second: Tests with the keyword long_test are only executed with a probability of 10% to save CI credits

### CODE REVIEW

**Comment by gpotter2** [comment]
It's a pretty good idea to add a timeout to tests, that'll help a lot.

However, I'd say either 10sec is too low, either we have some more tests to mark, either we need to add this tag in other places.
Some tests (e.g. ICMP) are network dependent and use `retry_test` (to retry until they work).

**Comment by polybassa** [comment]
I thought about that as well. I suggest to mark all tests which require more than 10 seconds with that keyword. This helps to identify tests which might need a refactoring and ensures that no new tests with long runtimes come in. 
I would say, for most tests it doesn't harm if they are only executed once a while. If you run a local unit test on your system, by default all tests will get executed. 
--

**Comment by polybassa** [comment]
To summarize my idea: If a test can't finish in less than 10s, it doesn't deserve to be executed every time.

**Comment by polybassa** [comment]
The downside of this changes might be a instability in codecov. But still, I would prefer to execute some tests once a while instead of disabling them. This gives us at least a feedback in a reasonable time, if some commit broke one of the tests marked as 'long_test'.

**Comment by gpotter2** [comment]
I think it would make more sense if we just had a flag to disable long tests, and we would enable it on all runs but one (for instance, the ubuntu 3.9 one). I'm not a huge fan of the random factor

**Comment by polybassa** [comment]
No problem. I can change that. Do you think the enforcement of the "long_test" keyword is a beneficial addition?

**Comment by gpotter2** [comment]
I'm unsure, what do you think @p-l- @guedou ?

**Comment by p-l-** [comment]
I'm not sure. Both have advantages. With random, you get more chance to find corner-case bugs. Without, you get stable, predictable CI. Both have their benefits and drawbacks. (I understand that does not help you chose, sorry about that!)

**Comment by polybassa** [comment]
Closed because of inactivity

**Comment by polybassa** [comment]
and its useless ;-D

**Pull request closed without merging**
