### PR TITLE
bluetooth: Add more HCI event packets

### PR DESCRIPTION
**Pull request by antoniovazquezblanco**
**Checklist:**

-   [x] If you are new to Scapy: I have checked [CONTRIBUTING.md](https://github.com/secdev/scapy/blob/master/CONTRIBUTING.md) (esp. section submitting-pull-requests)
-   [x] I squashed commits belonging together
-   [x] I added unit tests or explained why they are not relevant
-   [x] I executed the regression tests (using `cd test && ./run_tests` or `tox`)
-   [x] If the PR is still not finished, please create a [Draft Pull Request](https://github.blog/2019-02-14-introducing-draft-pull-requests/)

Partially rework HCI events and add new packet definitions. I did not have captures with `Inquiry Result` and `Inquiry Result with RSSI` packets...

I've added many tests for existing packets and fixed various packet definitions...

### CODE REVIEW

**Comment by antoniovazquezblanco** [comment]
Sorry but I am unsure of what is happening...

If I run `test/run_tests -t test/scapy/layers/bluetooth.uts` my tests pass but if I simply run them all then bluetooth tests fail...

What is going on? 🤣

**Comment by gpotter2** [comment]
Try with `conf.debug_dissector=True`

**Comment by antoniovazquezblanco** [comment]
I've removed the conflicting packet. I did not have a lot of time to debug the issue. I will send a PR whenever I get the problem sorted out.

For the time being let's keep it rolling with the remaining changes.

Thanks!

**Review by gpotter2 — DISMISSED** [review]
Sorry for the delay.

**Comment by gpotter2** [comment]
Apparently the reason is that you missed the section 8 about Extended Inquiry Responses. Fixed.

**Review by gpotter2 — APPROVED** [review]

**Comment by antoniovazquezblanco** [comment]
Thank you!

**Pull request merged**
