### PR TITLE
Refactoring imports.uts to remove multiprocessing library

### PR DESCRIPTION
**Pull request by polybassa**
Still experimenting with imports.uts

### CODE REVIEW

**Comment by polybassa** [comment]
@gpotter2 This is an alternative implementation of imports.uts. Could you please review this?

**Review by gpotter2 — COMMENTED** [review]
I really doubt that this is going to improve stability

**Comment by polybassa** [comment]
Why do you have doubts?

The previous implementation fails reliable on all current CI-runs: 
- https://github.com/secdev/scapy/runs/5019299638?check_suite_focus=true
- https://github.com/secdev/scapy/actions/runs/1777586068
- https://github.com/secdev/scapy/actions/runs/1777587789
- https://github.com/secdev/scapy/actions/runs/1777590368
- https://github.com/secdev/scapy/actions/runs/1777599464

This implementation passes all CI tests.

**Comment by polybassa** [comment]
This implementation just removes the process pool but doesn't change much on the intended functionality. Every layer is still imported in an individual sub-process. I have the suspicion that the multiprocessing library caused the error somehow. Sadly, it doesn't fail on my system. So the intention of this PR is to remove complexity for this unit test.

**Comment by polybassa** [comment]
@gpotter2 #3522 is a quick proof to show that the current imports.uts is buggy on the CI machines. I have the suspicion that the errors are caused by multiprocessing.pool

**Review by gpotter2 — APPROVED** [review]
Thanks a lot for looking into this !

**Pull request merged**
