### PR TITLE
Fix #4472: Add ability to parse multiple DoIP packets in one TCP pkt

### LINKED ISSUE #4472: Extra DoIP layers are discarded
### Brief description

Sometimes, an Ethernet Frame can contain multiple DoIP layers. When that occurs, the second DoIP layer and everything else after it are completely discarded during the dissection of the Frame.

### Scapy version

2.6.0rc1

### Python version

3.12

### Operating system

Ubuntu 24.04 LTS (Linux 6.8.0-38-generic x86_64)

### Additional environment information

_No response_

### How to reproduce

Here is a test script to show the issue:
```python
from scapy.main import load_contrib
from scapy.utils import PcapReader

if __name__ == '__main__':
    load_contrib("automotive.doip")
    with PcapReader("multiple_doip_layers.pcap") as pcap_reader:
        for packet in pcap_reader:
            packet.show()
```

As can be seen in the Wireshark screenshots, the first Frame contains:
- Alive check response
- Diagnostic message
Wireshark Frame 1

When we run the script, we can see that scapy discards the Diagnostic message (second DoIP layer)  and only shows the Alive check response (first DoIP layer):
image

### Actual result

_No response_

### Expected result

I expect to see the second DoIP layer also be dissected and shown accordingly.

### Related resources

Here is a sample pcap file:
[multiple_doip_layers.zip](https://github.com/user-attachments/files/16381177/multiple_doip_layers.zip)

### PR DESCRIPTION
**Pull request by polybassa**

### CODE REVIEW

**Comment by gpotter2** [comment]
Just to be sure, you aren't happy with a StreamSocket (or TCPSession) splitting the DoIP ?

**Comment by polybassa** [comment]
How can I tell the TCPSession to split the stream into multiple DoIP packets?

**Comment by gpotter2** [comment]
You just have to make the DoIP class implement an `extract_payload` (or something similar) to return `Padding` for additional payloads.

**Comment by polybassa** [comment]
Sorry, I don't fully understand. I couldn't find any example of `extract_payload` in Scapy.

in Packet there is this:
```
    def dissect(self, s):
        # type: (bytes) -> None
        s = self.pre_dissect(s)

        s = self.do_dissect(s)

        s = self.post_dissect(s)

        payl, pad = self.extract_padding(s)
        self.do_dissect_payload(payl)
        if pad and conf.padding:
            self.add_payload(conf.padding_layer(pad))
            
```
            
and in DoIP, i've implemented this:

```
    def extract_padding(self, s):
        # type: (bytes) -> Tuple[bytes, Optional[bytes]]
        if self.payload_type == 0x8001:
            return s[:self.payload_length - 4], None
        else:
            return b"", None
```

Currently, I don't return any padding. However, if I would return a padding, I would need to change the `conf.padding_layer` setting in order to treat the remaining bytes as DoIP, again. Is that correct. 

But changing the global padding_layer doesn't seem right to me. 

Can you give me a hint?

**Comment by gpotter2** [comment]
Sorry I meant `extract_padding`. If a DoIP packet has padding, this padding will be considered to be another DoIP by TCPSession. At least that's how it's supposed to work.

If you want me to help you could provide a pcap or code sample that has multiple DoIP packets :)

**Comment by polybassa** [comment]
The pcap would be here in this commit, or in #4472 if you want to take a look..
test/pcaps/multiple_doip_layers.pcap.gz

Since I got your hint now, I will try it myself ASAP

**Comment by polybassa** [comment]
```
    def extract_padding(self, s):
        # type: (bytes) -> Tuple[bytes, Optional[bytes]]
        if self.payload_type == 0x8001:
            return s[:self.payload_length - 4], s[self.payload_length - 4:]
        else:
            return b"", None
            ```
            I guess this would fix it

**Comment by polybassa** [comment]
actually.. not ;-D

**Comment by gpotter2** [comment]
I think I don't get it. Comparing what Scapy shows and what Wireshark shows on the pcap you mentionned for this PR shows the exact same thing. What exactly was expected? What part of that pcap is a separate DoIP payload?

**Comment by polybassa** [comment]
There is this screenshot in the issue.

It shows two DoIP packets after each other:

https://private-user-images.githubusercontent.com/7274337/352217370-ed48fdb1-f3ba-4ac7-9498-3cfcd11cfe01.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1NzE4ODYsIm5iZiI6MTcyNTU3MTU4NiwicGF0aCI6Ii83Mjc0MzM3LzM1MjIxNzM3MC1lZDQ4ZmRiMS1mM2JhLTRhYzctOTQ5OC0zY2ZjZDExY2ZlMDEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDVUMjEyNjI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODBiMTQ2ZTVjYzM5M2EzNTIxMTQ4YTQ4NDJhYWE0NzhjOWFhNDUyMmZiZDcyODRkZGYyNWQzYTFjZjNmMzlkNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.uwnxyYRaMtl7UCbQA3G9_6gi7BuGf-eYEiUft4GmKCQ

However, I could only dissect the first one with TCPSession

--
Mit freundlichen Grüßen

Dr. Nils Weiß

dissecto GmbH
Franz-Mayer-Str. 1
93053 Regensburg
________________________________

**Comment by gpotter2** [comment]
Okay you're right there's a bug somewhere. Thanks for the time

**Comment by polybassa** [comment]
Thank you for the fix.

**Comment by polybassa** [comment]
@gpotter2 Should we merge this?

**Comment by gpotter2** [comment]
Sure !

**Pull request merged**
