### PR TITLE
Native Mac OS X and *BSD support

### PR DESCRIPTION
**Pull request by guedou**
This PR provides native support for Mac OS X and and *BSD. No external Python
modules are required to send and receive packets. It was tested on Debian, OS X 10.9.5, FreeBSD 10.2, NetBSD 7.0 and OpenBSD 5.5

Issue #104 provides some examples, as  well as several mandatory items that were
implemented and tested.

@p-l- I chose to keep all commits for reference, as some changes are not
obvious. Can you squash them when the PR is OK ? Thanks.

### CODE REVIEW

**Comment by guedou** [comment]
@p-l the PR is finally good to be review. When you are OK with it, could you squash them all commits into a single one named "Native BPF support". We might face a merging issue after accepting PR #258.

**Comment by guedou** [comment]
@p-l- hopefully the travis run will go fine. The patch is good to be "squashed and merged"

**Comment by p-l-** [comment]
I'm not sure what is wrong here, but [this Travis CI  test](https://travis-ci.org/secdev/scapy/jobs/175991916) should not pass, should it?

**Comment by guedou** [comment]
What's wrong with this test ?

**Comment by p-l-** [comment]
```
$ bash .travis/test.sh
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "scapy/all.py", line 16, in <module>
    from scapy.arch import *
  File "scapy/arch/__init__.py", line 81, in <module>
    from scapy.arch.bpf import *
  File "scapy/arch/bpf.py", line 9, in <module>
    from scapy.arch.bsd import LOOPBACK_NAME
ImportError: No module named bsd
```

**Comment by guedou** [comment]
Thanks. I accessed the Travis test with a mobile phone and could not see the log. I pushed a patch that hopefully will fix the issue. I wonder why Travis  displayed the test as OK.

**Comment by guedou** [comment]
@p-l- I have a lot of errors due to modification to consts.py =/

**Comment by p-l-** [comment]
Another fail:
```
The command "bash .travis/test.sh" exited with 0.
Done. Your build exited with 0.
/Users/travis/build.sh: line 148: shell_session_update: command not found
```

**Comment by guedou** [comment]
I don't understand this error message. It might be Travis related, as  I
tested the code, and it worked fine on OS X, FreeBSD, NetBSD and OpenBSD.

Do you know shy it fails ?

**Comment by guedou** [comment]
@p-l- it seems that the OS X tests stopped working with PR #342, see https://travis-ci.org/secdev/scapy/builds/174817909 and https://travis-ci.org/secdev/scapy/jobs/174817912

**Pull request merged**
