### PR TITLE
Dot15d4 & Zigbee: Update, fixes & tests

### PR DESCRIPTION
**Pull request by gpotter2**
- Chose between Zigbee and SixLowPan using config
- Better FCS support in Dot15d4
- Move Zigbee support to a different layer
- Adds some more Dot15D4 / Zigbee tests
- Minor Zigbee fixes (some from the scapy-com PRs)

fixes https://github.com/secdev/scapy/issues/1455

### CODE REVIEW

**Comment by gpotter2** [comment]
Ok this won't work

**Comment by gpotter2** [comment]
@p-l- Do you have any idea of if we should also import
https://github.com/BastilleResearch/scapy-radio/blob/master/scapy/scapy/modules/gnuradio.py
inside scapy ?

**Comment by gpotter2** [comment]
@p-l- Ready to be reviewed
FTR, fixes:
- https://github.com/riverloopsec/killerbee/pull/127
- https://github.com/secdev/scapy/pull/1179

**Comment by ZeroChaos-** [comment]
@gpotter2 yes, getting the gnuradio support into scapy upstream would be amazing

**Comment by gpotter2** [comment]
@p-l- Good for you ?

**Comment by ZeroChaos-** [comment]
might I beg for a tag with this merged in? :-D

**Comment by ZeroChaos-** [comment]
so that's a no on begging for 2.4.1? :-)

I'd really like to have the zigbee stuff in a release on my livecd for DEF CON.

**Comment by gpotter2** [comment]
Well, I’d like to get IPython 7.0 integration (+ a few other tricks) before we release 2.4.1. They should release it quite soon

**Pull request merged**
