### PR TITLE
Fix PR 947: Delay Tolerant Networking Protocols

### PR DESCRIPTION
**Pull request by gpotter2**
- Fixes #947:
  - adding unit tests
  - reworking modules
  - fixing inconsistencies

Quite cool protocol btw https://www.nasa.gov/content/dtn

### CODE REVIEW

**Comment by p-l-** [comment]
Can you rebase against master and remove the commit "Merge commit 'refs/pull/947/head' of https://github.com/secdev/scapy" which messes the history?

**Comment by gpotter2** [comment]
@p-l- Rebased

**Comment by p-l-** [comment]
Can you now squash the  "Remove duplicated config.py" commit with the one introducing this ("Adding layers for LTP and BP" apparently), and remove the PEP-8 commit since we would not accept it?

**Comment by gpotter2** [comment]
Rebased !

**Comment by p-l-** [comment]
Since this is not a bugfix, I'm removing it from the "Release 2.4" project as we do not want it to be a release blocker.

**Comment by guedou** [comment]
@gpotter2 is this ready to be reviewed?

**Comment by gpotter2** [comment]
Should be

**Comment by guedou** [comment]
@gpotter2 could you rebase and fix the errors that flake8 will triggered ? Otherwise, you can launch `tox -e flake8` locally.

**Comment by guedou** [comment]
@gpotter2 flake8 is not happy =/

**Comment by gpotter2** [comment]
flake8 now passing on my machine

**Comment by guedou** [comment]
Still failing here.

**Comment by gpotter2** [comment]
Fixed

**Pull request merged**
