### PR TITLE
Don’t distribute test directory into site-packages

### PR DESCRIPTION
**Pull request by wimglenn**

### CODE REVIEW

**Comment by gpotter2** [comment]
@guedou @p-l- What do you think?

**Comment by guedou** [comment]
This is a good idea. As of today, `test/` only contains Python scripts. I tried the fix with `python setup.py sdist` and the resulting tarball still contains `test/`. I wonder if this fix is complete.

**Comment by wimglenn** [comment]
@guedou It is OK for the .tar.gz to still have test/ , but when you install it with e.g. `pip install scapy-2.5.0.tar.gz` you should not get a package at `.../lib/python3.11/site-packages/test`. It's the `setup.py` within the sdist which says what files to copy into the site packages dir.

**Comment by guedou** [comment]
Thanks for your answer!

**Review by guedou — APPROVED** [review]

**Pull request merged**
