### PR TITLE
[coverage] main.py tests

### PR DESCRIPTION
**Pull request by gpotter2**
Those are tiny fixes:
- Moved the instanciation of `__buildin__` inside a function
- Added tests for `save_session` and `load_session`

### CODE REVIEW

**Comment by p-l-** [comment]
Can you split that PR?

**Comment by gpotter2** [comment]
Done https://github.com/secdev/scapy/pull/475

**Comment by gpotter2** [comment]
Does it break codecov support ?

**Comment by guedou** [comment]
@gpotter2 Thanks ! Could you rename your PR with "[coverage]" ? It is my own personal project name related to unit tests creation =)

**Pull request merged**
