### PR TITLE
Minor cleanup to stabilize ISOTPSoftSocket unit tests

### PR DESCRIPTION
**Pull request by polybassa**

### CODE REVIEW

**Comment by polybassa** [comment]
@gpotter2 Ready to merge.

**Review by guedou — APPROVED** [review]

**Comment by guedou** [comment]
Can you provide more details? For example, I would like to understand if this PR  stabilize the tests.

**Comment by polybassa** [comment]
Hi, sorry for this short description.

Since the merge of #3318 I discovered some failing tests on CI, caused by non-deterministic `ISOTPSoftSocket` unit test failures. 

Therefor I wanted to provide this PR quickly, to not further interrupt CI pipelines with these bugs.

This PR aims to further cleanup `ISOTPSoftSocket` unit tests through the following changes:

- Replacement of `MockSocket` with `TestSocket` from `interface_mockup.py `
   `TestSocket` tends to be much more reliable because of the use of `ObjectPipes`
- Improvements and bug fixes of `TestSocket`
   `TestSocket` was configured wrong. It's now configured to be a blocking_socket. Also I've added a select method 
   to make use of `select_objects` method from` automaton.py`
- Add a cleanup of open `TestSocket` objects. All created `TestSocket` objects will be tracked in a global list and closed from the cleanup method of `interface_mockup.py`
- @gpotter A left-over `None` return value  of `ObjectPipe`'s select was removed

**Comment by guedou** [comment]
Thanks! LGTM

**Comment by polybassa** [comment]
@gpotter2 Can this PR get merged, please. I require this changes for my other open PRs.

**Review by gpotter2 — APPROVED** [review]

**Comment by polybassa** [comment]
Thanks!

**Pull request merged**
