### PR TITLE
Added some windows links

### PR DESCRIPTION
**Pull request by gpotter2**
Contains new python 2.7links for pyreadline, winpcap and pywin32

But libdnet and pypcap still need to be done as said here: https://github.com/secdev/scapy/pull/307#issuecomment-255363431

### CODE REVIEW

**Comment by gpotter2** [comment]
Oh I'm sorry: I somehow copied another old commit in this one ?! But although I did not changed anything...

**Comment by guedou** [comment]
@gpotter2 this could happen when you merge on a branch, then fork this branch. You can try to clean the history using `git rebase`, or open a new PR.

**Comment by gpotter2** [comment]
Ok cool, I've  managed to delete it

**Comment by p-l-** [comment]
Thanks!

**Pull request merged**
