### PR TITLE
Document Python 3.8 support

### PR DESCRIPTION
**Pull request by johnthagen**
Implemented in #2285 but missing in documentation.

### CODE REVIEW

**Comment by guedou** [comment]
Thanks for this PR!

**Comment by c-bg** [comment]
small question, is there reason for why the python 3.8 badge is missing in the project readme? :)

**Comment by johnthagen** [comment]
There badge is based on the latest version published to PyPI, and there hasn't been a release for almost a year.

**Comment by c-bg** [comment]
ah ok I see! thanks much for your helpful reply :)

**Pull request merged**
