### PR TITLE
Add Python 3.10 classifier

### PR DESCRIPTION
**Pull request by tonybaloney**
Since the package is being test (and works on ) 3.10, it should also have this classifier.

### CODE REVIEW

**Review by gpotter2 — APPROVED** [review]
Thanks !

**Comment by tonybaloney** [comment]
@gpotter2 i saw 3.11 in the release notes coming up, is a PR to test 3.11b4 welcome?

**Comment by gpotter2** [comment]
Hm, we'll probably wait for the final release. I should probably remove it from the patch notes

**Comment by gpotter2** [comment]
To give context, we do *try* to support betas/unreleased versions because our release schedule is so slow Python 3.11 will probably be out by the time we make another release, but we don't actually give it proper support before the final release.

We use quite a bunch of niche features and it has happened already that we did patches to support the betas, that ended up being unnecessary in the full release.

**Pull request merged**
