### PR TITLE
Add PyPI badges

### PR DESCRIPTION
**Pull request by johnthagen**
Adds latest version on PyPI and supported Python versions badges as listed in the latest published `setup.py`. The badges also have links to the PyPI page.

Note that the Python version badge will properly show "2.7" once a new release is pushed from master that contains the Python version information in `setup.py`.

### CODE REVIEW

**Comment by p-l-** [comment]
So maybe we can wait that before merging this PR?

**Comment by johnthagen** [comment]
@p-l- Yep, sounds fine to me.

**Comment by guedou** [comment]
@johnthagen could you also link https://pypi.python.org/pypi/scapy/ for the "PyPi version" badge ? Thanks.

**Comment by johnthagen** [comment]
@guedou Fixed, sorry about that. Must have been a copy-paste error.

**Pull request merged**
