### PR TITLE
[bluetooth.py] ATT and SMP tiny additions

### PR DESCRIPTION
**Pull request by Matheus-Garbelini**
- Added SM_Public_Key and SM_DHKey_Check layers for scapy to be able to dissect Secure Connection packets from the new BLE 4.2 Standard;
- Added _att_error_codes structure containing the ATT error codes for layer `ATT_Error_Response`

This PR is relatively very simple, so I'm not sure if a new tests needs to be added for this PR.
Let me know your feedback.

### CODE REVIEW

**Comment by Matheus-Garbelini** [comment]
failed F90D5955 conversations()

why this test is failing just for python 3.7? Is this normal?

**Comment by gpotter2** [comment]
It's a random networking failure. I've restarted the tests

**Comment by guedou** [comment]
@Matheus-Garbelini could you add small uni tests to `test/bluetooth.uts` ? Thanks!

**Comment by guedou** [comment]
@Matheus-Garbelini I just pushed unit tests to your branch.

**Pull request merged**
