### PR TITLE
tests: replace the LDAP OSS-Fuzz testcase

### PR DESCRIPTION
**Pull request by evverx**
The original testcase triggers a separate issue on 32-bit machines: https://github.com/secdev/scapy/issues/4527 and it should probably be tested separately. The new testcase triggers the issue fixed in 1935723c18b45b0a735d9e44ca80a0d4976a5bb9 only:
```sh
>>> assert l[0][LDAP].summary() == "LDAP"
Traceback (most recent call last):
  File "<input>", line 2, in <module>
  File "scapy/scapy/packet.py", line 1692, in summary
    return self._do_summary()[1]
           ^^^^^^^^^^^^^^^^^^
  File "scapy/scapy/packet.py", line 1669, in _do_summary
    ret = self.mysummary()
          ^^^^^^^^^^^^^^^^
  File "scapy/scapy/layers/ldap.py", line 736, in mysummary
    self.messageID.val,
    ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'val'
```

It was tested in https://download.copr.fedorainfracloud.org/results/packit/evverx-scapy-2/fedora-40-i386/07994883-scapy/builder-live.log.gz

### CODE REVIEW

**Comment by evverx** [comment]
(Also I was going to switch `manual_trigger` to `false` to run the tests on all those platforms on PRs automatically but then I remembered that it was discussed in https://github.com/secdev/scapy/pull/4355#issuecomment-2067803686 and it was decided not to do it at the time. Personally I think it should be OK to run the tests automatically because it's hard to tell how PRs can affect those architectures/packages. If the concern is that it consumes the resources I can ask the Packit folks if it's OK by analogy with, say, https://github.com/packit/packit/discussions/2371#discussioncomment-10398851. `scapy` is used extensively to test and find all sorts of issues in `systemd-resolved`, `systemd-networkd`, `avahi`, `NetworkManager` and things like that so I'm sure it should be convincing enough in terms of why testing scapy is a good idea. Though I don't think it should come up because it doesn't consume a lot resources anyway. I'd personally go as far as to run it all on commits as well to produce packages that folks that can't pull stuff from PyPi for whatever reason can use to test the master branch on RPM-based systems)

**Comment by guedou** [comment]
@evverx If that's OK for the packit folks, we could test Scapy on other architectures too. That will be super cool.

**Comment by gpotter2** [comment]
@guedou To clarify, and as pointed out by evverx, we can already do that on all platforms that packit support. (via /packit build)

However my point was that packit is designed to help fedora have a more streamlined upstream/downstream integration, not to be a freely available CI. If I understand it well, we're already kinda "abusing" the way it works to use it as a CI (https://github.com/evverx/scapy/pull/1#issuecomment-1420289145). I didn't want to have it triggered on each commit because I felt that would be an abuse, so we currently only trigger it manually once in a while.

**Comment by gpotter2** [comment]
Thanks for the PR anyways!

**Review by gpotter2 — APPROVED** [review]

**Comment by evverx** [comment]
> we're already kinda "abusing" the way it works to use it as a CI

`systemd`, `avahi`, `dbus-broker` and some other projects do that too to run their tests on big-endian and 32-bit machines. `systemd` doesn't trigger Packit on commits though (because there are already a lot of PRs and force-pushes there triggering a lot of Packit jobs testing a gazillion different components).

> packit is designed to help fedora have a more streamlined upstream/downstream integration, not to be a freely available CI

Fedora ships scapy (https://src.fedoraproject.org/rpms/scapy) and all the tests running upstream on Fedora machines help to catch things as soon as possible. From a Fedora perspective It's much better than waiting for releases and then trying to figure out why packages fail to build.

> I'm not against it, but out of respect that's probably something we should ask permission for.

Got it. I'll talk to the Packit folks and open a PR once it's confirmed that it's OK to run it on PRs.

**Comment by evverx** [comment]
I opened https://github.com/packit/packit/discussions/2407

**Pull request merged**
