### PR TITLE
Add TLS 1.3 HelloRetryRequest

### PR DESCRIPTION
**Pull request by romain-perez**
This pull request adds : 
- Support for HelloRetryRequest message in automaton (client and server)
- Tests from RFC8448 for HelloRetryRequest

**Edits by gpotter2**:
- Drops support for cryptography < 2.0.0 (2017)
- fix PR according to review
- rebase

### CODE REVIEW

**Comment by p-l-** [comment]
Hi,

Thanks for this PR. You have two failed tests. Could you have a look?
- https://travis-ci.com/secdev/scapy/jobs/238211535
- https://travis-ci.com/secdev/scapy/jobs/238211537

For the second one, you may need to add `~ crypto_advanced` on some of your tests.

**Comment by romain-perez** [comment]
The first failed test is a bit unclear to me because it failed when generating the doc and I didn't change this part. I am still looking at it. 

For the second one, I didn't used ~ crypto_advanced flag on purpose because I thought it was necessary only for key exchange with curve x25519, or the curve used for this test is secp256r1. But I think this flag is also necessary because of the symmetric cipher, so I will add it.

**Comment by romain-perez** [comment]
Hi,

I have been able to reproduce the first failed test and I found a way to fix it but I am not sure if it's the right way to fix it or not. 
 
The error is caused by a missing module 'cryptography' when importing module 'all' from module 'scapy.layers.tls'. So, if I add the module 'cryptography' in deps for [testenv:docs] defined in the tox.ini as follow, the test is not failing anymore :

```
[testenv:docs]
skip_install = true
changedir = doc/scapy
deps = sphinx
       sphinx_rtd_theme
       cryptography
commands =
  sphinx-build -q -W -b html . _build/html
```
But I can't really see why it was failing only in this pull request and not in my previous one. Could it be possible that the module 'scapy.layers.tls' was not imported previously ? Do you have any ideas on this ?

**Comment by gpotter2** [comment]
TLS files are using a safe check to be able to be imported even without cryptography:

https://github.com/secdev/scapy/blob/99d5142695962dbe5b21b22e7edd0dd5aa3044c0/scapy/layers/tls/crypto/cipher_stream.py#L15

**Comment by ria4** [comment]
Hi,

Regarding `crypto_valid`, I introduced it in order for Scapy not to have a `cryptography` dependency. If this condition was not met, the TLS 1.3 module would still be able to parse/encode packets -even though you wouldn't be able to decrypt/verify protected contents.

I believe it's still the intention of the maintainers not to depend upon `cryptography`, so you should keep this validation.

**Comment by gpotter2** [comment]
@guedou @p-l- ready for review

**Comment by gpotter2** [comment]
Let's move on. This has staled for too long already

**Comment by gpotter2** [comment]
@romain-perez Sorry for the delay, feel free to create PRs out of your other branches.

**Pull request merged**
