### PR TITLE
Fix automaton tests

### LINKED ISSUE #31: Automaton (tests) broken
For some reason, even basic automaton test fail. At least:
  - under Linux, when run as simple user.
  - under OpenBSD, even when run as root (reported by @danieljakots, see #29).

### PR DESCRIPTION
**Pull request by p-l-**
Use pseudo socket generators to fix automaton tests without the need of specific privileges.

Should fix #31.

### CODE REVIEW

**Comment by p-l-** [comment]
@danieljakots (or someone else) can you confirm automaton tests pass under OpenBSD with this patch?

**Comment by guedou** [comment]
Tested with vagrant and the following box: https://atlas.hashicorp.com/kaorimatz/boxes/openbsd-5.8-amd64. I had to deactivate the wifi tests.

After:
```shell
# bash run_tests -q -F -t regression.uts -K netaccess -K wifi
[..]
PASSED=759 FAILED=0
Regression tests for Scapy
```

**Comment by danieljakots** [comment]
Now I don't have to ^C the test but:
PASSED=760 FAILED=7
Exception Exception: 'pcapObject must be initialized via open_live(), open_offline(), or open_dead() methods' in <bound method _PcapWrapper_libpcap.__del__ of <pcap.pcapObject; proxy of <Swig Object of type 'pcapObject *' at 0x7a38bf50> >> ignored

**Comment by p-l-** [comment]
@guedou this might be because of a missing pycrypto module, since the only wifi test seem to be related to WEP.

@danieljakots can you post the full output somewhere so that I can have a look?

**Comment by danieljakots** [comment]
Ok I did the tests again with root (sorry I forgot to do it with root because I try to do as few things with root as I can) and this time:
PASSED=767 FAILED=0
If you still want to look at it https://chown.me/iota/scapy-test/

**Comment by p-l-** [comment]
Thanks a lot @danieljakots; for me, good do merge @guedou (btw I don't see an "approve pull request" button here - at last something better in bitbucket than github? ;-) ).

**Comment by guedou** [comment]
@p-l- that feature was quite nice on BB =)

**Pull request merged**
