### PR TITLE
Daimler AG kindly asked for removal of these files, since they violat…

### PR DESCRIPTION
**Pull request by polybassa**
…e there Information Disclosure policy

Could you please merge this PR as soon as possible.

### CODE REVIEW

**Comment by gpotter2** [comment]
This breaks all tests.
Please fix them and we'll merge it ASAP.

Please note that the files will remain in the git history

**Comment by p-l-** [comment]
I don't understand why one Appveyor test fails, apparently for an unrelated reason. @gpotter2 any idea?

**Comment by gpotter2** [comment]
It looks like that's because enum34 (a cryptography dependency) was updated a few hours ago. You can ignore that safely

**Comment by polybassa** [comment]
Thanks for your help

**Comment by p-l-** [comment]
py27 and pypy tests all fail on Travis. Is that the same problem? Can we merge it safely?

**Comment by gpotter2** [comment]
Everything python2 is failing because of that issue.

**Pull request merged**
