### PR TITLE
Allow wildcards in load_contrib

### PR DESCRIPTION
**Pull request by gpotter2**

### CODE REVIEW

**Comment by guedou** [comment]
Please add some tests.

**Comment by p-l-** [comment]
I'm OK for listing the contribs with wildcards, not to **load** them as the PR title says...

**Comment by gpotter2** [comment]
@p-l- Hi ! Could you elaborate please ?
This is used in rare cases, especially
`load_contrib("ppi*")`

If the usages are two rare, we may forget it.

**Comment by p-l-** [comment]
@gpotter2 sorry, I was not clear... I understand you may want to **list** contrib modules matching a specific wildcard (maybe when you are looking for a module), but I think one should not be able to **load** modules based on a wildcard.

If one wants to load three modules, I think it's not too hard to write three statements... On the other hand, the `ppi` case is interesting. Maybe it should be one contrib in a dedicated directory (like `tls` in the `layers` directory).

**Comment by gpotter2** [comment]
I get it :)

About the `ppi` case, I have a question: what on earth is the `gsm_um` module. It needs a full rewrite, uses disgusting lists... and says in its title « PPI » . Then why would we have a ppi module ?

Any thoughts ?

**Pull request closed without merging**
