### PR TITLE
Add UDPClientPipe and UDPServerPipe to scapypipes

### PR DESCRIPTION
**Pull request by Lastpixl**
Hi!

This PR adds new classes to scapypipes, that are similar to TCPListenPipe and TCPConnectPipe.

### CODE REVIEW

**Comment by Lastpixl** [comment]
Sure! Test added [here](https://github.com/Lastpixl/scapy/commit/118987f37072ffc1f794d20623b8d15e71483a54).

**Comment by guedou** [comment]
Could you rebase against master? That will solve one failing test. The other one seems related to *BSD.

**Comment by gpotter2** [comment]
A lot of code should be shared with the TCP* classes

**Comment by p-l-** [comment]
I agree with @gpotter2: you probably want to avoid code duplication.

**Review by guedou — APPROVED** [review]
This looks good to me!

**Review by p-l- — APPROVED** [review]

**Comment by gpotter2** [comment]
Tests did not pass for this, thus the broken tag.

**Comment by gpotter2** [comment]
See https://github.com/secdev/scapy/pull/2810

**Comment by p-l-** [comment]
@gpotter2 my bad, sorry...

**Pull request merged**
