### PR TITLE
Set sniff snaplen to MTU

### PR DESCRIPTION
**Pull request by gelim**
PR for closing #896

### CODE REVIEW

**Comment by gpotter2** [comment]
Hi, the test seems broken.
We could use this PR to fix it (as it's the TCPDUMP filter test).
Could you set:
index e732e932..8cbccff6 100644
```
--- a/test/regression.uts
+++ b/test/regression.uts
@@ -1024,7 +1024,7 @@ send_and_sniff(IP(dst="secdev.org")/ICMP(), flt="icmp")
 send_and_sniff(Ether()/IP(dst="secdev.org")/ICMP())

 a = L2ListenTcpdump()
-icmp_r = IP(b'E\x00\x00\x1c\x00\x01\x00\x00@\x01p\xc0\x7f\x00\x00\x01\xd9\x19\xb2\x05\x08\x00\xf7\xff\x00\x00\x00\x00')+icmp_r = IP(dst="secdev.org")/ICMP()
 send_and_sniff(icmp_r, timeout=10, opened_socket=a)
 a.close()
```

**Comment by p-l-** [comment]
@gelim your move!

**Comment by gelim** [comment]
Actually I'm a bit puzzled with the failed test and its backtrace:
``` python
Exception in thread Thread-26:
Traceback (most recent call last):
  File "C:\Python27-x64\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27-x64\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "<input>", line 9, in run_function
  File "<input>", line 25, in _send_or_sniff
AssertionError
Traceback (most recent call last):
  File "<input>", line 2, in <module>
  File "<input>", line 18, in send_and_sniff
AssertionError
```

as I can see it's running on a Windows box (`C:\Python27-x64`) and my change concerns `scapy/arch/linux.py`. I ran the test without my patch, and I got `FAILED=0`. I would like to understand what I'm really fixing before blindly pushing something...

**Comment by p-l-** [comment]
@gelim actually, you may want to fix the test as @gpotter2 explains it.

**Comment by gelim** [comment]
I got that. The thing is I don't see how his fix is related to the test failing, hence my comment.

**Comment by gpotter2** [comment]
Fine, i'll push it myself

**Comment by p-l-** [comment]
@gelim can you rebase against current master? Since @gpotter2 has updated the failing test, it should work now.

**Pull request merged**
