### PR TITLE
Add TLS 1.3 support

### PR DESCRIPTION
**Pull request by romain-perez**
**Edits by gpotter2:** This PR has been split !

- [x] https://github.com/secdev/scapy/pull/2146 - Basic support
- [x] https://github.com/secdev/scapy/pull/2244 - Automatons
- [x] https://github.com/secdev/scapy/pull/2260 - RetryRequests
- [x] https://github.com/secdev/scapy/pull/2585 Client Auth
- [x] https://github.com/secdev/scapy/pull/2586 Client Key update
- [x] https://github.com/secdev/scapy/pull/2586 External PSK
- [x] https://github.com/secdev/scapy/pull/2625 Session resumption
- [x] https://github.com/secdev/scapy/pull/2633 Curve x448 support
- [ ] Early data capatibilies: XXX unfinished. See [this rebase](https://github.com/gpotter2/scapy/tree/romain-perez-add-tls13-early-data) of romain-perez's work

**Original PR:**

This PR adds support of TLS 1.3 :
- Add new TLS 1.3 messages and extensions from RFC8446
- Update the key schedule
- Support of 0-RTT
- New test vectors based from RFC8448
- Basic automaton for TLS 1.3 client and server

TODO:
- fix error management in automaton
- middleblox compatibility

fixes https://github.com/secdev/scapy/issues/1668

### CODE REVIEW

**Comment by guedou** [comment]
Thanks a lot for this work!

There are some errors in the CI:
- code style, see https://travis-ci.com/secdev/scapy/jobs/213497139#L975
- typos, see https://travis-ci.com/secdev/scapy/jobs/213497139#L1088

You can run these tests locally with `tox -e flake8,spell`

Other error seems related to `tls13.uts`. Some changes are useless such as `def post_dissection(self, r):` could you revert them?

This PR is quite dense. A good alternative that will simplify the review process is to split it into smaller PR, for example HKDF + examples, 0-RTT + examples, ... That way we could have a working implementation when we release v2.4.3 at the end of the month.

**Comment by romain-perez** [comment]
Thanks for the feedback. 

I will correct the coding style and typos errors that i missed. I will also spit this large PR into smaller PR : a first with only basic TLS 1.3 handshake functionalities and then add each new functionalities individually

**Comment by guedou** [comment]
Awesome! Feel free to ask any question on

**Comment by gpotter2** [comment]
At this point if it's too much work splitting the PR, I'd also be fine to have a massive PR (**if the tests manage to pass**). Thanks an awesome work !

**Comment by romain-perez** [comment]
I just created a new PR ( #2146). Should I close this one ?

**Comment by guedou** [comment]
As you wish. I am fine with keeping this PR open until the other ones are merged.

**Comment by guedou** [comment]
Could you add "fixing https://github.com/secdev/scapy/blob/master/doc/notebooks/tls/notebook4_tls13.ipynb" to you list of TLS1.3 related things to fix? Thanks.

**Comment by gpotter2** [comment]
Hi @romain-perez.

If it helps for the rest of the development, I've done a rough rebase of this PR over:
https://github.com/gpotter2/scapy/tree/rebase_romain_perez
I am not confident with the TLS implementation, therefore this has broken some parts. You'll probably be more effective by doing your own rebase, but if you feel like so you can try fixing this one.

**Comment by guedou** [comment]
@romain-perez any progress on the last part of this PR?

**Comment by romain-perez** [comment]
Sorry for the delay, I couldn't work on this last month. 
I already prepared all the next PR on my forked repository, I just need to do some minor cleaning in order to make it easier to merge. 
I will submit the next one really soon.

**Comment by guedou** [comment]
Thanks !

**Comment by acp6** [comment]
Does it support writing SSL security testing scripts such as testing heartbleed, ccs attack, as scapy-ssl_tls did?

**Comment by gpotter2** [comment]
This PR has now been merged as smaller PRs. See the edited message

**Pull request closed without merging**
