### PR TITLE
Add ICMPv6 Paramater Problem type 3 "First Fragment has incomplete IP…

### PR DESCRIPTION
**Pull request by adventureloop**
…v6 Header Chain"

As defined in section 6 of RFC7112

This is just a checklist to guide you. You can remove it safely.

**Checklist:**

-   [ ] If you are new to Scapy: I have checked <https://github.com/secdev/scapy/blob/master/CONTRIBUTING.md> (esp. section submitting-pull-requests)
-   [ ] I squashed commits belonging together
-   [ ] I added unit tests or explained why they are not relevant
-   [ ] I executed the regression tests for Python2 and Python3 (using `tox` or, `cd test && ./run_tests_py2, cd test && ./run_tests_py3`)

> brief description what this PR will do, e.g. fixes broken dissection of XXX

> if required - short explanation why you fixed something in a way that may look more complicated as it actually is

> if required - outline impacts on other parts of the library

fixes #xxx (add issue number here if appropriate, else remove this line)

### CODE REVIEW

**Comment by gpotter2** [comment]
You have PEP8 failures:

```
scapy/layers/inet6.py:1396:88: E261 at least two spaces before inline comment
scapy/layers/inet6.py:1397:80: E501 line too long (100 > 79 characters)
scapy/layers/inet6.py:1397:101: W291 trailing whitespace
ERROR: InvocationError for command /home/travis/build/secdev/scapy/.tox/flake8/bin/flake8 scapy/ (exited with code 1)
```

**Comment by gpotter2** [comment]
```
scapy/layers/inet6.py:1397:80: E501 line too long (95 > 79 characters)
```
Note you can do `tox -e flake8` to check this locally..

**Comment by adventureloop** [comment]
1397 is shorter than the lines above it. 

Should I restructure the entire block?

**Comment by gpotter2** [comment]
Yeah you can do that, that'd remove the noqas

**Comment by gpotter2** [comment]
Thanks for the PR !

NTS: squashed

**Pull request merged**
