### PR TITLE
Ecu renaming

### PR DESCRIPTION
**Pull request by polybassa**
This PR tries to remove changes from #3054

### CODE REVIEW

**Comment by polybassa** [comment]
Hi, `Ecu` is a utility class with additional classes for several individual functionalities. This leads to all kind of combinations of `Ecu`, for example `EcuSession`, `EcuResponse`, `EcuState`. 
Since `Ecu` is not a layer and doesn't describe a protocol, I don't see a need to not follow PEP 8 (https://www.python.org/dev/peps/pep-0008/#class-names) for this class. 
You are right, that ECU is an abbreviation for Electronic Control Unit or Engine Control Unit, but I would like to have it distinguishable from protocols in Scapy. Additionally, this change makes the code more compliant to PEP 8.

**Comment by polybassa** [comment]
@guedou Can we continue with this PR? This is blocking me from applying further splits of #3054

**Comment by guedou** [comment]
I am not convinced that these changes are needed. I will let @gpotter2 take the final decision.

**Comment by polybassa** [comment]
@gpotter2 Is it possible to get this changes in?

**Comment by gpotter2** [comment]
I am still *highly* unconvinced but it's not that big of a deal, especially considering you more-less own the `automotive/` folder. 
Please try to avoid preventing having to do such changes in the future though: this is an unecessary long commit.

**Pull request merged**
