### PR TITLE
Interface's name isn't necessary to be ended with a digit

### PR DESCRIPTION
**Pull request by lwhsu**
Remove the step to convert to integer as it doesn't affect the result.

### CODE REVIEW

**Comment by guedou** [comment]
Please provide an example of the issue that you are fixing.

**Comment by p-l-** [comment]
Thanks for your report.

Actually, I think your fix is not correct (the function is supposed to mimic `mimics pcap_findalldevs()`'s order). I also think that this function also have another problem. See #1991.

**Comment by lwhsu** [comment]
@p-l- thanks for the correct fix, obviously I didn't understand this function is used in other places. I'm sorry for the wrong patch. BTW, I did run the test https://travis-ci.org/lwhsu/scapy/builds/520729170 and I am not sure why TravisCI reports error here.

**Comment by lwhsu** [comment]
@guedou I'm dealing with this error: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=237305#c0 , I believe the problem is the interface's name here is `epair0a`.

**Comment by guedou** [comment]
Thanks for sharing the link.

**Comment by ngie-eign** [comment]
Yeah, this solution is unfortunately incorrect :/.

**Pull request closed without merging**
