### PR TITLE
Update Automotive-specific documentation. Fixes #3141

### LINKED ISSUE #3141: Outdated Automotive Documentation
Reminder for myself.

Outdated:
https://github.com/secdev/scapy/blob/1aa0d8a849f7b102d18a3f65986e272aec5f518a/doc/scapy/layers/automotive.rst#L75-L85

SOME/IP:
https://github.com/secdev/scapy/blob/1aa0d8a849f7b102d18a3f65986e272aec5f518a/doc/scapy/layers/automotive.rst#L1011-L1030
Mentioned by @WebLabInt via gitter:
```Hi, I m having a problem creating a basic SOME IP service discovery following the example provided https://scapy.readthedocs.io/en/latest/layers/automotive.html?highlight=some%20ip#creating-a-some-ip-sd-message. The SOME IP package is working perfectly, however, the SD packet is not formed correctly thus not recognized as a SD packet by Wireshark and the SOME IP version is not correct. I did a capture with Wireshark reporting those issues http://fuiing.com/share/SD%20prob.png . I will be great if you can support me on this issue, thank you for making Scapy open source, it's really a great tool, have a great day ```

### PR DESCRIPTION
**Pull request by polybassa**
The second issue in #3141 could not be reproduced by myself.

> Mentioned by @WebLabInt via gitter:
> Hi, I m having a problem creating a basic SOME IP service discovery following the example provided https://scapy.readthedocs.io/en/latest/layers/automotive.html?highlight=some%20ip#creating-a-some-ip-sd-message. The SOME IP package is working perfectly, however, the SD packet is not formed correctly thus not recognized as a SD packet by Wireshark and the SOME IP version is not correct. I did a capture with Wireshark reporting those issues http://fuiing.com/share/SD%20prob.png . I will be great if you can support me on this issue, thank you for making Scapy open source, it's really a great tool, have a great day

### CODE REVIEW

**Review by guedou — CHANGES_REQUESTED** [review]
Are these paragraphs were written for Scapy documentation, or are they from an article?

**Comment by polybassa** [comment]
Thanks for your feedback. I will apply these changes

> Are these paragraphs were written for Scapy documentation, or are they from an article?

These paragraphs were not exclusively written for the Scapy documentation, but since I wrote these paragraphs in my thesis in a background section, I found it useful to modify them a bit and also make them available in the Scapy documentation. The intention was, to make the learning curve for automotive networks easier.

**Comment by guedou** [comment]
Could you add a reference to your thesis?

**Comment by polybassa** [comment]
That's a good point. Yes. I will reference it. 

I hope you are fine with these paragraphs in the scapy documentation.

**Comment by guedou** [comment]
I have no problem at all, as long as you wrote these paragraphs =)

**Comment by polybassa** [comment]
Yes I'm the author of these paragraphs. Therefore I also wanted to have the explicit section author tag, so that I will not get problems with similar paragraphs in my thesis.

**Pull request merged**
