### PR TITLE
Move automotive specific files in the correct place

### PR DESCRIPTION
**Pull request by polybassa**
No code changes... just movements

### CODE REVIEW

**Comment by polybassa** [comment]
Sorry... Done

**Comment by p-l-** [comment]
Tests seem broken...

**Comment by polybassa** [comment]
ok, fixed it

**Comment by polybassa** [comment]
Can this PR get merged, that I can continue with some more minor changes?

**Comment by polybassa** [comment]
Done

**Comment by gpotter2** [comment]
Great !

**Pull request merged**
