### PR TITLE
Fix Windows imports

### PR DESCRIPTION
**Pull request by gpotter2**
This is the reason why coverage was so low.
https://github.com/secdev/scapy/pull/1621 contained a few wrong imports that were not triggered in the tests.

This PR:
- fixes the imports
- fix UTscapy to report correctly such failures

### CODE REVIEW

**Comment by gpotter2** [comment]
Calling @guedou

**Comment by guedou** [comment]
A network related test is currently failing.

**Comment by gpotter2** [comment]
Ok got it, I haven’t broken anything, this test was silently failing already
https://travis-ci.org/secdev/scapy/jobs/440201244

**Comment by guedou** [comment]
It works fine locally.

**Comment by gpotter2** [comment]
Ok i have no clue why this is failing on OSX only... not very familiar with it and can’t debug it...

Could not reproduce under Linux/pcapdnet (as in the tests).

I wonder if it means all networking is broken or if it’s only this specific test. It could also be unrelated to scapy (a dependency update...)

**Comment by guedou** [comment]
A quick and dirty solution wil be to flag this test a `not_pcapdnet`. I did not have time to reproduce it on osx yet.

**Pull request merged**
