### PR TITLE
Fix *BSD bpf detection

### PR DESCRIPTION
**Pull request by gpotter2**
fixes https://github.com/secdev/scapy/issues/1793

### CODE REVIEW

**Comment by guedou** [comment]
I tested it on FreeBSD12 and it works fine, except for one test in `test/pipetool.uts`.

**Comment by guedou** [comment]
I will submit a PR.

**Comment by gpotter2** [comment]
Yes the last on fails on HTTP 1.1 rather than HTTP 1.0
Had the same issue when trying out #1660 but I don’t think that’s the root the issue. Otherwise the tests passed :/

**Comment by guedou** [comment]
I will push a fix soon.

**Pull request merged**
