### PR TITLE
Fix TLS constants names

### PR DESCRIPTION
**Pull request by mtury**
This should fix issue #746.

@rafajot thanks for pointing this out. Would you care to verify that a scapy build from this branch works as you expect?

### CODE REVIEW

**Comment by rafajot** [comment]
Sadly, I have tried the build https://github.com/secdev/scapy/tree/6baf1efed0b69bafaba1bea6271563d247a9bd28 but I still have the same issue with debugger when loading TLS layer.

**Comment by mtury** [comment]
My bad, I forgot a few constants. Hopefully this should do the job.

**Comment by rafajot** [comment]
Still no success. The last breakpoint I can set is on line 94, record_tls13.py
`                    _TLSInnerPlaintextField("inner", TLSInnerPlaintext()),`
after that there is some very long recursion in getfield_and_val function from packet.py and if I let the code to continue from that point degugging stops to work.

**Comment by mtury** [comment]
Could you show us the beginning of the recursion loop, please?

**Comment by rafajot** [comment]
Is that what you are asking for?

image

**Comment by mtury** [comment]
I was actually interested in the `attr`.

**Comment by rafajot** [comment]
Ok, I have a main function which looks like this:

```
    print "aa"
    from scapy.all import IP
    print"bb"
```
and I have amended getfield_and_val() function in packet.py to display recursions and attr value:

```
    def getfield_and_val(self, attr):
        global _zima
        _zima = _zima+1
        print ("zima=" + str(_zima) + ' ' + str(attr))
        if attr in self.fields:
            return self.get_field(attr),self.fields[attr]
        [...]
```

The outcome during debug run is not always the same and number of recursions differ across different debug runs. I have attached one example output for normal run and two different outputs for different debug runs.

Do I understand correctly that after applying your latest fix you can not reproduce the bug in your environment?

[scapy_debug2.txt](https://github.com/secdev/scapy/files/1227729/scapy_debug2.txt)
[scapy_debug1.txt](https://github.com/secdev/scapy/files/1227730/scapy_debug1.txt)
[scapy_run1.txt](https://github.com/secdev/scapy/files/1227731/scapy_run1.txt)

**Comment by mtury** [comment]
Oddly enough I can't seem to be able to reproduce the bug. I'm not running on Windows, I'm not sure how this could change things...

However thanks to your debug now I think I know where this is coming from. When calling its `__init__`, the TLSInnerPlaintext class is looking for a `tls_session` attribute, but because it inherits from Packet and because the Packet's `__init__` has not been called yet, the `fields` attribute has not been defined yet, and this throws it into the loop.

Could you try the latest commit?

**Comment by rafajot** [comment]
Yes, its good now. Thank you for the fix!

**Comment by mtury** [comment]
Great! Calling @p-l- or @guedou for merging (the commits may be squashed).

**Pull request merged**
