### PR TITLE
Fix an error of field definition in contrib.lldp.LLDPDUPortID class.

### PR DESCRIPTION
**Pull request by karpierz**
Scapy Version: 2.4.0rc5-79
System: Windows7/Windows10
Python Version: 2.7.14/3.4.4/3.6.4

Fix for field definition error in contrib.lldp.LLDPDUPortID class
Improvement of definitions in contrib.lldp
Add missing declaration of ByteField in contrib.lldp
Add tesst for check fields definition

### CODE REVIEW

**Comment by karpierz** [comment]
Reopened due to weird problems with Apveyor server

**Comment by karpierz** [comment]
PR is ready for merge to the master.

**Comment by karpierz** [comment]
I withdrew editing/cosmetic changes, which made the fix trivial and obvious.
PR is ready for merge to the master.

**Comment by karpierz** [comment]
Reopening due to travis fails/timeouts.

**Comment by karpierz** [comment]
PR is ready for merge to the master.

**Comment by guedou** [comment]
You can reopen your PRs. I will have time to review them next week.

**Comment by karpierz** [comment]
It is already quite not important for me, but ff you want?...

**Comment by karpierz** [comment]
PR is ready for merge to the master.

**Pull request merged**
