### PR TITLE
Make scapy usable as a third party library

### PR DESCRIPTION
**Pull request by robin-jarry**
When using scapy as an external lib, we encounter some problems with importing some modules. 
Here are some examples:

```
$ python -c "import scapy.layers.dhcp6"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "scapy/layers/dhcp6.py", line 17, in <module>
    from scapy.layers.inet6 import *
  File "scapy/layers/inet6.py", line 1717, in <module>
    from scapy.layers.dhcp6 import DomainNameListField
ImportError: cannot import name DomainNameListField
```
```
$ python -c "import scapy.contrib.spbm"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "scapy/contrib/spbm.py", line 37, in <module>
    bind_layers(Dot1Q, SPBM, type=0x88e7)
NameError: name 'Dot1Q' is not defined
```
```
$ python -c "import scapy.contrib.icmp_extensions"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "scapy/contrib/icmp_extensions.py", line 165, in <module>
    scapy.layers.inet.ICMPerror.post_dissection = ICMPExtension_post_dissection
NameError: name 'scapy' is not defined
```
```
$ python -c "import scapy.contrib.ospf"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "scapy/contrib/ospf.py", line 585, in <module>
    class OSPFv3_Inter_Area_Prefix_LSA(OSPF_BaseLSA):
  File "scapy/contrib/ospf.py", line 599, in OSPFv3_Inter_Area_Prefix_LSA
    IP6PrefixField("prefix", "2001:db8:0:42::/64", wordbytes=4, length_from=lambda pkt: pkt.prefixlen)]
TypeError: __init__() got an unexpected keyword argument 'length_from'
```

The first commit fixes all these errors (and also others).

The second commit prevents the shadowing of python internal symbols (`__all__`, `__file__`, `__doc__`, `__package__`, etc.) they should **not** be replaced by the one from other modules.

Also, when importing any part of scapy, we get some warning messages printed on the console.

```
WARNING: Failed to execute tcpdump. Check it is installed and in the PATH
```

The last commit allows to control the logging of scapy messages.

I have executed all tests suites and everything is ok. Please tell me what do you think.

PS: it would be a great thing to use pylint on a regular basis on scapy. This would obviously require to fix all errors first. I don't have the time to do it all but I can help on some parts.

### CODE REVIEW

**Comment by p-l-** [comment]
Could you explain what problem this PR solves? Thanks!

**Comment by robin-jarry** [comment]
Hi @p-l- ,

Sorry my message was a bit laconic. I have updated the PR description.

Also, I have simplified the 2nd patch.

**Comment by robin-jarry** [comment]
Arf,

travis failed because of some download failure:

```
==> Downloading http://downloads.sourceforge.net/project/pylibpcap/pylibpcap/0.6
Error: Failed to download resource "pylibpcap"
Download failed: http://downloads.sourceforge.net/project/pylibpcap/pylibpcap/0.6.4/pylibpcap-0.6.4.tar.gz
```

It worked this morning. Maybe sourceforge is down...

Can we run it again?

**Comment by robin-jarry** [comment]
Ineed sourceforge has problems:

```
$ wget http://downloads.sourceforge.net/project/pylibpcap/pylibpcap/0.6.4/pylibpcap-0.6.4.tar.gz
--2016-08-01 16:29:59--  http://downloads.sourceforge.net/project/pylibpcap/pylibpcap/0.6.4/pylibpcap-0.6.4.tar.gz
Resolving downloads.sourceforge.net (downloads.sourceforge.net)... 216.34.181.59
Connecting to downloads.sourceforge.net (downloads.sourceforge.net)|216.34.181.59|:80... connected.
HTTP request sent, awaiting response... 504 Gateway Time-out
2016-08-01 16:30:05 ERROR 504: Gateway Time-out.
```

**Comment by p-l-** [comment]
Thanks a lot for that important work (and for explaining it)! That's a very useful (and very clean, for that matters) contribution.

**Comment by robin-jarry** [comment]
Thanks @p-l- !

**Pull request merged**
