### PR TITLE
Force Python 2 for run_scapy_py2.bat, use Python 3 first in run_scapy.bat

### LINKED ISSUE #1763: run_scapy_py2.bat assumes python leads to python2
The `run_scapy_py2.bat` script launches scapy with the command `python -m scapy`. 

On my system, `python` links to `python3`. Thus I just got a huge confustion calling `run_scapy_py2.bat` until I figured it out.

I guess the script should call `python2 -m scapy`, the linux launch script seems to set it explicitly too.

### PR DESCRIPTION
**Pull request by p-l-**
Fixes #1763.

### CODE REVIEW

**Comment by gpotter2** [comment]
`python2` will most likely crash.

A default python installation on Windows doesn't really take multiple versionning into consideration. 
Here's the default Python 3.7 install:

image

There is most likely no way to guess which python version it is :/ I previously assumed that one would rename `python` to `python3` on the Python3 installation, if he had multiple python versions installed. That way `python` led to 2.7 and `python3` to 3 :/

**Comment by p-l-** [comment]
@gpotter2 thanks for your answer. I suppose there is nothing simple we could do for that?

**Comment by gpotter2** [comment]
We could first try `python2` then fallback on `python`. That would work for the (few) users who have updated their binaries accordingly

**Comment by p-l-** [comment]
Maybe we could simply remove the `run_scapy_py{2,3}.bat`, which are misleading, and leave only `run_scapy.bat`?

**Pull request closed without merging**
