### PR TITLE
[Windows] Fixed ppi_geotag

### PR DESCRIPTION
**Pull request by gpotter2**
Fixes ppi_geotag's part in https://github.com/secdev/scapy/issues/432 + added a few tests

### CODE REVIEW

**Comment by p-l-** [comment]
Could you explain why you replaced `time.gmtime(0)`?

**Comment by gpotter2** [comment]
It's a windows bug: `time.gmtime(0)` will return a tuple with the date (1970, 1, 1). But for some reasons, on windows only, the range starts at (1970,1,2)

**Comment by p-l-** [comment]
@gpotter2 so maybe you could just define a global constant `EPOCH = time.mktime((1970, 1, 1, 0, 0, 0, 0, 0, 0))`? BTW I think the current code is wrong, because you have used 1970-1-2 as the start time, while it should be 1970-1-1.

**Comment by gpotter2** [comment]
@p-l- The windows bug: `time.mktime((1970, 1, 1, 0, 0, 0, 0, 0, 0))` crash because Windows Epoch is 01/01/1970 at 00:00 but of the next day (so 01/02/1970 at 00:00)
`time.mktime((1970, 1, 2, 0, 0, 0, 0, 0, 0))-86400` will do the trick i guess...

**Comment by gpotter2** [comment]
That should do the trick

**Comment by gpotter2** [comment]
@guedou Hey, on master this if failing... I don't know what has changed since the tests were performed... any ideas ?

**Comment by guedou** [comment]
@gpotter2 I have no idea =/ The patches looked good to me. 

The issue might be related to PR#471 Could you have a look ?

**Comment by gpotter2** [comment]
I'll check that
@p-l CAN you have a look too please ?

**Pull request merged**
