### PR TITLE
Added IPv6 and IPv4/IPv6 support to GTP

### PR DESCRIPTION
**Pull request by decastromonteiro**
Changed IE_EndUserAddress() class and also added the possibility to send and receive DeletePDPContext packets.

### CODE REVIEW

**Comment by decastromonteiro** [comment]
Hello guys, please help me solve the issue with coverage. I have no clue of what I can do.

**Comment by p-l-** [comment]
Hi,

Thanks for your contribution!

Can you please remove the unneeded changes from your patch? We're trying (hard!) to keep the code history clean and tend to avoid changes like removing spaces at the end of the files.

About the coverage, can you add more tests? Specifically related to your changes (checking that a packet and a possible answers have the same `.hashret()` value and that `.answers()` works fine?

**Comment by decastromonteiro** [comment]
> About the coverage, can you add more tests? Specifically related to your changes (checking that a packet and a possible answers have the same .hashret() value and that .answers() works fine?

Could you share an example of how to test those methods, please?

> Can you please remove the unneeded changes from your patch? We're trying (hard!) to keep the code history clean and tend to avoid changes like removing spaces at the end of the files.

I'll remove any unneeded changes, thank you.

**Comment by p-l-** [comment]
> Could you share an example of how to test those methods, please?

Look for `.answers` and `.hashret` in `*.uts` files in `test/` (and `scapy/contrib/`).

**Comment by p-l-** [comment]
ping @decastromonteiro (about the tests)

**Comment by alexsult** [comment]
Hi @decastromonteiro ,

First of all, thanks for improving the GTP support. Like @p-l- , I have few things to say :
1. The *IE_EndUserAddress* field may be already used by other scapy scripts/programms, so changing *PDPAdress* to *PDPAddress_IPv4* (even if it is more appropriate) would break existing code. Could you keep the name *PDPAdress* for IPv4 and use *PDPAddress_IPv6* for IPv6 ?
2. To continuously check if commits don't affect old functions, it is asked to write tests corresponding to (all) the changes you do.
Here is how you can check your code is covered (with the coverage module):
To update coverage :
> PYTHONPATH=. coverage run  scapy/tools/UTscapy.py -P "load_contrib('gtp')" -t scapy/contrib/gtp.uts

And to check:

> $ coverage report scapy/contrib/gtp.py
> Name                   Stmts   Miss  Cover
> scapy/contrib/gtp.py     301     41    86%

Before your modifications, it was 87% covered. We don't ask you to add tests for everything, but could you add them for what you did ?

To see what is covered:

> $ coverage html scapy/contrib/gtp.py

It produces an *html* report in the *htmlcov* of your current directory.

About .anwsers and .hashret :

* Hashret
> hashret(self)
> Must returns a string that has the same value for a request and its answer.The result of this function is used as a hash value to speed up the look fora the request matching a given response.

You are using .seq with does not exist in *GTPDeletePDPContextResponse* (so it will not work), but this field exists in *GTPHeader* and I would use it (*seq* from the *GTPHeader*) with the sgsn and ggsn IP addresses to construct this *hash value*.

* Answers
> answers(self,other)
> True if self is an answer from other

I think that you can compare the results of the .hashret of the two packets

3. I have seen you removed trailing spaces, that's nice regarding the pep8, but it makes difficult to read the diffs and to keep track of the modifications, could you  cancel this changes ?

Alexis

**Pull request closed without merging**
