### PR TITLE
Fix UDP bindings

### PR DESCRIPTION
**Pull request by gpotter2**
Fixes https://github.com/secdev/scapy/issues/1382 and many others

### CODE REVIEW

**Comment by guedou** [comment]
Could you add some simple unit tests to ensure that ports are correctly selected?

**Comment by guedou** [comment]
I don't understand why the calls to `bind_layer()` does not work as expected. Do we need to fix it?

**Comment by gpotter2** [comment]
When doing manuel bindings without specifying the ports, when the bindings were, for instance, as such:
```
bind_layers(UDP, MobileIP, sport=434)
bind_layers(UDP, MobileIP, dport=434)
```
the packet only gets the bindings from the last `bind_layer` call (in this example, dport) and sport is defaulted to 53 (DNS). But because DNS has priority on other layers, packets are re-dissected as DNS:
image
One need to change that to
```
bind_layers(UDP, MobileIP, sport=434)
bind_layers(UDP, MobileIP, dport=434)
bind_layers(UDP, MobileIP, dport=434, sport=434)
```
However, `bind_layers` calls are un-necessary, as when building packets, only the last one is used. Others can be replaced by `bind_bottom_up`, so that they only get used during dissection

**Comment by gpotter2** [comment]
@guedou BTW, have you notived that some (dnet) tests are run twice ? See 
https://travis-ci.org/secdev/scapy/jobs/374005883
if you search for `regression.uts` you will noticed that all tests ran twice.

**Comment by guedou** [comment]
@gpotter2 this is the first `tox` tests that I introduced and `TOXENV` is set t to `py36-osx_non_root,py36-osx_root,codecov`as a result two tests are launched at the same time. I can make two tests in Travis but it will take longer to execute.

**Comment by gpotter2** [comment]
Didn't know about the tests, current way is fine =)
I've added some quite clear docs (with examples)

**Comment by p-l-** [comment]
Good for me. @guedou you can merge it if that's OK for you. Thanks @gpotter2!

**Pull request merged**
