### PR TITLE
Don't require newline at end of pcapng comment

### PR DESCRIPTION
**Pull request by nkorth**
I couldn't find anything in the spec about requiring this.

**Checklist:**

-   [x] If you are new to Scapy: I have checked [CONTRIBUTING.md](https://github.com/secdev/scapy/blob/master/CONTRIBUTING.md) (esp. section submitting-pull-requests)
-   [x] I added unit tests or explained why they are not relevant
-   [x] I executed the regression tests (using `cd test && ./run_tests` or `tox`)

### CODE REVIEW

**Review by p-l- — APPROVED** [review]

**Comment by gpotter2** [comment]
Awaiting a review from @guedou

**Comment by guedou** [comment]
I think that this PR is not valid as current Scapy behavior is explicitly written in https://www.ietf.org/archive/id/draft-tuexen-opsawg-pcapng-05.html

```
opt_comment:

    The opt_comment option is a UTF-8 string containing human-readable comment text that is associated to the current block. Line separators SHOULD be a carriage-return + linefeed ('\r\n') or just linefeed ('\n'); either form may appear and be considered a line separator. The string is not zero-terminated.
```

**Comment by nkorth** [comment]
I suggest the change in this PR. The code that I'm deleting here enforced something like "the string MUST end with a line separator", but there's no such statement in the spec.

The spec says this about line separators:

> Line separators SHOULD be a carriage-return + linefeed ('\r\n') or just linefeed ('\n'); either form may appear and be considered a line separator.

and the example in the spec demonstrates both types of line separators in use, but does not **end** in a line separator.

> "Packets 17-23 showing a bogus TCP retransmission!\r\n This is reported in bugzilla entry 1486.\nIt will be fixed in the future."

**Comment by guedou** [comment]
Oh, I see. You are absolutely right. I incorrectly assumed that `\n`should be a the end of the line. I should have use the example from the specifications in the regression tests to figure this out.

**Review by guedou — APPROVED** [review]
Thanks for this PR and your answers to my questions!

**Pull request merged**
