### PR TITLE
Typing of Answeringmachine [ready]

### PR DESCRIPTION
**Pull request by polybassa**
Started with typing of answeringmachine.

I'm not so happy, yet. 
In EcuAnsweringMachines I use PacketLists as reply. If I consider this in the base class, the code gets a little messy. 

@gpotter2 Do you have an idea to fix that?

Unfortunately, I can not overwrite the types of derived classes. 
I tried to apply `_T = TypeVar("_T", Packet, PacketList)` to
```
    def make_reply(self, req):
        # type: (Packet) -> _T
        ...

    def send_reply(self, reply):
        # type: (_T) -> None
        ...

    def print_reply(self, req, reply):
        # type: (Packet, _T) -> None
```
in order to allow both cases, but I couldn't overwrite make_reply in EcuAnsweringMachine.

Maybe you have a idea to improve that.

### CODE REVIEW

**Comment by polybassa** [comment]
OK, I figured out, how I can use generics ;-D

**Comment by gpotter2** [comment]
It's extremely powerful once learn how to use it :)

**Comment by polybassa** [comment]
Had some issues with the metaclasses.. but now it should be fixed.

**Comment by polybassa** [comment]
@gpotter2 May I ask you a question. What is the idea of `six.with_metaclass`, more specific, what is the idea of `metaclasses` in Scapy?

**Comment by gpotter2** [comment]
There are probably places in Scapy where metaclasses could be replaced with easier options.

But we also use them do so very specific things such as registering a class in a dictionary automatically, or changing the class dynamically (especially on Packets), which to my knowledge cannot be achieved with the more "rigid" patterns ABC has to follow.

**Comment by polybassa** [comment]
Alright. Thanks for this explanation.
--

**Review by gpotter2 — APPROVED** [review]

**Comment by gpotter2** [comment]
Please fix the conflicts, otherwise LGTM.

**Comment by polybassa** [comment]
@gpotter2 I don't see any conflicts here. Should I fix something?

**Comment by gpotter2** [comment]
No sorry I fixed them already.

**Pull request merged**
