### PR TITLE
Cleanup unit test for OBDScanner

### PR DESCRIPTION
**Pull request by polybassa**
Another cleanup PR for automotive unit tests.

### CODE REVIEW

**Review by guedou — COMMENTED** [review]
What is the usage of tracemalloc in the CI?

**Comment by polybassa** [comment]
I discovered some ResourceWarnings during a failing test. I think these warnings are somehow involved in the failing if these tests. Therefore I wanted to debug them. These warnings doesn't show up on my local setup, sadly. 

Here is an example https://github.com/secdev/scapy/runs/3482156637#step:5:12085


On September 2, 2021 5:18:30 PM GMT+02:00, Guillaume Valadon ***@***.***> wrote:
***@***.*** commented on this pull request.

**Comment by polybassa** [comment]
Do you have an idea how to debug this the proper way?

On September 2, 2021 5:18:30 PM GMT+02:00, Guillaume Valadon ***@***.***> wrote:
***@***.*** commented on this pull request.

**Comment by guedou** [comment]
Understood! That call will disappear in the final commit =)

My guess is there are some file descriptors that do no have the __del__ or close method implemented.

**Comment by polybassa** [comment]
This PR is ready for review and merge

**Review by guedou — APPROVED** [review]

**Pull request merged**
