### PR TITLE
Use current signature hash when resigning cert

### PR DESCRIPTION
**Pull request by bezvan**
* Fix choice of hash function when resigning cert

### CODE REVIEW

**Review by KhazAkar — COMMENTED** [review]
Looks fine, but do you have any example of such behavior, like before and after?

**Comment by bezvan** [comment]
The unexpected behavior is triggered when resigning a certificate whose signature does not use SHA256 as hash algorithm.
For instance, if we generate an auto-signed certificate using SHA1 as hash:
`openssl req -x509 -nodes -newkey rsa:512 -keyout key.pem -out cert.pem
-sha1 -subj "/C=FR"
`

Then, the following scapy script will behave differently with or without this patch:
```
load_layer("tls")
cert = X509_Cert(pem2der(open("cert.pem","rb").read()))
k = PrivKey("key.pem")
resigned = k.resignCert(cert)
# Expression evaluated as False with scapy master and evaluated as True with this patch
print(cert.signatureValue == resigned.signatureValue)
exit
```

**Comment by KhazAkar** [comment]
> The unexpected behavior is triggered when resigning a certificate whose signature does not use SHA256 as hash algorithm. For instance, if we generate an auto-signed certificate using SHA1 as hash: `openssl req -x509 -nodes -newkey rsa:512 -keyout key.pem -out cert.pem -sha1 -subj "/C=FR" `
> 
> Then, the following scapy script will behave differently with or without this patch:
> 
> ```
> load_layer("tls")
> cert = X509_Cert(pem2der(open("cert.pem","rb").read()))
> k = PrivKey("key.pem")
> resigned = k.resignCert(cert)
> # Expression evaluated as False with scapy master and evaluated as True with this patch
> print(cert.signatureValue == resigned.signatureValue)
> exit
> ```

Thanks for example, I will check it on my PC before and after :)

**Comment by gpotter2** [comment]
Hi and thanks a lot for the report.
Could you add a small unit test? That's an interesting issue. 
Thanks !

**Comment by bezvan** [comment]
Hello, I completed the existing PrivKey tests set with a resign test unit.
The old "sign tbs cert test" unit contained some code with resignCert, but this code was incorrect because it incorrectly ignored the resignCert returned value (see below). This has been fixed and separated in this new test unit.
```
pkey_sign.resignCert(c_tosign) # no-op because resignCert is a pure function
assert pkey_sign.verifyCert(c_tosign) # only verifies the signature in the original cert
```

**Review by gpotter2 — APPROVED** [review]

**Pull request merged**
