### PR TITLE
Add Modbus Schneider Electric specific function code

### PR DESCRIPTION
**Pull request by thmsaurel**

### CODE REVIEW

**Comment by p-l-** [comment]
Hi,

Are these packets empty (with only the `funCode` field)?

**Comment by thmsaurel** [comment]
Hi,
the rest of the fields are closed-source.

**Comment by p-l-** [comment]
Then I don't feel like it's necessary to add a new packet type is useful. Maybe using a `ByteEnum` field instead of an `XByte` for `funCode` would be enough?

**Comment by thmsaurel** [comment]
It can be done but if you do it, you will have to change all the other `funcCode` of the file (wich are in `XByte`) to keep a global logic. It's more common to read Modbus value as hexa as decimal.

I can transform the function to create object class to all proprietary protocols. A `ModbusPDUProprietaryFunction` for example (with a `ByteEnum` for as `funCode`).

**Comment by smainand** [comment]
Hi,
it could be a good way to make the layer aware of the 3 Modbus function code categories: Public, User-defined and Reserved (where the 0x5a falls into). It would also make more sense than the default ModbusPDU00GenericQuestion/Request/Error objects used for packet dissection.

**Comment by thmsaurel** [comment]
I understand the idea of the `Public` Category and the `Reserved` one. What is the purpose of a `UserDefined` category ?

**Comment by smainand** [comment]
Just to comply with the Modbus specification, which defines two ranges of function (65->72 and 100->110) codes that can be used by anyone to implement a new function code.

**Comment by thmsaurel** [comment]
ok. I have add six objects with the related dictionaries :
* `ModbusPDUReservedFunctionCodeRequest`
* `ModbusPDUReservedFunctionCodeResponse`
* `ModbusPDUReservedFunctionCodeError`
* `ModbusPDUUserDefinedFunctionCodeRequest`
* `ModbusPDUUserDefinedFunctionCodeResponse`
* `ModbusPDUUserDefinedFunctionCodeError`

**Comment by thmsaurel** [comment]
I will close this pull request and start a new one once i finished the test implementation

**Pull request closed without merging**
