### PR TITLE
[WIP] TLS 1.3

### PR DESCRIPTION
**Pull request by gpotter2**
There is way over my head to do, here's what I could get so far:
- (this PR includes https://github.com/secdev/scapy/pull/1574)
- fixes small IP bug when ihl < 5
- merges TLS13ServerHello and TLSServerHello, as there is now no way to differentiate them apart from their extensions
- updates some constants
- Fix TLSServerHello dissection + Implement the new (changed) HelloRetry
- updated the pack (2/2) of tests according to the latest draft. Some still don't pass

**TODO: (feel free to contribute)**
- fixes https://github.com/secdev/scapy/issues/1668
- fix the remaining tests
- find a way to have `gtx_unix_time` exist only on TLS 1.3, in which case `random_bytes` size is 32 (rather than 28)

### CODE REVIEW

**Comment by p-l-** [comment]
Hi!

Can you rebase against current master and remove the merge commit from the PR?

**Comment by gpotter2** [comment]
This is highly broken. Any help is appreciated as I have little time to look at it

**Comment by gpotter2** [comment]
More tests are passing, This also fixes how TLS1.3 version is detected (especially in Hello messages).
- Most Hello messages are now correctly dissected
- The certificate fail at decoding (TLS13 integrity fail)

**Comment by guedou** [comment]
@gpotter2 that might help you understanding the protocol without having to dig deep into the RFC https://tls13.ulfheim.net/

**Comment by gpotter2** [comment]
I actually don't want to handle this issue. Hope one of you can take care of it

**Comment by guedou** [comment]
TLS 1.3 is hard.

Could you reopen the PR to remind me to have a look at it?

**Comment by gpotter2** [comment]
I poorly force-pushed this one, see https://github.com/secdev/scapy/pull/1726

**Comment by guedou** [comment]
I understand =)

**Pull request closed without merging**
