### PR TITLE
Support for Diameter protocol layer (base RFC6733 + extensions)

### PR DESCRIPTION
**Pull request by pbat0908**
This pull request is directly taken from the July 2015 one on BitBucket. It works with Scapy version up to 2.3.2 (released in December 2015) but not with the current 2.3.2-dev version, probably due to modifications made in fields.py since the 2.3.2 release. Contributions are welcomed to fix this.

### CODE REVIEW

**Comment by gpotter2** [comment]
@pbat0908 Hello. If you still want this PR to be taken in consideration, please update your code to match the current scapy version's requirements, otherwise this will be closed for inactivity.

**Comment by gpotter2** [comment]
Fixed PR in https://github.com/secdev/scapy/pull/607

**Comment by guedou** [comment]
Rewritten in #607

**Comment by pbat0908** [comment]
Thanks for these modifications enabling support of diameter with current 
Scapy implementation.
Patrick

**Pull request closed without merging**
