### PR TITLE
More layer bindings for GRE

### LINKED ISSUE #534: Invalid GRE proto binding for Ether over GRE
```
>>> GRE() / Ether()
<GRE  proto=0x1 |<Ether  |>>
```

According to https://tools.ietf.org/html/rfc1701 the valid protocol number should be 0x6558.

### PR DESCRIPTION
**Pull request by bartex80**
Fixes #534

### CODE REVIEW

**Comment by guedou** [comment]
@p-l- could you restart the appveyor tests ?

**Comment by bartex80** [comment]
Is the appveyor failures related to my changes?

**Comment by guedou** [comment]
@bartex80 no. Sometimes, some tests fail due to network conditions.

**Comment by guedou** [comment]
I will close and reopen this PR to relanunch the unit tests.

**Comment by bartex80** [comment]
> Codecov Report
> Merging #555 into master will decrease coverage by 0.63%.

It's not true, it analyses the differences between my commits and current origin/master instead of the master from the time this commits were published...

**Comment by guedou** [comment]
@bartex80 don't worry. Your commit can be merged even if codecov complains =)

**Comment by guedou** [comment]
@gpotter2 do you understand why the tests fail on AppVeyor ?

**Comment by gpotter2** [comment]
@bartex80 Please rebase against master, i guess that's the problem....

**Comment by bartex80** [comment]
Commit rebased against master (Fix automaton tests) but there are still some problems with tests on windows...

**Comment by gpotter2** [comment]
@bartex80 Please test your code before submitting PR... If you had started scapy only once you would have seen:
```
WARNING: can't import layer inet: 'module' object has no attribute 'IPPROTO_GRE'
WARNING: can't import layer dhcp: 'module' object has no attribute 'IPPROTO_GRE'
WARNING: can't import layer dns: 'module' object has no attribute 'IPPROTO_GRE'
WARNING: can't import layer dot11: 'module' object has no attribute 'IPPROTO_GRE'
WARNING: can't import layer gprs: 'module' object has no attribute 'IPPROTO_GRE'
WARNING: can't import layer hsrp: 'module' object has no attribute 'IPPROTO_GRE'
WARNING: can't import layer inet6: 'module' object has no attribute 'IPPROTO_GRE'
WARNING: can't import layer l2tp: 'module' object has no attribute 'IPPROTO_GRE'
WARNING: can't import layer ntp: 'module' object has no attribute 'IPPROTO_GRE'
WARNING: can't import layer ppp: 'module' object has no attribute 'IPPROTO_GRE'
WARNING: can't import layer dhcp6: 'module' object has no attribute 'IPPROTO_GRE'
WARNING: can't import layer llmnr: 'module' object has no attribute 'IPPROTO_GRE'
WARNING: can't import layer sctp: 'module' object has no attribute 'IPPROTO_GRE'
WARNING: can't import layer ipsec: 'module' object has no attribute 'IPPROTO_GRE'
WARNING: can't import layer lltd: 'module' object has no attribute 'IPPROTO_GRE'
WARNING: can't import layer vxlan: 'module' object has no attribute 'IPPROTO_GRE'
Welcome to Scapy (2.3.3.dev278)
>>>
```

**Comment by bartex80** [comment]
@guedou I don't have any windows machine and the AppVeyor output didn't help at all... I will submit second version soon.

**Comment by gpotter2** [comment]
>  I don't have any windows machine and the AppVeyor output didn't help at all...
No worry :). It's true that we shall provide better logs while loading...

**Pull request merged**
