### PR TITLE
Increase test-coverage of uds_scanner

### PR DESCRIPTION
**Pull request by polybassa**
This PR increases the test-coverage of the UDSScanner and speeds up the execution.

### CODE REVIEW

**Comment by polybassa** [comment]
reopen / close: ObjectPipe got closed during test on appveyor
```
[i] Start execution of enumerator: Tue Feb  8 18:58:49 2022
Socket <ObjectPipe at 794121183112> failed with 'Socket closed'. It was closed.
Exception in thread Thread-2737:
Traceback (most recent call last):
  File "C:\Python37-x64\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Python37-x64\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\projects\scapy\scapy\ansmachine.py", line 202, in __call__
    self.sniff()
  File "C:\projects\scapy\scapy\ansmachine.py", line 208, in sniff
    sniff(**self.optsniff)
  File "C:\projects\scapy\scapy\sendrecv.py", line 1300, in sniff
    sniffer._run(*args, **kwargs)
  File "C:\projects\scapy\scapy\sendrecv.py", line 1247, in _run
    session.on_packet_received(p)
  File "C:\projects\scapy\scapy\sessions.py", line 106, in on_packet_received
    result = self.prn(pkt)
  File "C:\projects\scapy\scapy\ansmachine.py", line 181, in reply
    self.send_reply(reply)
  File "C:\projects\scapy\scapy\contrib\automotive\ecu.py", line 677, in send_reply
    self._main_socket.send(p)
  File "C:\projects\scapy\test\testsocket.py", line 69, in send
    super(TestSocket, r).send(sx)  # type: ignore
  File "C:\projects\scapy\scapy\automaton.py", line 183, in send
    os.write(self.__wr, b"X")
OSError: [Errno 9] Bad file descriptor
[-] Socket closed during scan.
[-] Exit execute. Retry packet next time!
```

**Comment by polybassa** [comment]
@gpotter2 Can this PR get merged, please?

**Comment by gpotter2** [comment]
> reopen / close: ObjectPipe got closed during test on appveyor
> 
> ```
> 
> [i] Start execution of enumerator: Tue Feb  8 18:58:49 2022
> 
> Socket <ObjectPipe at 794121183112> failed with 'Socket closed'. It was closed.
> 
> Exception in thread Thread-2737:
> 
> Traceback (most recent call last):
> 
>   File "C:\Python37-x64\lib\threading.py", line 926, in _bootstrap_inner
> 
>     self.run()
> 
>   File "C:\Python37-x64\lib\threading.py", line 870, in run
> 
>     self._target(*self._args, **self._kwargs)
> 
>   File "C:\projects\scapy\scapy\ansmachine.py", line 202, in __call__
> 
>     self.sniff()
> 
>   File "C:\projects\scapy\scapy\ansmachine.py", line 208, in sniff
> 
>     sniff(**self.optsniff)
> 
>   File "C:\projects\scapy\scapy\sendrecv.py", line 1300, in sniff
> 
>     sniffer._run(*args, **kwargs)
> 
>   File "C:\projects\scapy\scapy\sendrecv.py", line 1247, in _run
> 
>     session.on_packet_received(p)
> 
>   File "C:\projects\scapy\scapy\sessions.py", line 106, in on_packet_received
> 
>     result = self.prn(pkt)
> 
>   File "C:\projects\scapy\scapy\ansmachine.py", line 181, in reply
> 
>     self.send_reply(reply)
> 
>   File "C:\projects\scapy\scapy\contrib\automotive\ecu.py", line 677, in send_reply
> 
>     self._main_socket.send(p)
> 
>   File "C:\projects\scapy\test\testsocket.py", line 69, in send
> 
>     super(TestSocket, r).send(sx)  # type: ignore
> 
>   File "C:\projects\scapy\scapy\automaton.py", line 183, in send
> 
>     os.write(self.__wr, b"X")
> 
> OSError: [Errno 9] Bad file descriptor
> 
> [-] Socket closed during scan.
> 
> [-] Exit execute. Retry packet next time!
> 
> ```
> 
> 

What's this about exactly?

**Comment by polybassa** [comment]
I don't develop on windows. You can run it with ``./test/run_tests -3  -t test/contrib/automotive/scanner/uds_scanner.uts
``

**Comment by KhazAkar** [comment]
LGTM. After running this command, everything went fine. Heck, even RBMAEnumerator have run :)
Screenshot from 2022-02-21 20-04-28
Screenshot from 2022-02-21 20-05-12

**Review by KhazAkar — APPROVED** [review]
Even windows can run it :)

**Review by gpotter2 — APPROVED** [review]

**Review by gpotter2 — APPROVED** [review]

**Pull request merged**
