### PR TITLE
[Networking/Windows] Added IPv6 support + No winpcap.dll support

### PR DESCRIPTION
**Pull request by gpotter2**
**Do not merge**

> Well this is https://github.com/secdev/scapy/pull/380 but a way more cleaner...

So as today, IPv6 routes are not supported by scapy on Windows. I guess we can modify that...

This patch:

- Fixes IPv4 get_routes_post2008 function
- Modified version detection to support Windows 10+
- Add the LOOPBACK_NAME on Windows
- Fixes some route6.py functions to work on Windows
- Removes double warning logs when loading scapy (when winpcap is not installed)

What it returns:
http://pastebin.com/hUU6ykcc

### CODE REVIEW

**Comment by gpotter2** [comment]
@guedou Please help... I'm gonna explode...... The tests are working perfectly fine on my windows computer, works on travis ci but keep crashing on appveyor...  
I've been stuck on it for hours 😠

**Comment by p-l-** [comment]
@gpotter2 I'm not sure I understand you well, but in that case the test is wrong and we should replace it with a test that works on both platforms. Which test is that?

**Comment by p-l-** [comment]
The comment is helpful there! So what is the value of `str(IP())` on Linux and on Windows? I have (Linux, current dev master): `'E\x00\x00\x14\x00\x01\x00\x00@\x00|\xe7\x7f\x00\x00\x01\x7f\x00\x00\x01'` I do not have a Windows computer to test right now.

**Comment by gpotter2** [comment]
This is the current secdev/master:
```
>>> str(IP())
'E\x00\x00\x14\x00\x01\x00\x00@\x00:\xc9\xc0\xa8\x00w\x7f\x00\x00\x01'
```

**Comment by p-l-** [comment]
@gpotter2 OK the problem is not about IP protocol (and that's good news), it's about src IP address. We should use the trick from @guedou `scapy.arch.windows.route_add_loopback()`. Maybe it should be run upon routing table creation on Windows?

**Comment by gpotter2** [comment]
If it's about the source, maybe this:
https://github.com/secdev/scapy/pull/397/files#diff-a9f72b412e9acf78502c904846ff2c67L476
Fixed it ? I'll have to check that tomorrow...

The first version of this part of the fix was using the adapter found above like the other function, and then I replaced it by a new network interface...

**Comment by gpotter2** [comment]
Well sorry i was wrong, @guedou 's work was correct:
```
>>> route_add_loopback()
>>> str(IP())
'E\x00\x00\x14\x00\x01\x00\x00@\x00|\xe7\x7f\x00\x00\x01\x7f\x00\x00\x01'
>>> _ == 'E\x00\x00\x14\x00\x01\x00\x00@\x00|\xe7\x7f\x00\x00\x01\x7f\x00\x00\x01'
True
```

**Comment by gpotter2** [comment]
Well all of that is outdated

**Comment by gpotter2** [comment]
Poof, here we are
https://github.com/secdev/scapy/pull/398

**Pull request closed without merging**
