### PR TITLE
Minor improvements to the gmlan utilities

### PR DESCRIPTION
**Pull request by polybassa**

### CODE REVIEW

**Comment by gpotter2** [comment]
Hi,
Don't know if you've noticed but it seems the docs are failing because of `from six.moves...` imports (should use `from scapy.modules.six.moves...` imports) in some automotive/isotp files.
I'll fix by tonight unless you want to have a look.
Thanks, have a good day

**Comment by polybassa** [comment]
oh sorry. I'll fix that now. Thanks for pointing this out.

**Comment by gpotter2** [comment]
Testing test stability (1)

**Comment by polybassa** [comment]
stable enough?

**Review by gpotter2 — APPROVED** [review]

**Pull request merged**
