### PR TITLE
Add SSLStreamSocket

### PR DESCRIPTION
**Pull request by X-Cli**
In issue #235, I talk about a problem when using SSL-wrapped sockets in combination with `scapy.supersocket.StreamSocket`. The problem is related to the use of the `MSG_PEEK` flag.

This PR provides an implementation of `SSLStreamSocket` that keeps a local buffer instead of relying on the kernel buffer for storage.

The following code demonstrates its usage:

```
import ssl
import socket
import multiprocessing
import time

import scapy.supersocket
import scapy.fields
import scapy.packet
import scapy.config

def server():
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    try:
        s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        s.bind(('127.0.0.1', 1234))
        s.listen(1)
        tlss = ssl.wrap_socket(s, keyfile="/home/fmaury/testclear.key", certfile="/home/fmaury/test.crt", server_side = True)
        (ss, _) = tlss.accept()
        time.sleep(2)
        ss.send("AAAA")
        print "blip"
        time.sleep(2)
        ss.send("BBBBCCCCDD")
        print "blip"
        time.sleep(2)
        ss.send("DD")
        print "blip"
        ss.close()
    except socket.error:
        print "Die die die!"
        raise


class TestPacket(scapy.packet.Packet):
    name = 'Test Packet'
    fields_desc = [
        scapy.fields.IntField('value', 0)
    ]
    def guess_payload_class(self, pay):
        return scapy.config.conf.padding_layer

if __name__ == '__main__':
    p = multiprocessing.Process(target = server)
    p.start()
    time.sleep(1)
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    try:
        s.connect(('127.0.0.1', 1234))
        s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        tlss = ssl.wrap_socket(s)
        ss = scapy.supersocket.SSLStreamSocket(tlss, basecls=TestPacket)
        while True:
            ss.recv().show()
    except socket.error:
        pass
    p.join()
```

I believe the interface to be compatible with `scapy.supersocket.StreamSocket`.

### CODE REVIEW

**Comment by p-l-** [comment]
Thanks!

Could you add some regression tests?

**Comment by X-Cli** [comment]
Adding a regression test for this is a bit of a conundrum with Scapy testing tool. I believe there are currently none for `scapy.supersocket.StreamSocket` that I could draw inspiration from.

I guess I could define a test case that defines a function drawing from the example code above, and then a test case that calls this function. 

Other than that, multiline tests with scopes are a bit difficult to implement; for example, I believe it is impossible to use a try/except block in the middle of a test case.

Do you have any advice or example for me to implement such test suite?

**Comment by X-Cli** [comment]
I'm not sure that the edited comment sent a ping. I added some regression tests. Are these enough for you?

**Comment by guedou** [comment]
@X-Cli sorry for the delay, we were waiting for the 2.3.3 before merging cool PRs. Could you fix the conflict ?

**Comment by X-Cli** [comment]
Done. Thanks for the update.

**Pull request merged**
