### PR TITLE
Fix RandTCPOptions for MD5

### PR DESCRIPTION
**Pull request by gpotter2**
fixes https://github.com/secdev/scapy/issues/3777

### CODE REVIEW

**Comment by nrathaus** [comment]
Looks better than my patch!

**Review by guedou — CHANGES_REQUESTED** [review]
Is this something that we can trigger in a unit test? If so, I think that it is worth a test giving the complexity of the fix at line 364.

**Comment by nrathaus** [comment]
Hi,

This triggers the bug, take into account that it might not always trigger it due to randomness of the option being picked
```
import scapy.all
payload = scapy.all.Ether()/scapy.all.IP(dst='192.168.15.1')/scapy.all.TCP()
p = scapy.all.fuzz(payload)
p.show2()
```

Look at my original issue #3777 for more details

**Comment by gpotter2** [comment]
We could @guedou. I just got lazy because random works differently on Python 2 and 3

**Comment by guedou** [comment]
You can skip the Python 2 test IMHO.Sent from my iPhoneOn 8 Nov 2022, at 13:18, gpotter2 ***@***.***> wrote:﻿
We could @guedou. I just got lazy because random works differently on Python 2 and 3

**Pull request merged**
