### PR TITLE
Move libpcap tests to Github Actions

### PR DESCRIPTION
**Pull request by gpotter2**
- Move libpcap tests to Github actions since our travis suite is pretty much dead
- Only test root with PyPy (the only differences we're testing with PyPy are the `attach_filter` functions.. root only + pypy tests already are super long due to the build-on-install)
- Small Github Actions tweaks

### CODE REVIEW

**Comment by gpotter2** [comment]
I have honnestly no idea of what's happening. Will need to debug this

**Review by p-l- — APPROVED** [review]

**Comment by gpotter2** [comment]
Sorry I wasnt clear. This PR is still broken and does not pass the tests

**Comment by p-l-** [comment]
My bad I only saw the "required" tests were OK...

**Comment by guedou** [comment]
We should try to use draft PR until we think that they are trash to be be reviewed.

**Comment by gpotter2** [comment]
Sorry about that. I started this off as a draft but couldn't recall if all tests were properly ran on draft PRs (wasn't the case on travis)

**Comment by p-l-** [comment]
No really that's my mistake here!

**Comment by guedou** [comment]
My mistake too. I have seen @p-l- approval and did not think of telling him not to merge =/

**Pull request merged**
