### PR TITLE
Standalone DHCPv6 unit tests

### PR DESCRIPTION
**Pull request by guedou**
As discussed in #2550 and #2755, this PR shows how `regression.uts` could be split prior to the `pytest` conversion.

### CODE REVIEW

**Review by gpotter2 — APPROVED** [review]
LGTM

**Comment by guedou** [comment]
Once this is merged, I will provide more PR splitting unit tests.

**Comment by polybassa** [comment]
Great. 
Should I set up a new PR with pytest, based on that split?
--

**Comment by guedou** [comment]
Let's wait for the complete split of unit tests before moving to `pytest` =)

Does your script that converts `.uts` to `.py` works fine with `dhcp6.uts`?

**Comment by polybassa** [comment]
I didn't tested it yet, but I tried it on some other tests, and it safed a lot of time. Nevertheless manual refactoring is still required and recommended. 

I can test it in the next days and let you know.

**Comment by polybassa** [comment]
@guedou 
Here is your test as pytest. Most was generated by my script ```./test/run_tests -t test/scapy/layers/dhcp6.uts -p > test/scapy/layers/test_dhcp6.py```. I had to add asserts manually and applied a reformatting. 

[0001-Pytest-for-layer-dhcp6.patch.zip](https://github.com/secdev/scapy/files/5270165/0001-Pytest-for-layer-dhcp6.patch.zip)

**Comment by guedou** [comment]
Can it be merged?

**Comment by polybassa** [comment]
What's the plan with pytest? Can we also move forward on that?

**Pull request merged**
