### PR TITLE
Fix/document xUnit output support in UTscapy

### LINKED ISSUE #3330: [UTscapy] xunit output format is undocumented and broken
### Brief description

The code for 'xunit' output format is present in UTscapy but is not documented in '--help' output and is broken under py3.

### Scapy version

2.4.5

### Python version

3.9

### Operating system

Ubuntu 21.04

### Additional environment information

GNU/Linux, scapy installed via pip3.

### How to reproduce

python3 -m scapy.tools.UTscapy -c test.utsc -f xunit -o utscapy.xml -N
python3 -m scapy.tools.UTscapy -h

### Actual result

...
output += ' <testcase classname="%s"\n' % testset.name.encode("string_escape").replace('"', ' ')  # noqa: E501
LookupError: unknown encoding: string_escape

### Expected result

...
✓ All campaigns executed. Writing output...
UTscapy ended successfully

### Related resources

The string_escape encoder is absent in python 3 because the strings are always utf. Simply dropping the .encode() call fixes it. It would still be nice to get the supported format properly documented though.

### PR DESCRIPTION
**Pull request by zabbal**
**Checklist:**

-   [x] If you are new to Scapy: I have checked [CONTRIBUTING.md](https://github.com/secdev/scapy/blob/master/CONTRIBUTING.md) (esp. section submitting-pull-requests)
-   [x] I squashed commits belonging together
-   [x] I added unit tests or explained why they are not relevant
-   [ ] I executed the regression tests for Python2 and Python3 (using `tox` or, `cd test && ./run_tests_py2, cd test && ./run_tests_py3`)
-   [ ] If the PR is still not finished, please create a [Draft Pull Request](https://github.blog/2019-02-14-introducing-draft-pull-requests/)

Document xUnit output support in UTscapy. Make sure it actually works with python 3.

fixes #3330

### CODE REVIEW

**Comment by zabbal** [comment]
Don't have access to macos - feel free to update PR to fix it.

**Review by guedou — APPROVED** [review]
Thanks for this PR!

**Comment by zabbal** [comment]
Glad to be of help - even a little bit. No idea why it's failing on macos though - changes in this PR have nothing to do with p0f :-/

**Comment by guedou** [comment]
I re-started the tests and everything is OK now =)

**Pull request merged**
