### PR TITLE
Fix ./run_scapy unit test

### PR DESCRIPTION
**Pull request by guedou**
This PR investigates the issue from #2554

### CODE REVIEW

**Comment by gpotter2** [comment]
Seems to have fixed it

**Comment by polybassa** [comment]
Fixes #2554

This comment tries to force github to link the issue to the PR

**Comment by gpotter2** [comment]
Still happening and very weird
```
  py38-isotp_kernel_module: commands succeeded
  codecov: commands succeeded
  congratulations :)
DEBUG: TEMPFILE=/tmp/tmp.BdeI263XGj
ERROR: Too many parameters : [/tmp/tmp.BdeI263XGj]
The command "bash .config/ci/test.sh" exited with 1.
cache.2
store build cache
```

**Comment by guedou** [comment]
The last commit gave the following error (the second list is `argv`):
```
DEBUG: TEMPFILE=/tmp/tmp.AiSY2vb0V3
ERROR: Too many parameters : [/tmp/tmp.AiSY2vb0V3] ['/home/runner/work/scapy/scapy/scapy/__main__.py', '/tmp/tmp.AiSY2vb0V3']
```

Luckily, this also triggers the issue locally:
```
./run_scapy -H -c /tmp/tmp.AiSY2vb0V3
ERROR: Too many parameters : [/tmp/tmp.AiSY2vb0V3] ['/Users/guedou/Projects/Scapy/scapy-issues.git/scapy/__main__.py', '/tmp/tmp.AiSY2vb0V3']
```

**Comment by gpotter2** [comment]
If you're sure this is stable then it LGTM.

**Comment by guedou** [comment]
@p-l- @gpotter2 can this PR be merged?

**Pull request merged**
