### PR TITLE
Remove gsm_um

### PR DESCRIPTION
**Pull request by gpotter2**
**Edited**

This PR deletes the gsm_um module

### Why this module is bad:
- it has no bindings and uses weird functions to create packets
- it cannot dissect packets
- it has no tests
- it includes links to a website that is down
- it would need a lot of time to fix it
- **It makes the code quality of the project goes down by a lot**
### Why its good:
- there are tutorials on the internet that uses it
- it achieves a unique thing

==> Best option (as discussed with @guedou) is to delete it from scapy's codebase, and move it to the Wiki.
https://github.com/secdev/scapy/wiki/%5BLegacy%5D-Contrib:-gsm_um

Whats your mind about it ?

### CODE REVIEW

**Comment by guedou** [comment]
We don't use the WIKI that much but this is a perfect example of something that could be in it. What do you think?

**Comment by gpotter2** [comment]
Not sure I understood what you meant :/
What should I put on the Wiki? The above message, the "TODO" or the module?

**Comment by guedou** [comment]
I meant: put the module and the TODO in the WIKI and close the PR as it seems that you don’t believe the module is working.

**Comment by gpotter2** [comment]
@guedou Here's a new thing: I've moved the module and its todo to 
https://github.com/secdev/scapy/wiki/%5BLegacy%5D-Contrib:-gsm_um
And here is a removal PR

**Comment by guedou** [comment]
Thanks. I slightly rewrote some lines of the WIKI.

**Pull request merged**
