### PR TITLE
Add MACsec support

### PR DESCRIPTION
**Pull request by qsn**
These commits add MACsec ([IEEE 802.1AE](https://standards.ieee.org/getieee802/download/802.1AE-2006.pdf)) support, along with some tests.

This allows creating MACsec secure associations (SA), and encapsulate/encrypt/decrypt/decapsulate packets using an SA.

### CODE REVIEW

**Comment by plorinquer** [comment]
Hello,

Thanks for this contribution !

Could you use the `MACsecSCI` Packet instead of an `XLongField` for the `sci` field?

`ConditionalField(PacketField("sci", None, MACsecSCI), lambda pkt: pkt.SC)`
instead of
`ConditionalField(XLongField("sci", 0), lambda pkt: pkt.SC)`

(`MACsecSCI` is defined in `l2.py` as well)

Then, some tests provided in the `macsec.uts` file will need to be updated.

@guedou I had a quick look at this PR, and everything looks good !

**Comment by qsn** [comment]
Thanks for the review!

I pushed a few commits on top to make it easier to review, though I think it would be nicer to squash them before merging. Let me know how you want to handle that (and the conflict with commit 025621b7c658).

**Comment by gpotter2** [comment]
@qsn Hey could you fix the conflicts ?
Moreover, on github, you could rebase your own commits :)
- `git rebase -i HEAD~6` (then replace `pick` by `fixup`)
- `git push -f`

**Comment by qsn** [comment]
I rebased locally, but now I've got a circular dependency (scapy.layers.l2 imports scapy.layers.eap.MACsecSCI, scapy.layers.eap imports some stuff from l2). Apparently there should be a way to use simple imports (instead of from foo import bar), but I can't make that work.

The easy fix would be to move MACsecSCI back to scapy.layers.l2. Or I could put the new macsec code in a separate file (it just seems a bit strange to have vlan in l2 and macsec separate). Any preference?

**Comment by guedou** [comment]
Thanks for this useful PR !

We recently moved PR #714 refactored l2.py and eap.py. You have several choices here:
- move your code to scapy/contrib/macsec.py
- move your code into scapy/eap.py

The first choice is my favorite. Let me know if you don't manage to make it work.

**Comment by guedou** [comment]
@qsn sorry for the delay. We did not see your changes until yesterday =/
Thanks a lot for your awesome work !

Pr #822 improves it by disabling the tests with pypy, and adapting it to make it Python3 compatible.

**Pull request closed without merging**
