### PR TITLE
Switch Linux Travis test to tox

### PR DESCRIPTION
**Pull request by guedou**
Attempt at replacing the current Travis tests with tox. The ultimate goal is to test locally as done on Travis.

I had to remove Python3.3 support due to a bug with distutils that I could not fix.

### CODE REVIEW

**Comment by guedou** [comment]
@p-l- I think that we can merge this before v2.4.0. It is really convenient as we only need to type `tox` on our systems to run Scapy unit tests with the available Python interpreters. Much easier than the current system that makes our local tests different from the Travis ones.

**Comment by gpotter2** [comment]
I’ll try to mimic this PR on Windows when it gets merged

**Comment by p-l-** [comment]
Maybe we can have at least one release with 3.3 support?

**Comment by guedou** [comment]
We could but as this PR is removed 3.3 won’t be tested. 

I am fine with keeping 3.3 for v2.4.0, but I think that it it a bit strange to stop supporting it right away. More however the pypi badge will display 3.3 support.

**Comment by p-l-** [comment]
I think it is better to have at least one release with compatible with Python 3.3, so that if you have a box with this version installed, you have a version of Scapy you know you can use.

**Comment by guedou** [comment]
I don't agree, but I will leave the final decision to you =)

As soon as this PR is merged, we will stop supporting 3.3 right away which is a bit strange.

**Comment by karpierz** [comment]
FYI: Recent releases of  'cryptography' (from which scapy tsl/ssl depends) do not support Py3.3
https://pypi.python.org/pypi/cryptography/2.1
https://pypi.python.org/pypi/cryptography/2.2

**Pull request merged**
