### PR TITLE
Stop processing a pcapng file when a block is malformed

### LINKED ISSUE #2787: struct.error when opening malformed pcap
#### Brief description

Scapy crashes when opening a malformed pcap file.

#### Environment

-   Scapy version: scapy-2.4.4rc2.dev38
-   Python version: 3.8
-   Operating System: Debian

#### How to reproduce

```python
$ cat test.py 
import sys
import scapy
import scapy.utils

scapy.utils.rdpcap(sys.argv[1])

$ python3 test.py ./clusterfuzz-testcase-minimized-fuzz_scapy-5720462057013248 
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    scapy.utils.rdpcap(sys.argv[1])
  File "/home/user/ven/lib/python3.8/site-packages/scapy/utils.py", line 951, in rdpcap
    return fdesc.read_all(count=count)
  File "/home/user/ven/lib/python3.8/site-packages/scapy/utils.py", line 1343, in read_all
    res = RawPcapNgReader.read_all(self, count)
  File "/home/user/ven/lib/python3.8/site-packages/scapy/utils.py", line 1093, in read_all
    p = self.read_packet()
  File "/home/user/ven/lib/python3.8/site-packages/scapy/utils.py", line 1322, in read_packet
    rp = super(PcapNgReader, self).read_packet(size=size)
  File "/home/user/ven/lib/python3.8/site-packages/scapy/utils.py", line 1239, in read_packet
    res = self.blocktypes.get(blocktype,
  File "/home/user/ven/lib/python3.8/site-packages/scapy/utils.py", line 1269, in read_block_idb
    self.interfaces.append(struct.unpack(self.endian + "HxxI", block[:8]) +
struct.error: unpack requires a buffer of 8 bytes
```

#### Actual result

```python
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    scapy.utils.rdpcap(sys.argv[1])
  File "/home/user/ven/lib/python3.8/site-packages/scapy/utils.py", line 951, in rdpcap
    return fdesc.read_all(count=count)
  File "/home/user/ven/lib/python3.8/site-packages/scapy/utils.py", line 1343, in read_all
    res = RawPcapNgReader.read_all(self, count)
  File "/home/user/ven/lib/python3.8/site-packages/scapy/utils.py", line 1093, in read_all
    p = self.read_packet()
  File "/home/user/ven/lib/python3.8/site-packages/scapy/utils.py", line 1322, in read_packet
    rp = super(PcapNgReader, self).read_packet(size=size)
  File "/home/user/ven/lib/python3.8/site-packages/scapy/utils.py", line 1239, in read_packet
    res = self.blocktypes.get(blocktype,
  File "/home/user/ven/lib/python3.8/site-packages/scapy/utils.py", line 1269, in read_block_idb
    self.interfaces.append(struct.unpack(self.endian + "HxxI", block[:8]) +
struct.error: unpack requires a buffer of 8 bytes
```
#### Expected result

Not a crash

#### Related resources

[clusterfuzz-testcase-minimized-fuzz_scapy-5720462057013248.tar.gz](https://github.com/secdev/scapy/files/5149957/clusterfuzz-testcase-minimized-fuzz_scapy-5720462057013248.tar.gz)

### PR DESCRIPTION
**Pull request by guedou**
This PR fixes #2787

### CODE REVIEW

**Comment by guedou** [comment]
@p-l- can you have a look? If merged quickly, I will proceed with the release of v2.4.4

**Comment by gpotter2** [comment]
looks like brotli broke on python 2.7. Unrelated

**Review by gpotter2 — APPROVED** [review]

**Review by p-l- — APPROVED** [review]

**Comment by p-l-** [comment]
I have re-launched the failed appveyor test.

**Comment by p-l-** [comment]
The failing test (Python 2.7 / Win64) is related to dependencies installation. So I'll merge this PR anyway.

**Pull request merged**
