### PR TITLE
Switch from PyCrypto to Cryptography

### PR DESCRIPTION
**Pull request by ThomasFaivre**
This commit series addresses issue #243 

Add more unit tests to the IPsec layer

This changes impacts the following layers:
- IPsec
- TLS
- Dot11

Notes:
- Fix the WEP key in regression.uts: Should be a 40 bits key (5 ASCII) and 24 bits nonce for 64 bits. The key was 8 ASCII => 88 bits in total
- AES-GCM and AES-CMAC algorithms are now native in cryptography: add tests in ipsec.uts
- cryptography only supports Python 2.6+
- Fix the docstring for the pad method

Removed:
- MD2 and MD4 hash algorithms for RSA in tls/crypto/pkcs1.py
- AES-XCBC-96 not supported by cryptography.

### CODE REVIEW

**Comment by Motsah** [comment]
Hi there,

So as you can see, there are some issues with the Travis build... This issues come from the installation of cryptography in some configurations:

* Pypy: cryptography requires Pypy 2.6+ I couldn't find any indication of the supported version of Pypy in Scapy, so is it possible to upgrade the Pypy version used by Travis?
* OS X: pip tries to build cryptography but the libffi is missing. There is two solutions here:
  + Use the wheel package of cryptography available for OS X, but this requires upgrading pip to at least pip 8 to have the wheel support.
  + Meet the requirements to build cryptography by following the instruction in the [documentation](https://cryptography.io/en/latest/installation/#building-cryptography-on-os-x)

What do you think should be done?

**Comment by p-l-** [comment]
I close this PR for now since Scapy is compatible with Python 2.5. Once we have dropped support for Python 2.5, this change will be considered again. Thanks a lot for this.

**Comment by robin-jarry** [comment]
Hi @p-l-, I understand there is no rush to merge this, but why didn't you leave the PR open?

**Comment by p-l-** [comment]
To prevent "accidental" merge, and to let people know it was not going to land in a close future. This does not prevent discussions & updates here, unless I'm wrong?

**Comment by robin-jarry** [comment]
Ah ok, I see :)

No, it does not prevent discussions nor updates.

**Pull request closed without merging**
