### PR TITLE
fix incorrect parse with SRv6 header

### LINKED ISSUE #1634: Incorrect parse with SRv6 header.
### Issue
Trying to catch the packets with SRv6 header using sniff command, the last element of the segment-list( [ IPv6 Option Header Segment Routing ].addresses ) is misidentified as [ IPv6 Option Header Segment Routing - Generic TLV ].

### Brief description
Capturing a packet with SRv6 header, the last element of the addresses is misidentified as tlv_objects.

for example;
a SRv6 packet with addresses [ fd80:cafe:4444::9999, fd80:face:c::1, fd80:face:b::1, fd80:face:a::1 ] is misidentified like this.
```
        addresses = [ fd80:cafe:4444::9999, fd80:face:c::1, fd80:face:b::1 ]
        \tlv_objects\
         |###[ IPv6 Option Header Segment Routing - Generic TLV ]### 
         |  type      = 253
         |  len       = 128
         |  reserved  = 250
         |  flags     = 206
         |  value     = '\x00\n\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01'
```

It must be identified like this.
```
        addresses = [ fd80:cafe:4444::9999, fd80:face:c::1, fd80:face:b::1, fd80:face:a::1 ]
        \tlv_objects\
```

Scapy version: 2.4
Python version: 3.5.2
Operating System: Ubuntu 16.04 LTS

### How to reproduce
Send packet with SRv6 header (change IP according to your own environment)
(with Linux Kernel 4.10 or higher, iproute2-4.10 or higher.)
```
$ sudo ip -6 route add fd80:cafe:4444::9999/128 dev enp0s9 encap seg6 mode inline segs fd80:face:a::1,fd80:face:b::1,fd80:face:c::1
$ ping6 fd80:cafe:4444::9999
```

Capture the packet at same machine(change Interface according to your own environment)
```
def proc_packet(packet):
    print(packet.show())

sniff(filter="ip6", iface="enp0s9", prn=proc_packet)
```

Then you will get like below.
```
###[ Ethernet ]### 
  dst       = XX:XX:XX:XX:XX:XX
  src       = XX:XX:XX:XX:XX:XX
  type      = 0x86dd
###[ IPv6 ]### 
     version   = 6
     tc        = 0
     fl        = 625396
     plen      = 136
     nh        = Routing Header
     hlim      = 64
     src       = fd80:cafe:1111::9999
     dst       = fd80:face:a::1
###[ IPv6 Option Header Segment Routing ]### 
        nh        = ICMPv6
        len       = 8
        type      = 4
        segleft   = 3
        lastentry = 3
        unused1   = 0
        protected = 0
        oam       = 0
        alert     = 0
        hmac      = 0
        unused2   = 0
        tag       = 0
        addresses = [ fd80:cafe:4444::9999, fd80:face:c::1, fd80:face:b::1 ]
        \tlv_objects\
         |###[ IPv6 Option Header Segment Routing - Generic TLV ]### 
         |  type      = 253
         |  len       = 128
         |  reserved  = 250
         |  flags     = 206
         |  value     = '\x00\n\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01'
###[ ICMPv6 Echo Request ]### 
           type      = Echo Request
           code      = 0
           cksum     = 0xc4e4
           id        = 0x55e4
           seq       = 0xa
           data      = 'sG\xbc[\x00\x00\x00\x00S\xb4\t\x00\x00\x00\x00\x00\x10\x11\x12\x13\x14\x15\x16\x17\x18\x19\x1a\x1b\x1c\x1d\x1e\x1f !"#$%&\'()*+,-./01234567'
```

### PR DESCRIPTION
**Pull request by KotaroFurukawa**
fixes #1634

### CODE REVIEW

**Comment by guedou** [comment]
Thnaks for your PR.

I have two remarks:
- do not use `noqa` comments but format your code to make flake8 happy
- modify the regression tests in `test/regression.uts`. You can easily test everythin locally with `tox`.

**Comment by guedou** [comment]
I had a look at your fix and the IETF draft. It seems that both the current code and your fix are incorrect as `lastentry` does not encode the number of addresses in the `addresses` field but an offset.
Are you familiar enough with Segment Routing to fix this?

**Comment by jadinm** [comment]
@guedou Why do you think the fix is incorrect ?

The draft states that 
> Last Entry: contains the index (zero based), in the Segment List, of the last element of the Segment List.

This means that the number of elements in the list (hence the number of addresses) of the Segment Routing Header is `Last Entry + 1` and it will always be the case. At every stage of the packet forwading, `Last Entry + 1` always stays equal to the number of addresses in the header.

Of course, the [tests](https://github.com/secdev/scapy/blob/master/test/regression.uts#L1947) should be updated as well but the fix itself looks correct to me.

**Comment by jadinm** [comment]
Oh, maybe you meant this [line](https://github.com/secdev/scapy/blob/master/scapy/layers/inet6.py#L1011) ?
`pkt = pkt[:4] + struct.pack("B", len(self.addresses)) + pkt[5:]`

This line should be updated like this, I guess
```
if len(self.addresses) == 0:
    raise <some exception>
pkt = pkt[:4] + struct.pack("B", len(self.addresses) - 1) + pkt[5:]
```

**Comment by guedou** [comment]
@jadinm thanks for the clarification. That is a really confusing description of a list length! If I understand it correctly, the `addresses` list can never be empty. Is it correct?

**Comment by jadinm** [comment]
@guedou Yes, I agree ^^
That's correct. The list of addresses cannot be empty because the first item of the list is always the final destination of the IPv6 packet.

**Comment by guedou** [comment]
I updated the content of this PR in #1785 

@jadinm can you have a look at it?

**Pull request closed without merging**
