### PR TITLE
Add progress estimation to Automotive_Scanners

### PR DESCRIPTION
**Pull request by polybassa**

### CODE REVIEW

**Comment by polybassa** [comment]
retrigger build because of this error:
```
Run codecov/codecov-action@v2
==> macos OS detected
Error: certificate has expired
    at TLSSocket.onConnectSecure (_tls_wrap.js:1502:34)
    at TLSSocket.emit (events.js:314:20)
    at TLSSocket._finishInit (_tls_wrap.js:937:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:7[11](https://github.com/secdev/scapy/runs/7434990253?check_suite_focus=true#step:6:12):[12](https://github.com/secdev/scapy/runs/7434990253?check_suite_focus=true#step:6:13))
```

**Comment by polybassa** [comment]
This broken build should be fixed by #3702

**Comment by polybassa** [comment]
retrigger build for osx ci results

**Comment by polybassa** [comment]
@gpotter2 Can this PR get merged please?

**Comment by gpotter2** [comment]
Conflicting

**Comment by gpotter2** [comment]
Conflicting

**Comment by polybassa** [comment]
Resolved

**Review by gpotter2 — APPROVED** [review]

**Pull request merged**
