### PR TITLE
fix issue 4206

### PR DESCRIPTION
**Pull request by T3pp31**
**Checklist:**

-   [x] If you are new to Scapy: I have checked [CONTRIBUTING.md](https://github.com/secdev/scapy/blob/master/CONTRIBUTING.md) (esp. section submitting-pull-requests)
-   [x] I squashed commits belonging together
-   [x] I added unit tests or explained why they are not relevant
-   [x] I executed the regression tests (using `cd test && ./run_tests` or `tox`)
-   [x] If the PR is still not finished, please create a [Draft Pull Request](https://github.blog/2019-02-14-introducing-draft-pull-requests/)

Issues 4206, Typo was noted and i fixed it.

I don't know the details, but since it's just a name change, it seems to me that there should be no problem.
fixes #xxx 
[4206](https://github.com/secdev/scapy/issues/4206)

### CODE REVIEW

**Comment by polybassa** [comment]
Please remove your duplicated imports and minimize your changes in this PR!

**Comment by T3pp31** [comment]
i always use 'isort' and 'black'.
i need to off these?

**Comment by polybassa** [comment]
Yes please, keep your changes at a minimum

--
Mit freundlichen Grüßen

Dr. Nils Weiß

dissecto GmbH
Franz-Mayer-Str. 1
93053 Regensburg
________________________________

**Comment by T3pp31** [comment]
I disabled isort and black because the differences were too large when using them.

**Review by polybassa — APPROVED** [review]

**Pull request merged**
