### PR TITLE
F403 - 'from module import *' used; unable to detect undefined names

### PR DESCRIPTION
**Pull request by guedou**
PEPin project almost over!

I don't know how to provide a better fix than that =/

### CODE REVIEW

**Comment by gpotter2** [comment]
For the all* files, I think it’s legitimate to use

http://flake8.pycqa.org/en/3.0.4/user/ignoring-errors.html#ignoring-entire-files

Knowingly:
```
# flake8: noqa: F403
```
somewhere at the top of the file

**Comment by guedou** [comment]
Thanks! I was too lazy to check the documentation.

**Comment by gpotter2** [comment]
I would also use the trick on `arch/__init__` because it acts like a .all

Otherwise good to me

**Comment by guedou** [comment]
I did not do it because it do not like the way it is done today =)

I would like to implement an Architecture object that will clearly define mandatory methods such as getifaddr()

**Pull request merged**
