### PR TITLE
Add previous_msg field to ACK & NACK + expand tests

### PR DESCRIPTION
**Pull request by KhazAkar**
This PR adds an optional field to Diag Message ACK & NACK, called previous message, in code called previous_msg. In Wireshark it looks like this:
Screenshot from 2022-02-10 22-29-27
Screenshot from 2022-02-10 22-29-52
But in scapy, before this PR, it looks like that:
Screenshot from 2022-02-10 22-30-24

### CODE REVIEW

**Comment by polydroi** [comment]
Thanks for this PR, could you please also add a dissect test.

**Comment by KhazAkar** [comment]
> Thanks for this PR, could you please also add a dissect test.

I will, I just need to prepare specific pcapng for that, which won't contain specific MAC Address etc. :)

**Comment by KhazAkar** [comment]
Since tests passed, can @gpotter2 or other maintainer take a look at code in spare time, please? :)

**Review by gpotter2 — APPROVED** [review]
@polybassa Your call

**Comment by polybassa** [comment]
LGTM
-- 
Viele Grüße

Nils Weiß

On February 15, 2022 9:53:11 AM GMT+01:00, gpotter2 ***@***.***> wrote:
***@***.*** approved this pull request.
>
***@***.*** Your call

**Pull request merged**
