### PR TITLE
Add missing space in a message

### PR DESCRIPTION
**Pull request by tomaxuser**
This PR fixes formatting of an exception message.

### CODE REVIEW

**Comment by gpotter2** [comment]
Just wondering, did you actually encounter this error?

**Comment by tomaxuser** [comment]
Sure, you can reproduce it e.g. with this: `sr1(IP(dst="8.8.8.8")/UDP()/DNS(rd=1,qd=DNSQR("www.google.com")))`

**Comment by gpotter2** [comment]
You're actually missing `qname=` in
`DNSQR(qname="www.google.com")`

**Comment by tomaxuser** [comment]
Oh, you are right. I am just learning Scapy and when I noticed this, I tried to provide a fix, and haven't tried to fix the expression yet. :-) Thank you anyway.

**Pull request merged**
