### PR TITLE
chore : Fixed code quality issues

### PR DESCRIPTION
**Pull request by ankitdobhal**
## Description

Hi 👋 I ran the [DeepSource](https://deepsource.io/) static analyzer on the forked copy of this repo and found some [interesting code quality issues](https://deepsource.io/gh/ankitdobhal/scapy/issues/). This PR fixes a few of them.

## Summary of Fixes

- Remove unnecessary use of comprehension
- Merge `isinstance` calls
- Replace ternary syntax with if expression
- Use `sys.exit()` calls
- Consider merging these comparisons with in
- Added .deepsource.toml to fix bug risk

## Type of change

- [✔] Antipattern
- [ ] New feature (non-breaking change which adds functionality)

## Checklist:

- [✔] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by polybassa** [comment]
Thanks for this cleanup!

**Comment by guedou** [comment]
Thanks for your interest in Scapy. Instead of a single commits fixing all issues at once, could you do a commit per issue. That will ease reviewing and make the commit history clearer.

**Comment by ankitdobhal** [comment]
> Thanks for your interest in Scapy. Instead of a single commits fixing all issues at once, could you do a commit per issue. That will ease reviewing and make the commit history clearer.

Sure @guedou .
But some tests are failing in PR. Can you help me out to resolve them?
Thanks in advance

**Comment by ankitdobhal** [comment]
> Thanks for your interest in Scapy. Instead of a single commits fixing all issues at once, could you do a commit per issue. That will ease reviewing and make the commit history clearer.

@guedou to make things clear I have created new PR #3111 as per your suggestion.
KIndly checkout this PR #3111 .
@guedou @polybassa

**Pull request closed without merging**
