### PR TITLE
Matplotlib support

### PR DESCRIPTION
**Pull request by guedou**
Hi,

Here is a modified version of the PR submitted on bitbucket. It aims to replace the dependency on gnuplot-py with maplotlib.

The main focus was on compatibility. Therefore, most of the time, old plot() commands will seamlessly work with this PR. Moreover, Scapy can now be used in IPython notebooks: plots are inlined.

Besides the documentation that still refers to gnuplot, there is still one call to gnuplot in TracerouteResult.world_trace() which is broken since 2008, according to git blame (that is issue #28). 

Guillaume

### CODE REVIEW

**Comment by p-l-** [comment]
Great work!

Unless I'm wrong, `.multiplot()` behavior has changed: before, the expected result of the function was a two-element list/tuple (label, value), now it is (label, (xvalue, yvalue)).

While it is great to have the ability to specify the xvalue as well as the yvalue, it would be nice to get the previous behavior by default?

Also, the (xvalue, yvalue) plots could be made available for `.plot()`?

Also, I don't get the caption with matplotlib and the dot are the same color, while the gnuplot code diplays a caption and uses different colors (see screenshots).

Current code (using Gnuplot), using `ans.multiplot(lambda x: [x[1][IP].src, x[1][IP].id])`
scapy-multiplot-gnuplot

This code (using Matplotlib), using `ans.multiplot(lambda x: [x[1][IP].src, [x[1].time, x[1][IP].id]])`
scapy-multiplot-matplotlib

**Comment by guedou** [comment]
The old behavior, that I tried to mimic, is shown at slide 48 in http://www.secdev.org/conf/scapy-IPv6_HITB06.pdf
The multiplot() method takes a list of (label, (xvalue, yvalue)).

**Comment by p-l-** [comment]
OK so the behavior of `.multiplot()` has changed since that (current code seems to work more like `.plot()`).

Anyway as I said I think it would be good to have the two possibilities, for `.multiplot()` and for `.plot()`.

I'm merging this one and preparing another PR to offer these possibilities.

**Comment by techtonik** [comment]
[GitHub can render IPython notebooks](https://github.com/blog/1995-github-jupyter-notebooks-3), so are there any examples of which graphs can be drawn with Scapy?

**Comment by p-l-** [comment]
@techtonik that's something @guedou had in mind with this PR ;-)

**Comment by techtonik** [comment]
Cool. Looking forward to see them soon. =)

**Comment by p-l-** [comment]
@techtonik have a look at PR #30, which contains [an example](https://github.com/p-l-/scapy/blob/feature-plot-xy/doc/notebooks/graphs-ipids.ipynb).

**Comment by techtonik** [comment]
Yes. Awesome. =)

**Pull request merged**
