### PR TITLE
Check C errno

### PR DESCRIPTION
**Pull request by wataash**
**Checklist:**

-   [x] If you are new to Scapy: I have checked [CONTRIBUTING.md](https://github.com/secdev/scapy/blob/master/CONTRIBUTING.md) (esp. section submitting-pull-requests)
-   [x] I squashed commits belonging together
-   [ ] I added unit tests or explained why they are not relevant
-   [ ] I executed the regression tests for Python2 and Python3 (using `tox` or, `cd test && ./run_tests_py2, cd test && ./run_tests_py3`)
-   [x] If the PR is still not finished, please create a [Draft Pull Request](https://github.blog/2019-02-14-introducing-draft-pull-requests/)

---

I think checking C `errno` will prevent hard-to-debug crashes such like #2422.

If you maintainers are positive on it, I'll work on TODOs below:

- Tests
- Apply to all files where `ctypes.CDLL` is used
  - Move this patch from winpcapy.py to a new file
- Try wrapping `ctypes.CDLL` rather than wrapping all C functions
- Take the responsibility of checking and dumping `errbuf` in winpcapy.py

---

fixes #xxx

### CODE REVIEW

**Comment by gpotter2** [comment]
I don't see the point of this PR.
We use those calls correctly, they're not intended for end users, so there's no need to catch and parse exceptions.

**Comment by wataash** [comment]
Thanks for reviewing @gpotter2.

The purposes of this PR are two:

1. Prevent ignoring errors
2. Show user-friendly error messages

Unlike most of Python functions, C functions fail silently. If error was ignored, it may causes another unexpected error on a later stage, which is often hard-to-debug such like #2422. So I wanted C functions to raise exceptions immediately on `errno` set (or on -1 returned for some functions) and tell user what went wrong (`Operation not permitted`, `Device not configured`, ...). The error message can be made even more user-friendly by catching exceptions, as I did in #2422 (`Could not open iface eth0: Operation not permitted (needs sudo?)`).

To me, there seemed to be some functions not handling error (e.g. pcap_set_promisc), but now I understand they probably intendedly ignore errors. So now the main purpose is 2.

Suggesting me any other way would be appreciated.

**Comment by wataash** [comment]
Maybe this PR doesn't conform to the project style... so let me close this.
Thanks!

**Comment by gpotter2** [comment]
Thanks a lot for your investment on this PR. There was indeed an issue (when it used to crash with segmentation faults).
However I'm not sure if the extra level of complexity would have really helped: a user of scapy isn't supposed to see our calls to libpcap fail.

This PR is super useful for debugging, but I prefer to keep the file simple.
Thanks for your work & Gabe a great day

**Pull request closed without merging**
