### PR TITLE
Fix error handling for pcap_create() and pcap_activate().

### PR DESCRIPTION
**Pull request by guyharris**
This 1) handles pcap_create() failing and 2) provides a useful error message if pcap_activate() fails.

### CODE REVIEW

**Comment by guedou** [comment]
Thanks for this PR. Could you provide us a little more context to help us review it? I would like to know more about what this PR is fixing and how it could be tested in CI.

**Review by gpotter2 — DISMISSED** [review]
Thanks a lot for the PR !
That'll help a lot understand failures

**Comment by guyharris** [comment]
> I would like to know more about what this PR is fixing

It fixes two issues:

1. `pcap_create()` is not guaranteed to succeed, so assuming that it returns a non-null pointer can cause the Python interpreter to crash.  In particular, in macOS, `pcap_create()` on a pktap device such as the "any" device involves more than just allocating memory - it attempts to set up pktap plumbing, which requires root privileges, so, if you do `pcap_create("any", errbuf)` when not running as root, `pcap_create()` returns `NULL` and fills in `errbuf` with "ioctl(SIOCIFCREATE): Operation not permitted".
2. If an attempt to open an interface in monitor mode fails, the error message just says "Could not activate the pcap handler"; it doesn't report why it didn't work.  That makes it difficult to determine what the problem is, making it impossible to figure out what the problem would be in the failure case mentioned in [this StackOverflow answer](https://stackoverflow.com/a/74329936/).  The suggestion they made in that answer was to print out the return value of `pcap_activate()`; unfortunately, they didn't also suggest that, for some return values, the string returned by `pcap_geterr()` is also needed - that's very much the case for `PCAP_ERROR`, which is a generic error returned for a number of "should not happen" failures, and that string is necessary to determine which particular failure that was.  That is, in fact, what happened in [a later question](https://stackoverflow.com/questions/74336825/sniffing-network-traffic-with-scapy-get-could-not-activate-the-pcap-handler) asked by the person who asked the first question.  They also filed the-tcpdump-group/libpcap#1136; unfortunately, given that the error they were getting is `PCAP_ERROR`, we have no clue why the error is occurring or if there's anything they can do to fix it.

> and how it could be tested in CI

The fix for the first problem can be tested by running on macOS, *without* root privileges, and trying to open the "any" device".

The fix for the second problem can be tested by attempting to open a device in monitor mode on most OSes, *without* root privileges.  The error should report that permission was denied.

**Comment by guyharris** [comment]
WinPcap 4.1.3 has `pcap_statustostr()`, so I'm not sure why [one of the Appveyor builds](https://ci.appveyor.com/project/secdev/scapy/builds/45438417/job/jb9a5icwdvetmat1) is failing.

**Review by guedou — APPROVED** [review]
Thanks a lot!

**Comment by gpotter2** [comment]
I'm gonna have a look at what's happening with Winpcap.

**Review by gpotter2 — APPROVED** [review]

**Pull request merged**
