### PR TITLE
Fix bugs found with python-afl in IPv6 and ASN1 BER

### PR DESCRIPTION
**Pull request by ppietikainen**

### CODE REVIEW

**Comment by p-l-** [comment]
Hi,

It seems that this breaks an SNMP test

```Python
>>> x=SNMP('0y\x02\x01\x00\x04\x06public\xa2l\x02\x01)\x02\x01\x00\x02\x01\x000a0!\x06\x12+\x06\x01\x04\x01\x81}\x08@\x04\x02\x01\x07\n\x86\xde\xb78\x04\x0b172.31.19.20#\x06\x12+\x06\x01\x04\x01\x81}\x08@\x04\x02\x01\x07\n\x86\xde\xb76\x04\r255.255.255.00\x17\x06\x12+\x06\x01\x04\x01\x81}\x08@\x04\x02\x01\x05\n\x86\xde\xb9`\x02\x01\x01')
>>> x.show()
###[ SNMP ]### 
  version= 0x0 <ASN1_INTEGER[0L]>
  community= <ASN1_STRING['public']>
  \PDU\
   |###[ SNMPresponse ]### 
   |  id= 0x29 <ASN1_INTEGER[41L]>
   |  error= 0x0 <ASN1_INTEGER[0L]>
   |  error_index= 0x0 <ASN1_INTEGER[0L]>
   |  \varbindlist\
   |   |###[ SNMPvarbind ]### 
   |   |  oid= <ASN1_OID['.1.3.6.1.4.1.253.125.8.64.4.2.1.7.10.14130104.1547192.7096.56']>
   |   |  value= <ASN1_STRING['172.31.19.2']>
   |   |###[ SNMPvarbind ]### 
   |   |  oid= <ASN1_OID['.1.3.6.1.4.1.253.125.8.64.4.2.1.7.10.14130102.1547190.7094.54']>
   |   |  value= <ASN1_STRING['255.255.255.0']>
   |   |###[ SNMPvarbind ]### 
   |   |  oid= <ASN1_OID['.1.3.6.1.4.1.253.125.8.64.4.2.1.5.10.14130400.1547488.7392.96']>
   |   |  value= 0x1 <ASN1_INTEGER[1L]>
>>> assert(x.community=="public" and x.version == 0)
>>> assert(x.PDU.id == 41 and len(x.PDU.varbindlist) == 3)
>>> assert(x.PDU.varbindlist[0].oid == "1.3.6.1.4.1.253.8.64.4.2.1.7.10.14130104")
Traceback (most recent call last):
  File "<input>", line 2, in <module>
AssertionError
```

**Comment by ppietikainen** [comment]
Argh :-) Brute-force fix seems to leave that test unaffected (but fails e.g.
pylint --disable=all --enable=undefined-loop-variable,undefined-variable, which would have 
caught both ber.py bugs). Might be better to have that kind of check in the caller, but any edits to this kind of code are by nature very error-prone :(

**Comment by p-l-** [comment]
Thanks! Do you think it would be useful to add tests that wouldn't pass with current Scapy code and are fixed by this PR?

**Comment by ppietikainen** [comment]
Good question, they would go under "regression", but also "material for future fuzzing", and duplicating those might be a bit silly since there could be useful automation involved.

I've considered automatically using the current regression tests as samples and that could work. Basically fuzzing could report stuff directly in a suitable format, e.g.

```
#   File "/usr/lib/python2.7/site-packages/scapy/asn1/ber.py", line 99, in BER_num_dec
#     if c&0x80:
# UnboundLocalError: local variable 'c' referenced before assignment
a=ECParameters('\xff')
a=X509_RFC822Name('\xff')
```

(all with the same root cause)

and, respectively, regexp magic that matches on a=PROTO('param')  that puts '\xff' in a file in ECParameters/in/ . 

Of course, the same level of automation for say `PPP()/PPP_IPCP(options[PPP_IPCP_Option_DNS1(data="1.2.3.4"),PPP_IPCP_Option_DNS2(data="5.6.7.8"),PPP_IPCP_Option(type=123,data="ABCDEFG"),PPP_IPCP_Option_NBNS2(data="9.10.11.12")])` is a bit more tricky, but is a better starting point than PPP() for fuzzing...

**Comment by mtury** [comment]
Regarding your fix in scapy/asn1/ber.py: actually, only the decoding of invalid ASN1 strings (as '\xff') may result in passing an empty string to BER_num_dec(). I suggest replacing your
```python
if len(s) == 0:
    return x, s[1:]
```
with something like
```python
if len(s) == 0:
    raise BER_Decoding_Error("BER_num_dec: got empty string", remaining=s)
```

**Comment by guedou** [comment]
It looks good to me. Could you clean up the commits (for example using "git rebase -i" ) ? A single commit is much nicer, and ease going through the history.

**Comment by guedou** [comment]
@ppietikainen sorry for the merging delay. Would you mind fixing the conflict ?

**Comment by guedou** [comment]
Fixed move to #514

**Pull request closed without merging**
