### PR TITLE
Tests: disable debug_dissector in sniff tests

### PR DESCRIPTION
**Pull request by p-l-**
This should avoid random unrelated crashes.

### CODE REVIEW

**Comment by p-l-** [comment]
@guedou: tests are OK BTW on Travis-CI, no idea why they are seen "in progress" here.

**Comment by gpotter2** [comment]
Same with https://github.com/secdev/scapy/pull/499

**Comment by gpotter2** [comment]
@p-l- It looks like the secdev organization has removed Travis third party access.

**Comment by p-l-** [comment]
@gpotter2 no, access is OK according to that page.

**Comment by gpotter2** [comment]
Well i would recommand you to [contact the travis support](mailto:support@travis-ci.com)... Because it's a bit annoying

**Pull request merged**
