### PR TITLE
Compute the IPv4 checksum using  the IP address from a Source Routing…

### LINKED ISSUE #3074: Wrong UDP checksum when using IPv4 Source Routing options
#### Brief description

The UDP checksum is computed on a pseudo-header that does not appear to take IPv4 header options into account. I think this is a bug in `inet.in4_chksum()`, because the IP layer checksums are correct.

#### Environment

-   Scapy version: current master HEAD (e412d2f2877dbebfb8d88d90626406960dc7a559)
-   Python version: 3.7.3
-   Operating System: reproduced on Linux and macOS

#### How to reproduce

```python
# LSRR routers=[192.168.1.1]
opt = IPOption(copy_flag=1, optclass=0, option=3, length=7, value=b'\x04\xC0\xA8\x01\x01')
ip_1 = IP(dst="127.0.0.1") / UDP(sport=0, dport=5555) / b"payload"
ip_2 = IP(dst="127.0.0.1", options=opt) / UDP(sport=0, dport=5555) / b"payload"
```

Then `show2()` the IP packets. The UDP checksum on `ip_2` is computed incorrectly -- specifically, it is the same as for `ip_1`. 

#### Actual result

```python
>>> ip_1.show2()
###[ IP ]### 
  version   = 4
  ihl       = 5
  tos       = 0x0
  len       = 35
  id        = 1
  flags     = 
  frag      = 0
  ttl       = 64
  proto     = udp
  chksum    = 0x7cc7
  src       = 127.0.0.1
  dst       = 127.0.0.1
  \options   \
###[ UDP ]### 
     sport     = 0
     dport     = personal_agent
     len       = 15
     chksum    = 0x2eeb
###[ Raw ]### 
        load      = 'payload'
```

```python
>>> ip_2.show2()
###[ IP ]### 
  version   = 4
  ihl       = 7
  tos       = 0x0
  len       = 43
  id        = 1
  flags     = 
  frag      = 0
  ttl       = 64
  proto     = udp
  chksum    = 0x49f6
  src       = 127.0.0.1
  dst       = 127.0.0.1
  \options   \
   |###[ IP Option Loose Source and Record Route ]### 
   |  copy_flag = 1
   |  optclass  = control
   |  option    = loose_source_route
   |  length    = 7
   |  pointer   = 4
   |  routers   = [192.168.1.1]
   |###[ IP Option End of Options List ]### 
   |  copy_flag = 0
   |  optclass  = control
   |  option    = end_of_list
###[ UDP ]### 
     sport     = 0
     dport     = personal_agent
     len       = 15
     chksum    = 0x2eeb
###[ Raw ]### 
        load      = 'payload'
```

#### Expected result

The UDP checksums for the two packets should be different.

### PR DESCRIPTION
**Pull request by guedou**
This PR fixes #3074.

### CODE REVIEW

**Comment by jmillikin** [comment]
At commit f91fc46a0f5646cc7157e01cd16bf04237e459ed, I get the following exception when trying to send an IP packet with a source-routing option:

```python
  File "/Users/john/src/third_party/github.com/secdev/scapy/f91fc46a0f5646cc7157e01cd16bf04237e459ed/scapy/layers/inet.py", line 660, in in4_chksum
    if len_sr_options == 1 and len(sr_options[0].routers):
  File "/Users/john/src/third_party/github.com/secdev/scapy/f91fc46a0f5646cc7157e01cd16bf04237e459ed/scapy/packet.py", line 437, in __getattr__
    return self.payload.__getattr__(attr)
  File "/Users/john/src/third_party/github.com/secdev/scapy/f91fc46a0f5646cc7157e01cd16bf04237e459ed/scapy/packet.py", line 435, in __getattr__
    fld, v = self.getfield_and_val(attr)
  File "/Users/john/src/third_party/github.com/secdev/scapy/f91fc46a0f5646cc7157e01cd16bf04237e459ed/scapy/packet.py", line 1835, in getfield_and_val
    raise AttributeError(attr)
AttributeError: routers
```

Here's the contents of `sr_options[0]` in that call to `in4_checksum`:
```
(Pdb) sr_options[0]
<IPOption  copy_flag=1 optclass=control option=loose_source_route length=7 value='\x04\\xc0\\xa8\x01\x01' |>
(Pdb) len(sr_options[0])
7
(Pdb) ls(sr_options[0])
copy_flag  : BitField  (1 bit)                   = 1               ('0')
optclass   : BitEnumField                        = 0               ('0')
option     : BitEnumField                        = 3               ('0')
length     : FieldLenField                       = 7               ('None')
value      : StrLenField                         = b'\x04\xc0\xa8\x01\x01' ("b''")
```

The following patch fixes the exception, and I've verified the original test case works as expected:
```diff
diff --git a/scapy/layers/inet.py b/scapy/layers/inet.py
index 02d132ef..61a5e7cd 100644
--- a/scapy/layers/inet.py
+++ b/scapy/layers/inet.py
@@ -655,7 +655,7 @@ def in4_chksum(proto, u, p):
         ln = len(p)
 
     # Filter out IPOption_LSRR and IPOption_SSRR
-    sr_options = [opt for opt in u.options if opt.option in [3, 9]]
+    sr_options = _sourceroute_options(u)
     len_sr_options = len(sr_options)
     if len_sr_options == 1 and len(sr_options[0].routers):
         # The checksum must be computed using the final
@@ -674,6 +674,24 @@ def in4_chksum(proto, u, p):
     return checksum(psdhdr + p)
 
 
+def _sourceroute_options(ip):
+    """
+    Extracts source-routing options from an IP instance.
+    """
+    sr_options = []
+    for opt in ip.options:
+        if isinstance(opt, (IPOption_SSRR, IPOption_LSRR)):
+            sr_options.append(opt)
+            continue
+        if type(opt) != IPOption or opt.optclass != 0:
+            continue
+        if opt.option == 3:
+            sr_options.append(IPOption_LSRR(raw(opt)))
+        elif opt.option == 9:
+            sr_options.append(IPOption_SSRR(raw(opt)))
+    return sr_options
+
+
 class TCP(Packet):
     name = "TCP"
     fields_desc = [ShortEnumField("sport", 20, TCP_SERVICES),
```

**Comment by guedou** [comment]
Can you share the line that you use to create the packet? It should use IPOption_SSRR or _LSR.

**Comment by jmillikin** [comment]
> Can you share the line that you use to create the packet? It should use IPOption_SSRR or _LSR.

I used the `IPOption` constructor (see original bug report at https://github.com/secdev/scapy/issues/3074#issue-795579016):

```python
opt = IPOption(copy_flag=1, optclass=0, option=3, length=7, value=b'\x04\xC0\xA8\x01\x01')
ip = IP(dst="127.0.0.1", options=opt) / UDP(sport=0, dport=5555) / b"payload"
```

Based on blog posts I found when originally googling for [scapy ip header options], including:
* http://durst.ninja/blog/2014/3/15/scapy
* https://allievi.sssup.it/techblog/archives/631
* https://blog.x-way.org/Networking/2015/07/12/Scapy-and-IP-Options.html

plus the docs at https://scapy.readthedocs.io/en/latest/api/scapy.layers.inet.html#scapy.layers.inet.IPOption

**Comment by guedou** [comment]
I just fixed the exception. The correct way to forge such packet is:
`IP(options=[IPOption_SSRR(routers=["1.1.1.1", "8.8.8.8"])])/UDP()/Raw(load=b"Scapy"))`

**Comment by jmillikin** [comment]
Thanks, I've verified that using the more specific constructor fixes the issue for me. Both tcpdump and the Linux kernel now accept source-routed packets from scapy.

**Comment by guedou** [comment]
@gpotter2 this is finally ready to be reviewed!

**Review by gpotter2 — APPROVED** [review]

**Comment by gpotter2** [comment]
LGTM !

**Pull request merged**
