### PR TITLE
add TCP User Timeout Option (RFC 5482)

### PR DESCRIPTION
**Pull request by H1ghl4nd3r**
Allow one to send the TCP User Timeout Option described in RFC 5482 in
a crafted TCP segment.

### CODE REVIEW

**Comment by guedou** [comment]
Thanks for your patch. Could you write build & dissection unit tests in test/regression.uts ?

**Comment by H1ghl4nd3r** [comment]
Sure, what section of the regression.uts file should I put my tests in ? I looked but didn't find the TCP options section.

**Comment by guedou** [comment]
You can create a new TCP section at the end of the test/regression.uts. Two tests will be enough: one with basic build, and the other one with basic dissection (see for example https://github.com/secdev/scapy/blob/master/test/regression.uts#L4274)

**Comment by H1ghl4nd3r** [comment]
I wrote the tests in a newly created "TCP options" section as requested, is it all right for you ?

**Comment by p-l-** [comment]
Thanks @H1ghl4nd3r!

**Pull request merged**
