### PR TITLE
Update IANA Router Alert Options

### PR DESCRIPTION
**Pull request by walintonc**
Signed-off-by: Walinton Cambronero <walinton.cambronero@hpe.com>

### CODE REVIEW

**Comment by p-l-** [comment]
Looks OK to me, @guedou that's your part, up to you ;)

**Comment by guedou** [comment]
Thanks for this patch ! I am happy to see that the IPv6 support is used in Scapy.

**Comment by walintonc** [comment]
I am planning to use the MLD implementation. I see it is lacking some MLDv2 functionality. What would be the best way to upstream (if any) changes to add support for that functionality? https://github.com/secdev/scapy/blob/master/scapy/layers/inet6.py#L1116

**Comment by guedou** [comment]
The best is to follow the guidelines in https://github.com/secdev/scapy/blob/master/CONTRIBUTING.md

Then, we could interact on the issue if you have questions. When the code is ready, you could submit a PR that we will review.

**Pull request merged**
