### PR TITLE
gtp: fix GTPPDUSessionContainer layer implementation

### PR DESCRIPTION
**Pull request by raslandarawsheh**
This reflects the rfc 38415-f20 with the following
example frame format:

Bits	                Number of Octets
7  6  5  4  3  2  1  0
 Field 1  |  Field 2          1          Octet 1
 Field 3  |  Field 4          2          Octet 2
 Field 4 Cont | Spare	                 Octet 3
          Field 6             2          Octet 4
 Field 6 Cont | Padding bits             Octet 5
      Future Extension        0-m
      Padding                 0-3

Signed-off-by: Raslan Darawsheh <rasland@nvidia.com>

**Checklist:**

-   [ ] If you are new to Scapy: I have checked [CONTRIBUTING.md](https://github.com/secdev/scapy/blob/master/CONTRIBUTING.md) (esp. section submitting-pull-requests)
-   [x] I squashed commits belonging together
-   [ ] I added unit tests or explained why they are not relevant
-   [x] I executed the regression tests for Python2 and Python3 (using `tox` or, `cd test && ./run_tests_py2, cd test && ./run_tests_py3`)
-   [ ] If the PR is still not finished, please create a [Draft Pull Request](https://github.blog/2019-02-14-introducing-draft-pull-requests/)

fixes #xxx

### CODE REVIEW

**Comment by raslandarawsheh** [comment]
@guedou can you kindly check this PR? 
its fixing all issues that we discussed over gitter like following:
`
GTPPDUSessionContainer(type=4, qmp=0, QFI=17).show2()
`

there is also this kind of issue:
`len(GTPPDUSessionContainer(ExtHdrLen=1, type=0, P=1, QFI=0X3F, qmp=1))`
it will report 9 bytes of header len meanwhile from the spec it should be 4 bytes aligned

**Comment by gpotter2** [comment]
Hi & thanks for the PR.

It looks rather good, but do you think you could provide a test to check that no further regression will happen?
If you have a pcap containing a packet that reproduces this issue, it works too.

THanks !

**Comment by raslandarawsheh** [comment]
@gpotter2 I'm afraid I can't much add the test for it, 
for the pcap file I might be able to provide one, but where should it be pushed?

**Comment by gpotter2** [comment]
Could you upload it in this issue? You'll have to zip it first

**Comment by raslandarawsheh** [comment]
[pkt.zip](https://github.com/secdev/scapy/files/6278395/pkt.zip)
sure attached an example

**Review by gpotter2 — APPROVED** [review]

**Pull request merged**
