### PR TITLE
Fix wrong Modbus response code / class match (#3202)

### PR DESCRIPTION
**Pull request by JulienBedel**
This PR fixes an implementation error in Modbus contrib module, described in issue #3202.

Before :
```python
>>> from scapy.contrib.modbus import ModbusADUResponse
>>> pkt = ModbusADUResponse(b"\x00\x00\x00\x00\x00\x03\x00\x88\x01")
>>> pkt.show2()
###[ ModbusADU ]### 
  transId   = 0x0
  protoId   = 0x0
  len       = 3
  unitId    = 0x0
###[ Raw ]### 
     load      = '\x88\x01'
```

After :
```python
>>> from scapy.contrib.modbus import ModbusADUResponse
>>> pkt = ModbusADUResponse(b"\x00\x00\x00\x00\x00\x03\x00\x88\x01")
>>> pkt.show2()
###[ ModbusADU ]### 
  transId   = 0x0
  protoId   = 0x0
  len       = 3
  unitId    = 0x0
###[ Diagnostics Exception ]### 
     funcCode  = 0x88
     exceptionCode= Illegal Function Code
```

### CODE REVIEW

**Review by guedou — CHANGES_REQUESTED** [review]
Thanks for this PR.

Could you add corresponding unit tests to https://github.com/secdev/scapy/blob/master/test/contrib/modbus.uts ? You can mimic the test at https://github.com/secdev/scapy/blob/master/test/contrib/modbus.uts#L15

**Comment by JulienBedel** [comment]
Thanks for your response.

I added unit tests for every Modbus PDU payload guess types, as they where not implemented and probably caused the initial bug.
It revealed a similar issue that was fixed in the same commit.

During the tests, I also found that other aspects of the Modbus implementation required some patches, should I add them in this PR or create a new one (as it is not targeting the same issue) ?

**Comment by guedou** [comment]
I will prefer that you add the changes to a different PR. Thanks

**Comment by JulienBedel** [comment]
Thanks for your response. I added another fix on Modbus codes that was causing the tests to fail, and will add further fix in an other PR.

**Comment by gpotter2** [comment]
Thanks for the PR. Could you rebase against master?

**Review by gpotter2 — APPROVED** [review]

**Comment by JulienBedel** [comment]
> Thanks for the PR. Could you rebase against master?

Sorry, your answer got lost in my notifications. Thanks for the merge ;)

**Pull request merged**
