### PR TITLE
Select the network interface in send()

### LINKED ISSUE #2355: Interface routing issue with `send` on layer 3
I setup my UDP server by python code below.
```python
import socket

s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
s.bind(('192.168.8.104', 9999))

print('Bind UDP on 9999...')

while True:
    data, addr = s.recvfrom(1024)
    print('Received from %s ---> %s' % (addr, data.decode("utf-8")))
```
and then,I try to send UPD package by scapy.
```python
send(IP(src="192.168.8.110",dst="192.168.8.104")/UDP(dport=9999,sport=5678)/"Hello scapy udp")
```
result is `Sent 1 packets.in terminal`.But I can't see anything in my udp server logout.

and then,I try to use another way to send UPD package like this:
```python
sr1(IP(src="192.168.8.110",dst="192.168.8.104")/UDP(dport=9999,sport=5678)/"Hello scapy udp")
```
IT WORKED(I mean that i can see logout in my UDP server)!!!WHY?????Can somebody answer for me.

**I asked this question on StackOverflow.com but nobody answer for me.So,if you see this,please help me.Thank you for your waste time watch this.**

### PR DESCRIPTION
**Pull request by guedou**
This PR fixes #2355.

### CODE REVIEW

**Comment by guedou** [comment]
Ready to be reviewed!

**Comment by guedou** [comment]
Please don't merge yet. I have some doubts about this PR when multiple packets are sent.

**Comment by p-l-** [comment]
I do **not** agree with this PR.

In my mind, `send()` is supposed to use Scapy's routing table (`conf.iface`) to send layer 3 packets, while `sendp()` sends layer 2 packets using `conf.iface` (or the value for parameter `iface=`).

Specifying an interface in `send()` is weird. For instance, what layer 2 address should Scapy use to send a packet outside the LAN?

An option would be to allow specifying an alternative routing table object (or a route).

What do you think?

**Comment by guedou** [comment]
The current implementation of `sr1()` behaves the same way as this PR: try to be smart and use the routing table instead of `conf.iface`.

**Comment by p-l-** [comment]
OK I misunderstood your PR then, I'll have to read again. Anyway, having `send()` behavior consistent with `sr()` and `sr1()` is what we want.

**Comment by p-l-** [comment]
But I really don't think that `send()` (or `sr()` and `sr1()`) should have an `iface=` argument.

**Comment by guedou** [comment]
The root issue might be related to this line https://github.com/secdev/scapy/blob/master/scapy/arch/linux.py#L478

**Comment by guedou** [comment]
Can this PR be merged?

**Comment by p-l-** [comment]
As I said, I don't like the idea of `send()` having an `iface=` parameter. `send()` should rely on a routing table, not an interface (which, in turn, will provide an interface **and** a gateway). What is the meaning of providing an interface alone? We still need the routes to get the gateway IP address.

**Comment by guedou** [comment]
This PR aligns sr1() and send() behavior. I think that it is ok to merge it.

Bypassing the routing table with these functions is indeed useful for protocols such as IPv6 with link-local addresses when the same prefix exists on different interfaces.

**Comment by guedou** [comment]
This is indeed related to #2108 and #1975. 

As explained several times in this thread, I really think that this PR should be merged.

**Pull request merged**
