### PR TITLE
Add sponsors badge to Scapy?

### PR DESCRIPTION
**Pull request by gpotter2**
**Do you think it would be right for us to promote ourselves this way ?**
I know @guedou already is a GitHub sponsors-enables (so am I), but apparently @p-l- isn't.

Waiting for your input

### CODE REVIEW

**Comment by p-l-** [comment]
If I understand well, I should join the wait list?

**Comment by p-l-** [comment]
You can add my github handle.

**Comment by gpotter2** [comment]
I merged that too quickly.
115559E3-98C9-4556-BD5B-7C2BC9DA70EB
When @p-l- will have fully joined the program (get approved) it will fix itself..

**Comment by gpotter2** [comment]
Let's wait for p-l- to be approved, not to break GitHub.

**Pull request merged**
