### PR TITLE
Add support for Geneve per IETF draft draft-ietf-nvo3-geneve-06

### PR DESCRIPTION
**Pull request by haozheng10**
This PR adds support for draft-ietf-nvo3-geneve-06

### CODE REVIEW

**Comment by guedou** [comment]
#1187 is another implementation

**Comment by haozheng10** [comment]
@guedou #1187 is incomplete in the following area,
1) no individual fields for the Geneve header flags (ver, option len, critical, OAM)
2) no support for Geneve header options for either build or dissect
3) no unit tests

**Comment by guedou** [comment]
Could you rebase against master? Thanks.

**Comment by haozheng10** [comment]
merged from master

**Comment by guedou** [comment]
The `flake8` tests are failing: https://travis-ci.org/secdev/scapy/jobs/362339847 Please conform to PEP08 to correc them. I will review the PR when this is fixed.

**Comment by haozheng10** [comment]
fixed white space complains

**Pull request merged**
