### PR TITLE
Fix L2CAP_ConnResp comparing incorrect CID fields

### LINKED ISSUE #2012: L2CAP_ConnResp answers method is comparing the wrong Channel Identifier fields
#### Brief description

The answers method of L2CAP_ConnResp (scapy/layers/bluetooth.py) is comparing the wrong Channel Identifier fields.

#### Actual result

The answers method of L2CAP_ConnResp checks whether the _dcid_ field of the Response is the same as the _scid_ field from the Request.
However, according to Bluetooth Core spec v4.2 (p. 63):

> 4.3 CONNECTION RESPONSE (CODE 0x03)
> Source Channel Identifier - SCID (2 octets)
> This field contains the channel endpoint on the device receiving this
> Response packet. This is copied from the SCID field of the connection
> request packet.

On the other hand, the Destination Channel Identifier (DCID) of the Response is chosen by the receiver of the Request and is not necessarily related to the SCID of the Request.

This leads to L2CAP Connection Responses not getting detected as answers to Connection Requests if SCID and DCID differ.

#### Expected result

Instead of:

> return isinstance(other, L2CAP_ConnReq) and self.dcid == other.scid

it should be 

> return isinstance(other, L2CAP_ConnReq) and self.scid == other.scid

### PR DESCRIPTION
**Pull request by HorakS**
L2CAP Connection Responses were not detected as answers if the DCID field of
the Request differed from the Response's SCID field. According to the
Bluetooth Core specifications, only the SCID fields are identical in Request
and Response.

Fixes #2012.

### CODE REVIEW

**Comment by gpotter2** [comment]
Thanks for the PR. This triggers the failure of one of the unit tests, could you fix it ? From the log on Travis:

```
###(015)=[failed] Answers
>>> a = HCI_Hdr(b'\x02\x00\x00\x0c\x00\x08\x00\x05\x00\x02\x00\x04\x00\x00\x00\x9a;')
>>> b = HCI_Hdr(b'\x02\x00\x00\x10\x00\x0c\x00\x05\x00\x03\x00\x08\x00\x9a;\x00\x00\x00\x00\x01\x00')
>>> assert b.answers(a)
Traceback (most recent call last):
  File "<input>", line 2, in <module>
AssertionError
```

That would be in `tests/bluetooth.uts`

**Comment by gpotter2** [comment]
I'm pretty sure this also applies to `L2CAP_ConfResp` a few lines below.
We can merge it as it, or you can add it if you'd like

**Comment by HorakS** [comment]
As you noted, Configure Request/Response have the same issue. But here it is a bit more complicated, since they both only contain either the SCID or the DCID.
I suggest removing the SCID comparison completely from Configure Response, thus only relying on the comparing the ID fields in L2CAP_CmdHdr. It would certainly be an improvement to the current version.

**Comment by gpotter2** [comment]
Thanks for the note. Done in https://github.com/secdev/scapy/pull/2032

**Pull request merged**
