### PR TITLE
adds mysummary()s to RAs, and to RA options MTU, route info, RDNSS, …

### PR DESCRIPTION
**Pull request by TheDiveO**
…DNSSL

This PR:
- adds `mysummary()`s to the classes `ICMPv6ND_RA`, `ICMPv6NDOptRouteInfo`, `ICMPv6NDOptRDNSS`, `ICMPv6NDOptDNSSL`, and `ICMPv6NDOptMTU`.
- extends the `mysummary()` of `ICMPv6NDOptPrefixInfo`.
- adds `icmp6ndraprefs` RFC 4191 route(r) preference enumeration values to common use in `ICMPv6ND_RA` and `ICMPv6NDOptRouteInfo`.

I manually run the regression tests and they passed for the classes mentioned above (python3 test output); in addition this PR is subject to your normal test suite:
```
passed 988340A1 ICMPv6ND_RA - Basic Instantiation
passed EAB9F5B1 ICMPv6ND_RA - Basic instantiation with empty dst in IPv6 underlayer
passed 854A2794 ICMPv6ND_RA - Basic dissection
passed 10B9F0CB ICMPv6ND_RA - Basic instantiation with empty dst in IPv6 underlayer
passed 5F315605 ICMPv6ND_RA - Answers
passed 12DB2C22 ICMPv6NDOptMTU - Basic Instantiation
passed 65770798 ICMPv6NDOptMTU - Instantiation with specific values
passed 83B871C6 ICMPv6NDOptMTU - Basic dissection
passed 17C89A45 ICMPv6NDOptMTU - Dissection with specific values
passed F594DA97 ICMPv6NDOptPrefixInfo - Basic Instantiation
passed 48915433 ICMPv6NDOptPrefixInfo - Instantiation with specific values
passed ACF9B9CF ICMPv6NDOptPrefixInfo - Basic Dissection
passed 5CFA5B35 ICMPv6NDOptPrefixInfo - Instantiation with specific values
passed 8C3E3751 ICMPv6NDOptRouteInfo - Basic Instantiation
passed 44A42CE7 ICMPv6NDOptRouteInfo - Instantiation with forced prefix but no length
passed D30C6789 ICMPv6NDOptRouteInfo - Instantiation with forced length values (1/4)
passed 03213D9B ICMPv6NDOptRouteInfo - Instantiation with forced length values (2/4)
passed D2034B7A ICMPv6NDOptRouteInfo - Instantiation with forced length values (3/4)
passed 9B323128 ICMPv6NDOptRouteInfo - Instantiation with forced length values (4/4)
passed 0E899A78 ICMPv6NDOptRouteInfo - Instantiation with specific values
passed A9702412 ICMPv6NDOptRouteInfo - Basic dissection
passed BA32308F ICMPv6NDOptRouteInfo - Dissection with specific values
passed 4F509225 ICMPv6NDOptRDNSS - Basic Instantiation
passed 9CD0A8FB ICMPv6NDOptRDNSS - Basic instantiation with 1 DNS address
passed C58A2B38 ICMPv6NDOptRDNSS - Basic instantiation with 2 DNS addresses
passed 43D6D077 ICMPv6NDOptRDNSS - Instantiation with specific values
passed DC2BFF23 ICMPv6NDOptRDNSS - Basic Dissection
passed 37BF7067 ICMPv6NDOptRDNSS - Dissection (with 1 DNS address)
passed 9D964AF3 ICMPv6NDOptRDNSS - Dissection (with 2 DNS addresses)
passed 043EECBA ICMPv6NDOptDNSSL - Basic Instantiation
passed F6B0842F ICMPv6NDOptDNSSL - Instantiation with 1 search domain, as seen in the wild
passed E914C420 ICMPv6NDOptDNSSL - Basic instantiation with 2 search domains
passed ECC9DE2E ICMPv6NDOptDNSSL - Basic instantiation with 3 search domains
passed B1DC63A2 ICMPv6NDOptDNSSL - Basic Dissection
passed B96216D1 ICMPv6NDOptDNSSL - Basic Dissection with specific values
```

### CODE REVIEW

**Comment by guedou** [comment]
This PR looks fine but I have some comments:
- I would like to have unit tests for the mysummary() Something simple will be fine
- it will be nicer if the the dns and searchlist fields are expended with commas instead of using the default Python list representation

**Comment by TheDiveO** [comment]
Can be done ;)
- re: unit tests ... I assume that it would be okay if I don't construct the packets from binary scratch but instead rely on Scapy to build the payload, as this should have been tested by the other tests to work correctly, correct?
- re: DNS server address list, searchlist ... should this be done at Scapy's `sprintf()` level, or should I rather do list explosion inside the `mysummary()` methods instead?

**Comment by guedou** [comment]
You can add the mysummary() tests to existing code testing RA. If the one you need don't exist, building a packet is enough and you don't need to parse a real binary.

The list handling needs to be done in your code. You can prepare a nicer output prior to calling sprintf().

**Comment by TheDiveO** [comment]
@guedou Tests are now in place, and summary printing of lists improved.

**Pull request merged**
