### PR TITLE
Re-enable ISOTP unit tests for MAC OSX, BSD, Windows and PyPy machines

### PR DESCRIPTION
**Pull request by polybassa**

### CODE REVIEW

**Comment by polybassa** [comment]
@gpotter2 We've discussed these tests. According to your point, you didn't like isotp.uts to be executed by default (``./run_tests``). Should I add another keyword for this test?

**Comment by gpotter2** [comment]
The isotp tests used to crash a lot, especially on PyPy. I indeed would like for them not to be ran in `run_tests` because that util should be super fast (but also super responsive, with few individual tests hanging for more than a few seconds).

It would probably require a new keyword since I've been mixing up `vcan_sockets` :)

**Comment by polybassa** [comment]
speaking about keywords... I've made a list of keywords in all uts files of Scapy [kws2.txt](https://github.com/secdev/scapy/files/6741339/kws2.txt).

Only these keywords are used in CI:

```
appveyor_only
brotli
crypto_advanced
icmp_firewall
ipv6
linux
manufdb
mock_read_routes_bsd
not_pypy
open_ssl_client
osx
require_gui
tap
tcpdump
tshark
tun
vcan_socket
veth
windows
zstd
```

Wouldn't it make sense to clean these keywords up? Basically to remove the not used keywords from the *uts files.

**Comment by polybassa** [comment]
I've added a new keyword `automotive_comm` to indicate unit tests which require communication, and therefore have a longer execution time.

**Comment by polybassa** [comment]
@gpotter2 Ready for review.

**Comment by gpotter2** [comment]
That's fine by me but note I'll tweak tests ran by `./run_tests` if they start being too slow.

Regarding the re-enabling of isotp tests, it's fine as long as they don't freeze.

**Review by gpotter2 — APPROVED** [review]

**Comment by polybassa** [comment]
No problem. Thanks for the review. 

By the way, what's the status of appveyor?

**Comment by gpotter2** [comment]
I answered you on gitter ^^ It's not going away. Why ask?

**Comment by polybassa** [comment]
I asked because currently it looks like no tests are executed on appveyor. Sorry for asking again. Didn't checked gitter.
-- 
Viele Grüße

Nils Weiß

**Comment by gpotter2** [comment]
Thanks for the report, you are right there's a UTscapy bug that runs no test !
I was confused at first ^^

**Comment by gpotter2** [comment]
isotp tests are still unstable: https://github.com/secdev/scapy/runs/3061942222?check_suite_focus=true

```
Regression tests for ISOTP
-- Run at 23:43:54 from [test/contrib/isotp.uts] by UTscapy in 57.1609158516
 -> Passed=120
 -> Failed=6

######
## Testing ISOTPSocket with an actual CAN socket
######


###(091)=[failed] Receive frames from CandumpReader

>>> candump_fd = BytesIO(b'''  vcan0  541   [8]  10 0A DE AD BE EF AA AA
...   vcan0  241   [3]  30 00 00
...   vcan0  541   [5]  21 AA AA AA AA
...   vcan0  541   [8]  10 0A DE AD BE EF AA AA
...   vcan0  541   [8]  10 0A DE AD BE EF AA AA
...   vcan0  241   [3]  30 00 00
...   vcan0  541   [5]  21 AA AA AA AA
...   vcan0  541   [8]  10 0A DE AD BE EF AA AA
...   vcan0  241   [3]  30 00 00
...   vcan0  541   [5]  21 AA AA AA AA
...   vcan0  541   [8]  10 0A DE AD BE EF AA AA
...   vcan0  241   [3]  30 00 00
...   vcan0  541   [5]  21 AA AA AA AA
...   vcan0  541   [8]  10 0A DE AD BE EF AA AA
...   vcan0  241   [3]  30 00 00
...   vcan0  541   [5]  21 AA AA AA AA
...   vcan0  541   [8]  10 0A DE AD BE EF AA AA
...   vcan0  241   [3]  30 00 00
...   vcan0  541   [5]  21 AA AA AA AA''')
>>> 
>>> with ISOTPSocket(CandumpReader(candump_fd), sid=0x241, did=0x541, listen_only=True) as s:
...     pkts = s.sniff(timeout=2, count=6)
...     assert(len(pkts) == 6)
...     isotp = pkts[0]
...     print(repr(isotp))
...     print(hex(isotp.src))
...     print(hex(isotp.dst))
...     assert(isotp.data == dhex("DE AD BE EF AA AA AA AA AA AA"))
...     assert(isotp.src == 0x241)
...     assert(isotp.dst == 0x541)
... 
You should put a filter for identifier=541 on your CAN socket
RX state was reset because first frame was received
<ISOTP  data='\xde\xad\xbe\xef\xaa\xaa\xaa\xaa\xaa\xaa' |>
0x241
0x541


###(092)=[failed] Receive frames from CandumpReader with ISOTPSniffer without extended addressing

>>> candump_fd = BytesIO(b'''  vcan0  541   [8]  10 0A DE AD BE EF AA AA
...   vcan0  241   [3]  30 00 00
...   vcan0  541   [5]  21 AA AA AA AA
...   vcan0  541   [8]  10 0A DE AD BE EF AA AA
...   vcan0  541   [8]  10 0A DE AD BE EF AA AA
...   vcan0  241   [3]  30 00 00
...   vcan0  541   [5]  21 AA AA AA AA
...   vcan0  541   [8]  10 0A DE AD BE EF AA AA
...   vcan0  241   [3]  30 00 00
...   vcan0  541   [5]  21 AA AA AA AA
...   vcan0  541   [8]  10 0A DE AD BE EF AA AA
...   vcan0  241   [3]  30 00 00
...   vcan0  541   [5]  21 AA AA AA AA
...   vcan0  541   [8]  10 0A DE AD BE EF AA AA
...   vcan0  241   [3]  30 00 00
...   vcan0  541   [5]  21 AA AA AA AA
...   vcan0  541   [8]  10 0A DE AD BE EF AA AA
...   vcan0  241   [3]  30 00 00
...   vcan0  541   [5]  21 AA AA AA AA''')
>>> 
>>> pkts = sniff(opened_socket=CandumpReader(candump_fd), session=ISOTPSession, timeout=1, session_kwargs={"use_ext_addr": False})
>>> assert(len(pkts) == 6)
>>> isotp = pkts[0]
>>> assert(isotp.data == dhex("DE AD BE EF AA AA AA AA AA AA"))
>>> assert (isotp.dst == 0x541)


###(093)=[failed] Receive frames from CandumpReader with ISOTPSniffer
 all flow control frames are detected as single frame with extended address

>>> candump_fd = BytesIO(b'''  vcan0  541   [8]  10 0A DE AD BE EF AA AA
...   vcan0  241   [3]  30 00 00
...   vcan0  541   [5]  21 AA AA AA AA
...   vcan0  541   [8]  10 0A DE AD BE EF AA AA
...   vcan0  541   [8]  10 0A DE AD BE EF AA AA
...   vcan0  241   [3]  30 00 00
...   vcan0  541   [5]  21 AA AA AA AA
...   vcan0  541   [8]  10 0A DE AD BE EF AA AA
...   vcan0  241   [3]  30 00 00
...   vcan0  541   [5]  21 AA AA AA AA
...   vcan0  541   [8]  10 0A DE AD BE EF AA AA
...   vcan0  241   [3]  30 00 00
...   vcan0  541   [5]  21 AA AA AA AA
...   vcan0  541   [8]  10 0A DE AD BE EF AA AA
...   vcan0  241   [3]  30 00 00
...   vcan0  541   [5]  21 AA AA AA AA
...   vcan0  541   [8]  10 0A DE AD BE EF AA AA
...   vcan0  241   [3]  30 00 00
...   vcan0  541   [5]  21 AA AA AA AA''')
>>> 
>>> pkts = sniff(opened_socket=CandumpReader(candump_fd), session=ISOTPSession, timeout=1)
>>> assert(len(pkts) == 12)
>>> isotp = pkts[1]
>>> assert(isotp.data == dhex("DE AD BE EF AA AA AA AA AA AA"))
>>> assert (isotp.dst == 0x541)
>>> isotp = pkts[0]
>>> assert(isotp.data == dhex(""))
>>> assert (isotp.dst == 0x241)


###(094)=[failed] Receive frames from CandumpReader with ISOTPSniffer and count
 all flow control frames are detected as single frame with extended address

>>> candump_fd = BytesIO(b'''  vcan0  541   [8]  10 0A DE AD BE EF AA AA
...   vcan0  241   [3]  30 00 00
...   vcan0  541   [5]  21 AA AA AA AA
...   vcan0  541   [8]  10 0A DE AD BE EF AA AA
...   vcan0  541   [8]  10 0A DE AD BE EF AA AA
...   vcan0  241   [3]  30 00 00
...   vcan0  541   [5]  21 AA AA AA AA
...   vcan0  541   [8]  10 0A DE AD BE EF AA AA
...   vcan0  241   [3]  30 00 00
...   vcan0  541   [5]  21 AA AA AA AA
...   vcan0  541   [8]  10 0A DE AD BE EF AA AA
...   vcan0  241   [3]  30 00 00
...   vcan0  541   [5]  21 AA AA AA AA
...   vcan0  541   [8]  10 0A DE AD BE EF AA AA
...   vcan0  241   [3]  30 00 00
...   vcan0  541   [5]  21 AA AA AA AA
...   vcan0  541   [8]  10 0A DE AD BE EF AA AA
...   vcan0  241   [3]  30 00 00
...   vcan0  541   [5]  21 AA AA AA AA''')
>>> 
>>> pkts = sniff(opened_socket=CandumpReader(candump_fd), session=ISOTPSession, timeout=1, count=2)
>>> assert(len(pkts) == 2)
>>> isotp = pkts[1]
>>> assert(isotp.data == dhex("DE AD BE EF AA AA AA AA AA AA"))
>>> assert (isotp.dst == 0x541)
>>> isotp = pkts[0]
>>> assert(isotp.data == dhex(""))
>>> assert (isotp.dst == 0x241)


###(095)=[failed] ISOTPSession tests

>>> ses = ISOTPSession()
>>> ses.on_packet_received(None)
>>> ses.on_packet_received([None, None])
>>> assert True


######
## Cleanup
######


###(149)=[failed] Cleanup reference to ISOTPSoftSocket to let the thread end

>>> s = None



UTscapy ended with error code 1

WARNING: UNFINISHED THREADS
[<_MainThread(MainThread, started 140267622429696)>, <Thread(TimeoutScheduler._task, started 140267315259136)>]
ERROR: InvocationError for command /usr/bin/sudo -E .tox/pypy2-linux_root/bin/python -m coverage run -m scapy.tools.UTscapy -c ./test/configs/linux.utsc -K tshark -K icmp_firewall -K not_pypy (exited with code 1)
___________________________________ summary ____________________________________
ERROR:   pypy2-linux_root: commands failed
Error: Process completed with exit code 1.
```

**Comment by polybassa** [comment]
Thanks a lot for this report.

I will have a look at this. To be honest, these errors look really strange to me. The failed tests do not involve any network communication. It's just reading and defragmentation from a log file.

The same tests fail on Mac os aswell: 
```
###(091)=[failed] Receive frames from CandumpReader 

4824 

4825>>> candump_fd = BytesIO(b''' vcan0 541 [8] 10 0A DE AD BE EF AA AA 

4826... vcan0 241 [3] 30 00 00 

4827... vcan0 541 [5] 21 AA AA AA AA 

4828... vcan0 541 [8] 10 0A DE AD BE EF AA AA 

4829... vcan0 541 [8] 10 0A DE AD BE EF AA AA 

4830... vcan0 241 [3] 30 00 00 

4831... vcan0 541 [5] 21 AA AA AA AA 

4832... vcan0 541 [8] 10 0A DE AD BE EF AA AA 

4833... vcan0 241 [3] 30 00 00 

4834... vcan0 541 [5] 21 AA AA AA AA 

4835... vcan0 541 [8] 10 0A DE AD BE EF AA AA 

4836... vcan0 241 [3] 30 00 00 

4837... vcan0 541 [5] 21 AA AA AA AA 

4838... vcan0 541 [8] 10 0A DE AD BE EF AA AA 

4839... vcan0 241 [3] 30 00 00 

4840... vcan0 541 [5] 21 AA AA AA AA 

4841... vcan0 541 [8] 10 0A DE AD BE EF AA AA 

4842... vcan0 241 [3] 30 00 00 

4843... vcan0 541 [5] 21 AA AA AA AA''') 

4844>>> 

4845>>> with ISOTPSocket(CandumpReader(candump_fd), sid=0x241, did=0x541, listen_only=True) as s: 

4846... pkts = s.sniff(timeout=2, count=6) 

4847... assert(len(pkts) == 6) 

4848... isotp = pkts[0] 

4849... print(repr(isotp)) 

4850... print(hex(isotp.src)) 

4851... print(hex(isotp.dst)) 

4852... assert(isotp.data == dhex("DE AD BE EF AA AA AA AA AA AA")) 

4853... assert(isotp.src == 0x241) 

4854... assert(isotp.dst == 0x541) 

4855... 

4856You should put a filter for identifier=541 on your CAN socket 

4857RX state was reset because first frame was received 

4858Socket <scapy.layers.can.CandumpReader instance at 0x112b47230> failed with 'I/O operation on closed file.'. It was closed. 

4859Socket <scapy.layers.can.CandumpReader instance at 0x112b47230> failed with 'I/O operation on closed file.'. It was closed. 

4860more Socket <scapy.layers.can.CandumpReader instance at 0x112b47230> failed with 'I/O operation on closed file.'. It was closed. 

4861<ISOTP data='\xde\xad\xbe\xef\xaa\xaa\xaa\xaa\xaa\xaa' |> 

48620x241 

48630x541 

4864

```

Here the error message is indicating that the BytesIO object got closed. Which may actually not be a problem of ISOTP. But I will have a closer look, soon.

Please let me know when you see more instability.


Cheers, 

Nils 
-- 
Viele Grüße

Nils Weiß

**Pull request merged**
