### PR TITLE
Fix PY3 incompatibilities. [Please add to TODO]

### PR DESCRIPTION
**Pull request by karpierz**
Scapy Version: 2.4.0rc5-79
System: Windows7/Windows10
Python Version: 2.7.14/3.4.4/3.6.4

Fix PY3 incompatibilities.

### CODE REVIEW

**Comment by karpierz** [comment]
This fixes are so obvious that it seems to me that tests are unnecessary (in the end, difficult for me to do).

**Comment by guedou** [comment]
The bug are likely present because the corresponding code is not tested. We should try to test them, and document uses cases that crash Scapy.

In your case, lldp should at least be tested. save_session is likely possible too.

**Comment by karpierz** [comment]
I'v reverted changes from lldp and save_session.

**Comment by karpierz** [comment]
>The bug are likely present because the corresponding code is not tested. 

It was usual oversight - existing tests covers a place of its occurence.
I'v reverted changes from lldp and save_session.

**Comment by karpierz** [comment]
PPR is ready for merge to the master.

**Pull request merged**
