### PR TITLE
Added functionality for ISOTP with extended frames

### LINKED ISSUE #2298: ISOTPScan does not work with extended IDs
When using scapy for CAN packages the ISOTP funcionallity does not work when using extended frames. tools\automotive\isotpscanner.py does have --extended option but it does not work.

The following command:
`isotpscanner.py --extended --interface=vector --channel=0 --bitrate=500000 --start 0x17ffFF00 --end 0x17ffffff`
crashes.

Scapy verison is the recent. Commit: 3dfbfc66d89e8a2432a2b857fef3eff94f1b5691
Python 3.7
Windows 10
Vector VN1610 as CAN interface

Output:
  File "C:\Python37\lib\site-packages\scapy\contrib\isotp.py", line 1939, in ISOTPScan
    sniff_time=sniff_time, verbose=verbose)
  File "C:\Python37\lib\site-packages\scapy\contrib\isotp.py", line 1871, in scan_extended
    scan_block_size))
  File "C:\Python37\lib\site-packages\scapy\contrib\isotp.py", line 1702, in send_multiple_ext
    sock.send(packet)
  File "C:\Python37\lib\site-packages\scapy\contrib\cansocket_python_can.py", line 69, in send
    raise ex
  File "C:\Python37\lib\site-packages\scapy\contrib\cansocket_python_can.py", line 67, in send
    return self.iface.send(msg)
  File "C:\Python37\lib\site-packages\python_can-2.2.0-py3.7.egg\can\interfaces\vector\canlib.py", line 336, in send
  File "C:\Python37\lib\site-packages\python_can-2.2.0-py3.7.egg\can\interfaces\vector\vxlapi.py", line 157, in check_status
can.interfaces.vector.exceptions.VectorError: xlCanTransmit failed (XL_ERR_WRONG_PARAMETER)

### PR DESCRIPTION
**Pull request by Ita1pu**
ISOTP messages can be sent with extended can IDs now
    1. Added --extended_can_id option for isotpscanner
    2. Added --wide(-w) option for scanning ranges greater than 0x7FF
    3. Maxmim CAN ID can be `0x1FFF FFFF` now. for isotpscanner
    4. Added extended_can_id argument for functions : get_isotp_packet, scan and scan extended
    5. Added untitests for extended can ids

fixes #2298

### CODE REVIEW

**Comment by polybassa** [comment]
Please use this patch to add functional unit tests for extended can identifier scanning.

Since you are using Vector CAN adapters, I want to help you with this test, because they are fully based on Linux and virtual CAN interfaces.

[isotpscanner.patch.txt](https://github.com/secdev/scapy/files/3770716/isotpscanner.patch.txt)

**Comment by polybassa** [comment]
I approve this PR

**Comment by p-l-** [comment]
BTW, I suppose the `print()` calls should be replaced by scapy warnings...

**Comment by polybassa** [comment]
Hi @p-l- thanks for this remark. I checked if that's applicable. Unfortunately warnings don't get printed if I call the isotpscanner directly from command line.

**Comment by p-l-** [comment]
@polybassa this should be somehow configurable...

**Comment by polybassa** [comment]
Done  #2338

**Pull request merged**
