### PR TITLE
Test scapy imports

### PR DESCRIPTION
**Pull request by gpotter2**
This PR adds a test that imports every file in a new Python session, just to make sure we stop having those dumb circular issues.

**The issue was triggered by the test**

fix https://github.com/secdev/scapy/issues/3246

### CODE REVIEW

**Comment by gpotter2** [comment]
@guedou If you can help debug this it would be greatly appreciated. Should solve https://github.com/secdev/scapy/issues/3246 (once and for all), but I don't have an OSX machine to test it

**Comment by guedou** [comment]
`import.uts` does not find any new issue on my macOS.

Do you think that we can make this test faster?

**Comment by guedou** [comment]
Awesome !

Before the changes:
```
passed F66DC992 000.03s Prepare importing all scapy files
passed 816770EE 029.09s Try importing all core separately
passed 1D3DC2E3 117.76s Try importing all layers separately
passed B57BFE53 193.02s Try importing all contribs separately
```

After the changes:
```
passed 8FC9A72E 000.06s Prepare importing all scapy files
passed 816770EE 021.66s Try importing all core separately
passed 1D3DC2E3 061.64s Try importing all layers separately
passed B57BFE53 116.30s Try importing all contribs separately
```

This is a quite old laptop. On Github Actions, the whole `.uts` takes only 40 seconds.

**Comment by guedou** [comment]
@gpotter2 do you know why some tests are failing?

**Comment by gpotter2** [comment]
No I currently have no idea

**Comment by guedou** [comment]
Let’s merge this PR?

**Comment by gpotter2** [comment]
Sure. I disabled a few imports I thought could be problematic. Those are few contrib modules so it's fine if we don't test them

**Pull request merged**
