### PR TITLE
codecov configuration file moved to .github/

### PR DESCRIPTION
**Pull request by guedou**
This PR is an attempt at reducing the number of files at the root of the project. According to codecov documentation, the yaml file can be located anywhere.

### CODE REVIEW

**Comment by gpotter2** [comment]
Apparently codecov didn't find the config file

**Comment by guedou** [comment]
I need to have another look at the documentation =/

**Comment by guedou** [comment]
The documentation and the code do not agree. The file can be only be located in the root of the project according to https://github.com/codecov/codecov-python/blob/master/codecov/__init__.py#L589 I will try to submit a PR to `https://github.com/codecov/codecov-python/`.

**Comment by guedou** [comment]
I created a PR in the codecov-python repository https://github.com/codecov/codecov-python/pull/235

**Pull request merged**
