### PR TITLE
Add a new parameter interpkt_timeout to the sniff function

### PR DESCRIPTION
**Pull request by haozheng10**
When performing packet tests to a device under test (DUT), sometime the DUT loses packets.  When automating such tests, it is desirable to have the test, hence the sniff session, to end as soon as possible, even when the expected number of packets are not received, or the end of the stream marker packet is not received, both due to packet loss. The existing parameter timeout doesn't accomplish what's needed here, since when you writing the automation for the packet tests, there is no way to anticipate how many packets will be sent, therefore no way to estimate the total duration of the test.  By introducing a parameter interpkt_timeout to sniff(), it specifies a timeout value in seconds, such that, if the timeout has passed since the most recent packet was captured, and no new packet is captured, the sniff stops.

### CODE REVIEW

**Comment by gpotter2** [comment]
Hi, Thanks for your PR !

Please add unit tests (see `test/regression.uts`)

You may want to mock results for this one

**Comment by p-l-** [comment]
As @gpotter2 said, it would be great if you could add a regression test for that.

For the rest, this change seems sensible to me, and not too invasive, so I'd be OK to merge this (with tests).

**Comment by haozheng10** [comment]
@gpotter2 Yes, I definitely want to add a regression test for this.  Could you elaborate on what do you mean by "mock results".  I was wondering about how to  regression test for this interpkt_timeout.  I wrote this patch for my work a while ago, it works for me and I find it to be quite useful in my use cases and want to contribute upstream.  If you can share your idea on how to regression test this, I would very much appreciate it.

**Comment by haozheng10** [comment]
@p-l- Thanks for your encouraging comments.  I definitely want to write a regression test for this feature.  Would you share your idea on how to regression test this feature?  I'd very much appreciate it.  I wrote this patch for my work a while ago, and have been using this, so I know it does what I intend it to do.

**Comment by speakinghedge** [comment]
this really solves an issue for me.

as the timer is now used twice (sharing the same functionality) maybe its a good time (< subtle joke) to encapsulate the thing in a class, e.g. :
```python
class Timer:

    def __init__(self, timeout):
        self._interval = timeout
        self._timeout = None

    def start(self):
        """
        set the timeout of the timer
        """
        self._timeout = time.time() + self._interval

    def expired(self):
        """
        :return: True if the timer has expired, else False
        """

        if self._timeout:
            remain = self._timeout - time.time()
            if remain < 0:
                return True

        return False
```
Maybe the `expired()` should throw an exception if the timer was not started before.

**Comment by speakinghedge** [comment]
> I was wondering about how to regression test for this interpkt_timeout.

As I was already attracted to this issue earlier this day... :smile: 

Why not using a [socketpair](https://gist.github.com/speakinghedge/9f98f402808680b15215e404ef5f7ea8) (beside the fact that this will only work on Linux) for testing this 
so you can inject a defined stream of frames into `sniff()`?

**Comment by guedou** [comment]
@speakinghedge your idea is nice. Are you willing to implement it ?

**Comment by speakinghedge** [comment]
@guedou which of the solutions from above? 

[ ] class to encap timers
[ ] socketpair for testing sniff

will do both if required.

**Comment by guedou** [comment]
@speakinghedge both will be awesome. I love tests =)

@gpotter2 any idea to get this working on Windows?

**Comment by gpotter2** [comment]
@speakingedge Instead of socketpair, could you use `ObjectPipe` from scapy.automaton ?

In your gist, the implementation would be to use an ObjectPipe object as ins and out at the same time

**Comment by speakinghedge** [comment]
@gpotter2 I was not aware of the ObjectPipe (that has a nice selectable interface). Thanks for the hint, looks promising, will try ASAP.

**Comment by speakinghedge** [comment]
@haozheng10 Would you like to team-up to work on this/finish this PR? 

I don't want to steal it from you :worried:

**Comment by haozheng10** [comment]
@speakinghedge what do you propose to proceed?  The project maintainers basically want some unit tests to go with the main changes, right?  Why don't I take a look at Object Pipe and see if I can whip up some UTs?  OTOH, I was planning on use pcap files to test this timeout feature, as sniff can operate on a pcap file too.

**Comment by speakinghedge** [comment]
> ... right?

Right. And sorry if my request looked as I would like to put any kind of pressure on you - I just tried to offer some help :)

I'm also fine if you just finish your PR - the part about a [generic timeout class](https://github.com/secdev/scapy/pull/1181#issuecomment-372307872) could/should be handled in a separate PR (I'm aware that this creates another PR and therefore more effort for the maintainers but it also keeps the topics 'adding functionality' and 'refactor if there is time - and a test' separated).
Just drop me a line if you would like to do this additional step or not.

> OTOH, I was planning on use pcap files to test this timeout feature, as sniff can operate on a pcap file too.

Then I suggest to proceed with the pcap based solutions as it would solve the problem and causes less new code (even if the inject-frames-with-a-pipe looks like a lot of useful fun).

**Comment by gpotter2** [comment]
Closed for inactivity, but also because the sniffing API has been completely overhauled. The PR would have to be reworked, probably in something fancier :)

**Pull request closed without merging**
