### PR TITLE
Remove duplicated fields for GTP v2

### PR DESCRIPTION
**Pull request by gnewson**
This PR removes the duplicated fields of the GTP v2 protocol as described in #2862.

Tested via the CLI and no warnings seen when load_contrib("gtp_v2") is run.

### CODE REVIEW

**Comment by gnewson** [comment]
The failures are due to the test files referring to the "spare" field.  I'll fix that tomorrow and update.

**Review by guedou — COMMENTED** [review]
Did you have a look at GTPv2 specification before making these changes? I wonder if they can be merged into a 3 bits BitField() instead.

**Comment by gnewson** [comment]
I didn't look at the specs, no.  I'll take a look at the specs to see if that makes sense but which bits are you thinking might be possible to merge into a BitField?

**Comment by guedou** [comment]
`BitField("SPARE", 0, 3)` will make more sense.

**Comment by gnewson** [comment]
Oh, I see now, yes.  Let me check the specs and confirm.

**Comment by gnewson** [comment]
@guedou I've looked at version 16.5.0 of the docs https://portal.3gpp.org/desktopmodules/Specifications/SpecificationDetails.aspx?specificationId=1692.  My interpretation is that there are 3 individual spare bits rather than a bitfield.  
For the Evolved Packet Core (EPC) specific header, there are only 2 spare bits, one of the three for the general is used.

**Comment by gnewson** [comment]
@guedou If you're happy to merge this given that the spec seems to support what's there already in the code I'll get onto another duplicate field ticket.

**Pull request closed without merging**
