### PR TITLE
Enhancements to GTP headers

### PR DESCRIPTION
**Pull request by UmakantKulkarni**

### CODE REVIEW

**Review by UmakantKulkarni — COMMENTED** [review]
Please review.

**Comment by gpotter2** [comment]
Hi, could you please squash and rebase against master ? Thanks

**Comment by UmakantKulkarni** [comment]
> Hi, could you please squash and rebase against master ? Thanks

Sure, let me do that!

**Comment by UmakantKulkarni** [comment]
@gpotter2 , I see these errors after pull - https://github.com/secdev/scapy/pull/2795/checks?check_run_id=1131224951#step:5:3687
Can you please check, what's wrong; Or am I missing anything?

**Comment by gpotter2** [comment]
Those failures are unrelated. Could you rebase again against master ? I've disabled the failing tests
You would probably do
```
git pull --rebase upstream master
git push -f
```
to make a clean rebase. You can squash your commits afterwards

**Comment by gpotter2** [comment]
I've rebased and squashed for you

**Comment by UmakantKulkarni** [comment]
> I've rebased and squashed for you

Great, Thanks @gpotter2 !
We can merge it to master, if you are okay with the changes.

**Review by guedou — CHANGES_REQUESTED** [review]
Could you add some tests regarding the new conditional fields?

**Comment by UmakantKulkarni** [comment]
> Could you add some tests regarding the new conditional fields?

Sure, let me add that!

**Comment by UmakantKulkarni** [comment]
Hi, I've modified the test cases with all the fields that I know of.
I will update the tests with remaining fields over time once I get the production PCAP

**Comment by gpotter2** [comment]
Thanks a lot for the update !

**Comment by UmakantKulkarni** [comment]
@gpotter2 , I've made the changes as requested. Can you please approve the PR?

**Review by gpotter2 — APPROVED** [review]

**Pull request merged**
