### PR TITLE
bluetooth: Reorder HCI command packets to follow opcode

### PR DESCRIPTION
**Pull request by antoniovazquezblanco**
**Checklist:**

-   [x] If you are new to Scapy: I have checked [CONTRIBUTING.md](https://github.com/secdev/scapy/blob/master/CONTRIBUTING.md) (esp. section submitting-pull-requests)
-   [x] I squashed commits belonging together
-   [x] I added unit tests or explained why they are not relevant
-   [x] I executed the regression tests (using `cd test && ./run_tests` or `tox`)
-   [x] If the PR is still not finished, please create a [Draft Pull Request](https://github.blog/2019-02-14-introducing-draft-pull-requests/)

This PR simply reorders bluetooth HCI command packets by opcode to keep the source a little bit tidier. Reordering the packets and the binding instructions I found a duplicate binding...

Low effort maintenance...

### CODE REVIEW

**Review by p-l- — CHANGES_REQUESTED** [review]
Hi there :wave: 
We try to limit the amount of unneeded changes to keep a clean commit history (that often proves really helpful for debugging).
While I do understand the benefit for `bind_layers()` calls (spotting duplicates), I don't think it is really useful to reorder class definitions (and it will make the history harder to read).
Could you only reorder the `bind_layers()` calls?

**Comment by antoniovazquezblanco** [comment]
In order to keep clean commit history I can squash this changes to changes that are to come to this layer but I guess that reduces readability of the future changes.

Would you prefer to only reoder binding?
Would you prefer to squash a full reorder with new additions?


Thanks

**Review by p-l- — APPROVED** [review]

**Comment by p-l-** [comment]
Thank you!
I'd rather keep the order even when changing code (even more importantly then, because reordering will hide the changes from the diff).

**Comment by antoniovazquezblanco** [comment]
Thank you!

**Pull request merged**
