### PR TITLE
[WIP] TLS 1.3

### PR DESCRIPTION
**Pull request by gpotter2**
There is way over my head to do, here's what I could get so far:
- (this PR includes https://github.com/secdev/scapy/pull/1574)
- fixes small IP bug when ihl < 5
- merges TLS13ServerHello and TLSServerHello, as there is now no way to differentiate them apart from their extensions
- updates some constants, especially the default TLS version in the packets. It used to be set to `0x0301` in some drafts, but is now `0x0303` (TLS 1.2)
- Fix TLSServerHello dissection + Implement the new (changed) HelloRetry
- updated the pack (2/2) of tests according to the latest draft. Some still don't pass

**TODO: (feel free to contribute)**
- fixes https://github.com/secdev/scapy/issues/1668
- fix the remaining tests
- find a way to have `gtx_unix_time` exist only on TLS 1.3, in which case `random_bytes` size is 32 (rather than 28)

### CODE REVIEW

**Comment by gpotter2** [comment]
Current most problematic issue is that `tls_version` is now always set to `0x0303` in the packet field. You now have to detect the version from inside the extensions.

Current implementation (with the edits) has added the detection of `0x0304` in the extensions, but it now triggers TLS 1.3 dissection (in `dispatch_hook`, which comies with decryption) even when it should keep stay on `TLS` (for instance, after packet 2 in the tests, scapy will try to dissect TLS13 whereas it is a ClientHello message, in TLS 1.2 format)

**Comment by gpotter2** [comment]
@guedou @p-l- If you have some time available, it could be worth looking into this.

I'm still figuring out how to fix the issue mentioned above: the tests in `tls13.uts` fail when the payload becomes encrypted... (starting with packet `t5`). I managed to fix the `TLS 1.3` detection and `TLSHelloRetryRequest`

**Comment by guedou** [comment]
Thanks for this work. TLS 1.3 is a though protocol =)

I will try to find time to review it carefully. According to the diffs, it seems that you updated the current test vectors using RC8448. It is likely not useful for our tests, but an errata fixes some vectors (see https://www.rfc-editor.org/errata_search.php?rfc=8448).

I do not recall which version of the draft the original author used, but I will be that it is 18 or 20. I wonder if changes in the key scheduling algorithm were made in between (https://tools.ietf.org/rfcdiff?url1=draft-ietf-tls-tls13-18.txt&url1=rfc8446 might help us investigating). However, as far as I recall, the last revisions of the drafts were related to zero RTT and not the core of TLS 1.3.

**Comment by gpotter2** [comment]
The version in place is the draft 18. The goal of this PR was to upgrade it to the version that got accepted (we won't support all drafts..). This meant updating the vectors.

One of the biggest (and breaking difference) since draft 18 is that it used a TLS version of `0x304`, whereas the last revision uses `0x303` and specifies a TLS extension that says `0x304`. This breaks all previous tests.

**Comment by guedou** [comment]
RFC8448 also defines the expected results for key computation. I started adding some checks. See the attached patch: [tls13.check_keys.patch.txt](https://github.com/secdev/scapy/files/3359091/tls13.check_keys.patch.txt)

This could help us narrowing the issue.

**Comment by gpotter2** [comment]
(I'm not actively working on this, but as a maintainer, you have write access on this branch. You can
`git remote add gpotter2 git@github.com:gpotter2/scapy.git`
`git checkout gpotter2/tls-1.3`
and push in the branch)

**Comment by gpotter2** [comment]
Overwritten by https://github.com/secdev/scapy/pull/2132

**Pull request closed without merging**
