### PR TITLE
Packet layers manipulations

### PR DESCRIPTION
**Pull request by Romounet**
Proposition of adding new methods into the main Packet class:
* lastlayer_index
* remove_lastlayer
* decode_lastlayer_as
This proposition is based on the fact that the last layer of a packet is not easy to manipulate (in an automated way), when not dealing with a simple payload.

An other method I propose to add is:
* set_byte

This method purpose is to modify just one or several byte of a packet string without modifying its properties and decoding status as a Packet instance.

The use of these methods is mainly directed to scripts and bigger tools that may require these kind of manipulations.
I'm looking forward your opinion on these and the opportunity to merge them into the framework.
As for the implementation part, there may well be some adjustments to make.

### CODE REVIEW

**Comment by guedou** [comment]
Could you provide some use cases and unit tests ? Also, could you use a linter to make your code PEP-08 compliant ? Thanks.

**Comment by Romounet** [comment]
Ok, I'm working on the unit tests and the PeP8 compliance. About the testcases:
The lastlayer functions aim to manipulate easily the lastlayer of a Packet. In that sense they are the counterpart of the *payload* functions (pkt.decode_payload_as).
@guedou You mentionned the idea of using pkt[-1] to select the last layer, and it does not actually work as it tries to identify -1 as a class name.
But yes, the implementation of the methods could very probably be simplified.
These functions are usefull whenever you want to manipulate packets, you don't know the composition of (meaning you are not in interractive mode).

The set_byte function is usefull whenever you want to work down at the byte level. Moreover, there are some packet manipulations that are just uneasy to do using the normal attributes of the packet.
That way, you can mess up with a packet string and see the effects on the decoding.

>>> pkt
<IP  len=12 frag=0 proto=udp |<UDP  sport=isakmp dport=isakmp |<ISAKMP  |>>>
>>> pkt[-1]
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/outils/reseau/scapy/scapy/packet.py", line 983, in __getitem__
    raise IndexError("Layer [%s] not found" % lname)
IndexError: Layer [-1] not found
>>> pkt.lastlayer()
<ISAKMP  |>
>>> pkt.lastlayer_index()
2
>>> pkt.remove_lastlayer()
<IP  frag=0 proto=udp |<UDP  |>>
>>> pkt.decode_lastlayer_as(TCP)
<IP  frag=0 proto=tcp |<TCP  sport=domain dport=domain seq=524658 |>>
I'm not completely happy here, because I would like an option allowing to not apply the post_build() when doing the add_payload(), but I don't know yet how to do this.

>>> str(pkt)
'E\x00\x00\x1c\x00\x01\x00\x00@\x06|\xd9\x7f\x00\x00\x01\x7f\x00\x00\x01\x005\x005\x00\x08\x01r'
>>> len(pkt)
28
>>> pkt.set_byte(1,'\x04')
<IP  version=4L ihl=5L tos=0x4 len=20 id=1 flags= frag=0L ttl=64 proto=hopopt chksum=0x7ce7 src=127.0.0.1 dst=127.0.0.1 |<TCP  sport=domain dport=domain seq=524658 |>>
>>> str(pkt)
'E\x04\x00\x14\x00\x01\x00\x00@\x00|\xe7\x7f\x00\x00\x01\x7f\x00\x00\x01\x005\x005\x00\x08\x01r'
>>> len(pkt)
28
>>> pkt.show()
###[ IP ]### 
  version= 4L
  ihl= 5L
  tos= 0x4
  len= 20
  id= 1
  flags= 
  frag= 0L
  ttl= 64
  proto= hopopt
  chksum= 0x7ce7
  src= 127.0.0.1
  dst= 127.0.0.1
  \options\
###[ TCP ]### 
     sport= domain
     dport= domain
     seq= 524658
     ack= 0
     dataofs= None
     reserved= 0
     flags= S
     window= 8192
     chksum= None
     urgptr= 0
     options= []

**Comment by guedou** [comment]
These ideas are great, but are too different with current Scapy behavior (i.e. p[2] already works). I will suggest that you keep the logic in the `lastlayer_index()` method and use it in `Packet.__getitem__()`. 

I quickly hacked it to do the following examples. What do you think of this API?
```
>>> p = IP()/UDP()/DNS(); p[-1]; p[-2]
<DNS  |>
<UDP  sport=domain |<DNS  |>>

>>> p = IP()/UDP()/DNS(); del(p[-1]); p
<IP  frag=0 proto=udp |<UDP  |>>

>>> p = IP()/UDP()/Raw(str(DNS())); p[-2].decode_payload_as(DNS); p
<IP  frag=0 proto=udp |<UDP  |<DNS  id=0 qr=0L opcode=QUERY aa=0L tc=0L rd=1L ra=0L z=0L ad=0L cd=0L rcode=ok qdcount=0 ancount=0 nscount=0 arcount=0 |>>>
```

Concerning `set_byte()`, I don't understand why it should be implemented, as it could easily be donein Python.

**Comment by Romounet** [comment]
Sorry for my late reply.

About the `pkt[-1]` api, seems good to me. It does respond to the need, if you think it is more intuitive/usable than `lastlayer()`, I am perfectly fine with that.


About the `set_byte()` method, I can understand the question.
Of course modifying a byte before sending the packet is no problem using regular python, but as soon as you want to touch the packet this way, you are forced to do it outside scapy.
Meaning that in case you want to decode it and continue to work with it inside scapy, you just can't.

Let's say you want to put a value of 0x99 at byte x of your pkt (you know, just to see what happens with the remote server ...) you would do somehting like
```
packetstring = str(pkt)
packetstring[x] = '\x99'
```
and then send it.

What if, after that, you want to modify `pkt.field_whatever`? If you modify pkt, your (\x99) modification has been lost, and you will have to redo this modification before sending the packet.
If you do it the other way arround, nothing is guaranted that you will be able to rebuild your initial packet decoding from the (modified) packetstring. You will have to modify the packetstring by hand.

Either way, both kind of modifications are not easily compatible, and that is the purpose of `set_byte`.

**Comment by p-l-** [comment]
There is no such thing as "outside Scapy", since Scapy is only a Python library.

If you want to set a byte (which only means something for packets entirely explicit: every field has a "real" and computed value), you're stuck with getting `data = str(pkt)`, altering it, then storing `pkt = type(pkt)(data)`.

**Comment by Romounet** [comment]
Well, that is pretty much what I was saying. Let's just precise that when you do `pkt = type(pkt)(data)` there is much chance that you loose your decoding setup : it will be guessed, which is not what I wanted.
However, if it is not something you want to include in scapy I would totaly understand, just discard it from the PR.
That is just something I needed, that is why I was proposing it.

**Comment by p-l-** [comment]
I understand what you need, but it makes little sense to change a `byte` from a non-explicit Scapy Packet object, since you do not even know, sometimes, what you are changing. Say you have a layer with two TLVs, you need to parse the first length field to know what byte you need to change. And if you change that value, you're not changing the same byte any more.

If you want to tamper bytes, you need the packet as raw bytes so that you know exactly what you are doing. If not, just change the field values of the `Packet` object. These look like two very different operations to me.

**Comment by Romounet** [comment]
@guedou Yes, of course. I'm going to do that :p

**Comment by p-l-** [comment]
Please reopen if needed.

**Pull request closed without merging**
