### PR TITLE
Fix Dot11EltCountry

### PR DESCRIPTION
**Pull request by Zoruk**
The padding length of Dot11EltCountry was wrongly calculated causing all the misinterpretation of all the following Dot11Elt

This patch fix:
- Padding length calculation is now correct
- country_string is 2 bytes length not 3
- Add field environment (replacing the 3rd byte of the old country)

### CODE REVIEW

**Comment by gpotter2** [comment]
Please:
- rebase against master to fix the tests
- provide an example of packet where the padding calculation is incorrect. We already had a similar report recently, and the fix looked good to me
Thanks for the PR

**Comment by gpotter2** [comment]
I also disagree with the field change: Scapy currently sticks to the RFC

**Comment by Zoruk** [comment]
- Here is the example packet misinterpreted `
RadioTap(b"\x00\x008\x00/@@\xa0 \x08\x00\xa0 \x08\x00\x00\x0b\x865E\x00\x00\x00\x00\x10\x18l\t\xc0\x00\xd6\x00\x00\x00\x00\x00\x00\x00\x00\x00S\x855E\x00\x00\x00\x00\x16\x00\x11\x03\xc9\x00\xd6\x01P\x080\x00\xc0\xe8b~\x86\x0e\xdc\xa5\xf4`\xc3\x13\xdc\xa5\xf4`\xc3\x13\xf0\xfe\x06\xec\xff\xe4\xd8\x02\x00\x00f\x00!\x14\x00\x0epublic-HEIG-VD\x01\x06\x98$\xb0H`l\x03\x01\x01\x07\x06CH \x01\r\x14\x0b\x05\x01\x00\x1d\x8d[*\x01\x00-\x1a\xac\x19\x1b\xff\xff\xff\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00=\x16\x01\x08\x04\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x7f\x06\x00\x10\x00\x00\x01@\x96\x06\x00@\x96\x00\x10\x00\xdd\x18\x00P\xf2\x02\x01\x01\x80\x00\x03\xa4\x00\x00'\xa4\x00\x00BC^\x00b2/\x00\xdd\x06\x00@\x96\x01\x01\x04\xdd\x05\x00@\x96\x03\x05\xdd\x05\x00@\x96\x0b\x89\xdd\x05\x00@\x96\x14\x00\xe8D\x1a\xee")
`
- Rebase on master done
- Revert the field change

**Comment by gpotter2** [comment]
Thanks for the reply,

However, I fail to see how the packet is misinterpreted: tshark apparently returns the same results (you can try the `tdecode()` function).

Would you mind showing what's happening on your end, and what's expected ?

Thanks a lot !

**Comment by Zoruk** [comment]
Sorry, with the data from the tests (we just removed one entry of Dot11EltCountryConstraintTriplet):
```
data = hex_bytes('00001a002f48000017cd9f3100000000000c3c144001e000000080000000ffffffffffff461b860bef06461b860bef06909403e0f75b0000000064001105000c4c697665626f782d3232353001088c1218243048606c0301240504020300000725504c202801172c01173001173401173801173c011740011764011e68011e6c011e70011e000b05000002ffff46050000000000200100c30502171717002a01002d1aef0117fffffffffeffffffff1f000001000000000018e6e719003d1624050000000000000000000000000000000000000000dd180050f2020101840003a4000027a4000042435e0062322f0030140100000fac040100000fac040100000fac020000bf0cb279c33faaff0000aaff0000c005012a00fcffdd1e002686010300dd00000025040592000601d15b5816830000000000000000dd06002686170000dd0e00268618010101024c1b860bef067f080100080200000040dd3b0050f204104a0001101044000102105700010110470010344331423836f042f546303634433142103c000103103c0001031049000600372a000120')
pkt = RadioTap(data)
```
Without the patch:
```
###[ RadioTap dummy ]###
  version   = 0
  pad       = 0
  len       = 26
  present   = TSFT+Flags+Rate+Channel+dBm_AntSignal+Antenna+RXFlags
  mac_timestamp= 832556311
  Flags     =
  Rate      = 12
  ChannelFrequency= 5180
  ChannelFlags= OFDM+5GHz
  dBm_AntSignal= -32 dBm
  Antenna   = 0
  RXFlags   =
  notdecoded= ''
###[ 802.11 ]###
     subtype   = 8
     type      = Management
     proto     = 0
     FCfield   =
     ID        = 0
     addr1     = ff:ff:ff:ff:ff:ff
     addr2     = 46:1b:86:0b:ef:06
     addr3     = 46:1b:86:0b:ef:06
     SC        = 38032
###[ 802.11 Beacon ]###
        timestamp = 1542971395
        beacon_interval= 100
        cap       = res8+short-slot+ESS+privacy
###[ 802.11 Information Element ]###
           ID        = SSID
           len       = 12
           info      = 'Livebox-2250'
###[ 802.11 Rates ]###
           ID        = 1
           len       = 8
           rates     = [0x8c, 0x12, 0x18, 0x24, 0x30, 0x48, 0x60, 0x6c]
###[ 802.11 Information Element ]###
           ID        = DSset
           len       = 1
           info      = '$'
###[ 802.11 Information Element ]###
           ID        = TIM
           len       = 4
           info      = '\x02\x03\x00\x00'
###[ 802.11 Country ]###
           ID        = 7
           len       = 37
           country_string= 'PL '
           \descriptors\
            |###[ 802.11 Country Constraint Triplet ]###
            |  first_channel_number= 40
            |  num_channels= 1
            |  mtp       = 23
            |###[ 802.11 Country Constraint Triplet ]###
            |  first_channel_number= 44
            |  num_channels= 1
            |  mtp       = 23
            |###[ 802.11 Country Constraint Triplet ]###
            |  first_channel_number= 48
            |  num_channels= 1
            |  mtp       = 23
            |###[ 802.11 Country Constraint Triplet ]###
            |  first_channel_number= 52
            |  num_channels= 1
            |  mtp       = 23
            |###[ 802.11 Country Constraint Triplet ]###
            |  first_channel_number= 56
            |  num_channels= 1
            |  mtp       = 23
            |###[ 802.11 Country Constraint Triplet ]###
            |  first_channel_number= 60
            |  num_channels= 1
            |  mtp       = 23
            |###[ 802.11 Country Constraint Triplet ]###
            |  first_channel_number= 64
            |  num_channels= 1
            |  mtp       = 23
            |###[ 802.11 Country Constraint Triplet ]###
            |  first_channel_number= 100
            |  num_channels= 1
            |  mtp       = 30
            |###[ 802.11 Country Constraint Triplet ]###
            |  first_channel_number= 104
            |  num_channels= 1
            |  mtp       = 30
            |###[ 802.11 Country Constraint Triplet ]###
            |  first_channel_number= 108
            |  num_channels= 1
            |  mtp       = 30
            |###[ 802.11 Country Constraint Triplet ]###
            |  first_channel_number= 112
            |  num_channels= 1
            |  mtp       = 30
###[ 802.11 Information Element ]###
           ID        = SSID
           len       = 11
           info      = '\x05\x00\x00\x02\xff\xffF\x05\x00\x00\x00'
###[ 802.11 Information Element ]###
           ID        = SSID
           len       = 0
           info      = ''
###[ 802.11 Information Element ]###
           ID        = 32
           len       = 1
           info      = '\x00'
###[ 802.11 Information Element ]###
           ID        = 195
           len       = 5
           info      = '\x02\x17\x17\x17\x00'
###[ 802.11 Information Element ]###
           ID        = ERPinfo
           len       = 1
           info      = '\x00'
###[ 802.11 Information Element ]###
           ID        = HTCapabilities
           len       = 26
           info      = '\xef\x01\x17\xff\xff\xff\xff\xfe\xff\xff\xff\xff\x1f\x00\x00\x01\x00\x00\x00\x00\x00\x18\xe6\xe7\x19\x00'
###[ 802.11 Information Element ]###
           ID        = HTinfo
           len       = 22
           info      = '$\x05\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
###[ 802.11 Vendor Specific ]###
           ID        = 221
           len       = 24
           oui       = 0x50f2
           info      = "\x02\x01\x01\x84\x00\x03\xa4\x00\x00'\xa4\x00\x00BC^\x00b2/\x00"
###[ 802.11 RSN information ]###
           ID        = 48
           len       = 20
           version   = 1
           \group_cipher_suite\
            |###[ Cipher suite ]###
            |  oui       = 0xfac
            |  cipher    = CCMP
           nb_pairwise_cipher_suites= 1
           \pairwise_cipher_suites\
            |###[ Cipher suite ]###
            |  oui       = 0xfac
            |  cipher    = CCMP
           nb_akm_suites= 1
           \akm_suites\
            |###[ AKM suite ]###
            |  oui       = 0xfac
            |  suite     = PSK
           mfp_capable= 0
           mfp_required= 0
           gtksa_replay_counter= 0
           ptksa_replay_counter= 0
           no_pairwise= 0
           pre_auth  = 0
           reserved  = 0
###[ 802.11 Information Element ]###
           ID        = VHTCapabilities
           len       = 12
           info      = '\xb2y\xc3?\xaa\xff\x00\x00\xaa\xff\x00\x00'
###[ 802.11 Information Element ]###
           ID        = 192
           len       = 5
           info      = '\x01*\x00\xfc\xff'
###[ 802.11 Vendor Specific ]###
           ID        = 221
           len       = 30
           oui       = 0x2686
           info      = '\x01\x03\x00\xdd\x00\x00\x00%\x04\x05\x92\x00\x06\x01\xd1[X\x16\x83\x00\x00\x00\x00\x00\x00\x00\x00'
###[ 802.11 Vendor Specific ]###
           ID        = 221
           len       = 6
           oui       = 0x2686
           info      = '\x17\x00\x00'
###[ 802.11 Vendor Specific ]###
           ID        = 221
           len       = 14
           oui       = 0x2686
           info      = '\x18\x01\x01\x01\x02L\x1b\x86\x0b\xef\x06'
###[ 802.11 Information Element ]###
           ID        = ExtendendCapatibilities
           len       = 8
           info      = '\x01\x00\x08\x02\x00\x00\x00@'
###[ 802.11 Vendor Specific ]###
           ID        = 221
           len       = 59
           oui       = 0x50f2
           info      = '\x04\x10J\x00\x01\x10\x10D\x00\x01\x02\x10W\x00\x01\x01\x10G\x00\x104C1B86\xf0B\xf5F064C1B\x10<\x00\x01\x03\x10<\x00\x01\x03\x10I\x00\x06\x007*\x00\x01 '
```

With the patch:
```
###[ RadioTap dummy ]###
  version   = 0
  pad       = 0
  len       = 26
  present   = TSFT+Flags+Rate+Channel+dBm_AntSignal+Antenna+RXFlags
  mac_timestamp= 832556311
  Flags     =
  Rate      = 12
  ChannelFrequency= 5180
  ChannelFlags= OFDM+5GHz
  dBm_AntSignal= -32 dBm
  Antenna   = 0
  RXFlags   =
  notdecoded= ''
###[ 802.11 ]###
     subtype   = 8
     type      = Management
     proto     = 0
     FCfield   =
     ID        = 0
     addr1     = ff:ff:ff:ff:ff:ff
     addr2     = 46:1b:86:0b:ef:06
     addr3     = 46:1b:86:0b:ef:06
     SC        = 38032
###[ 802.11 Beacon ]###
        timestamp = 1542971395
        beacon_interval= 100
        cap       = res8+short-slot+ESS+privacy
###[ 802.11 Information Element ]###
           ID        = SSID
           len       = 12
           info      = 'Livebox-2250'
###[ 802.11 Rates ]###
           ID        = 1
           len       = 8
           rates     = [0x8c, 0x12, 0x18, 0x24, 0x30, 0x48, 0x60, 0x6c]
###[ 802.11 Information Element ]###
           ID        = DSset
           len       = 1
           info      = '#'
###[ 802.11 Information Element ]###
           ID        = 213
           len       = 4
           info      = '\x02\x03\x00\x00'
###[ 802.11 Country ]###
           ID        = 7
           len       = 40
           country_string= 'PL '
           \descriptors\
            |###[ 802.11 Country Constraint Triplet ]###
            |  first_channel_number= 40
            |  num_channels= 1
            |  mtp       = 23
            |###[ 802.11 Country Constraint Triplet ]###
            |  first_channel_number= 44
            |  num_channels= 1
            |  mtp       = 23
            |###[ 802.11 Country Constraint Triplet ]###
            |  first_channel_number= 48
            |  num_channels= 1
            |  mtp       = 23
            |###[ 802.11 Country Constraint Triplet ]###
            |  first_channel_number= 52
            |  num_channels= 1
            |  mtp       = 23
            |###[ 802.11 Country Constraint Triplet ]###
            |  first_channel_number= 56
            |  num_channels= 1
            |  mtp       = 23
            |###[ 802.11 Country Constraint Triplet ]###
            |  first_channel_number= 60
            |  num_channels= 1
            |  mtp       = 23
            |###[ 802.11 Country Constraint Triplet ]###
            |  first_channel_number= 64
            |  num_channels= 1
            |  mtp       = 23
            |###[ 802.11 Country Constraint Triplet ]###
            |  first_channel_number= 100
            |  num_channels= 1
            |  mtp       = 30
            |###[ 802.11 Country Constraint Triplet ]###
            |  first_channel_number= 104
            |  num_channels= 1
            |  mtp       = 30
            |###[ 802.11 Country Constraint Triplet ]###
            |  first_channel_number= 108
            |  num_channels= 1
            |  mtp       = 30
            |###[ 802.11 Country Constraint Triplet ]###
            |  first_channel_number= 112
            |  num_channels= 1
            |  mtp       = 30
            |###[ 802.11 Country Constraint Triplet ]###
            |  first_channel_number= 0
            |  num_channels= 11
            |  mtp       = 5
           pad       = '\x00'
###[ 802.11 Information Element ]###
           ID        = SSID
           len       = 2
           info      = '\xff\xff'
###[ 802.11 Information Element ]###
           ID        = 70
           len       = 5
           info      = '\x00\x00\x00\x00\x00'
###[ 802.11 Information Element ]###
           ID        = 32
           len       = 1
           info      = '\x00'
###[ 802.11 Information Element ]###
           ID        = 195
           len       = 5
           info      = '\x02\x17\x17\x17\x00'
###[ 802.11 Information Element ]###
           ID        = ERPinfo
           len       = 1
           info      = '\x00'
###[ 802.11 Information Element ]###
           ID        = HTCapabilities
           len       = 26
           info      = '\xef\x01\x17\xff\xff\xff\xff\xfe\xff\xff\xff\xff\x1f\x00\x00\x01\x00\x00\x00\x00\x00\x18\xe6\xe7\x19\x00'
###[ 802.11 Information Element ]###
           ID        = HTinfo
           len       = 22
           info      = '$\x05\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
###[ 802.11 Vendor Specific ]###
           ID        = 221
           len       = 24
           oui       = 0x50f2
           info      = "\x02\x01\x01\x84\x00\x03\xa4\x00\x00'\xa4\x00\x00BC^\x00b2/\x00"
###[ 802.11 RSN information ]###
           ID        = 48
           len       = 20
           version   = 1
           \group_cipher_suite\
            |###[ Cipher suite ]###
            |  oui       = 0xfac
            |  cipher    = CCMP
           nb_pairwise_cipher_suites= 1
           \pairwise_cipher_suites\
            |###[ Cipher suite ]###
            |  oui       = 0xfac
            |  cipher    = CCMP
           nb_akm_suites= 1
           \akm_suites\
            |###[ AKM suite ]###
            |  oui       = 0xfac
            |  suite     = PSK
           mfp_capable= 0
           mfp_required= 0
           gtksa_replay_counter= 0
           ptksa_replay_counter= 0
           no_pairwise= 0
           pre_auth  = 0
           reserved  = 0
###[ 802.11 Information Element ]###
           ID        = VHTCapabilities
           len       = 12
           info      = '\xb2y\xc3?\xaa\xff\x00\x00\xaa\xff\x00\x00'
###[ 802.11 Information Element ]###
           ID        = 192
           len       = 5
           info      = '\x01*\x00\xfc\xff'
###[ 802.11 Vendor Specific ]###
           ID        = 221
           len       = 30
           oui       = 0x2686
           info      = '\x01\x03\x00\xdd\x00\x00\x00%\x04\x05\x92\x00\x06\x01\xd1[X\x16\x83\x00\x00\x00\x00\x00\x00\x00\x00'
###[ 802.11 Vendor Specific ]###
           ID        = 221
           len       = 6
           oui       = 0x2686
           info      = '\x17\x00\x00'
###[ 802.11 Vendor Specific ]###
           ID        = 221
           len       = 14
           oui       = 0x2686
           info      = '\x18\x01\x01\x01\x02L\x1b\x86\x0b\xef\x06'
###[ 802.11 Information Element ]###
           ID        = ExtendendCapatibilities
           len       = 8
           info      = '\x01\x00\x08\x02\x00\x00\x00@'
###[ 802.11 Vendor Specific ]###
           ID        = 221
           len       = 59
           oui       = 0x50f2
           info      = '\x04\x10J\x00\x01\x10\x10D\x00\x01\x02\x10W\x00\x01\x01\x10G\x00\x104C1B86\xf0B\xf5F064C1B\x10<\x00\x01\x03\x10<\x00\x01\x03\x10I\x00\x06\x007*\x00\x01 '
```

With a logical explanation, there is `(Dot11Elt.len -  Dot11Elt.len % 3) / 3` Dot11EltCountryConstraintTriplet, so the length of the padding can be 1 or 2 and should be `Dot11Elt.len % 3`.

The actual function use a padding of len(1) if the number of Dot11EltCountryConstraintTriplet is even otherwise no padding.

**Comment by gpotter2** [comment]
From the RFC:

> Pad (1 byte; optional)
>The size of the information element must be an even number of bytes. If the length of the information element is an odd number of bytes, a single byte of zeroes is appended as a pad.

In your example (unfixed), the length of the IE is:

2 (ID/Len) + 3 (country_string) + 11*3 (descriptors) = 38 => Even => no Padding

I still can't figure out how you would get a such packet. Can you compare it with Wireshark's result ?

**Comment by gpotter2** [comment]
Hmm, tshark says otherwise. I'll have a deeper look

**Comment by Zoruk** [comment]
Ok, it's my bad. 

I had some trouble with the release version so I patched the git version with the same parsing algorithm used in Wireshark without noticing that it was already fixed in https://github.com/secdev/scapy/commit/87ef9e976f5e4c3892442959553943adb52c7686

The algo in wireshark is something like
```
while bytes are available:
    if nb bytes aviables >= 3:
        pick 3 bytes and parse them as Country Info
    else:
        pick 1 byte as padding
```

Which does not strictly respect the norm as you mentioned above since it's possible to have 2 bytes of padding.

**Comment by gpotter2** [comment]
Did you craft the packet yourself or did you sniff it ?
If you sniffed it, we should probably support this behavior even though it isn't in the RFC

**Comment by Zoruk** [comment]
Some crafted come captured but the problem occurred with a captured packet
with the released version (installed with pip).

The parsing only failed with the release version or with craft packet built
to test my implementation against the one from Wireshark so it should be
fine.

**Pull request closed without merging**
