### PR TITLE
Code coverage recently decreased

### PR DESCRIPTION
**Pull request by guedou**
Coverage went from 85% to 83% during the last week. This PR will help me understand why.

### CODE REVIEW

**Comment by gpotter2** [comment]
The nice chart on the codecov page shows
https://codecov.io/gh/secdev/scapy/commit/927c157b58918d5fdce9714a3c35627339cc8657

**Comment by guedou** [comment]
I could not find anything that could decrease the coverage =/

**Comment by guedou** [comment]
Some notes for future reference:

| % | commit | LoC |
| --- | --- | --- |
| 83.15 | 6e6408aedb99b94efab373a3e618c88d498063bb | 40347 | 
| 85.12 | 577bdf8459e55ccc2b5fdd4e37de5457f0f42647 | 40067 |

**Comment by guedou** [comment]
Good news: we are back at 85% !

**Pull request merged**
