### PR TITLE
Add SSL support for DoIP sockets

### PR DESCRIPTION
**Pull request by polybassa**
This PR adds SSL functionality for DoIP Sockets. 

In order to provide SSL functionality, the `recv()` function of existing DoIP socket needed to be refactored. 

The SSL DoIP Sockets work the same way as existing DoIP sockets, only a SslContext has to be provided.

Additionally, this PR adds unit tests for the new recv() function and the SSL DoIPSockets.

### CODE REVIEW

**Comment by gpotter2** [comment]
Could you add a PR summary? Thanks.

**Comment by polybassa** [comment]
@gpotter2 Done

**Review by gpotter2 — DISMISSED** [review]
LGTM. Could you rebase against master? Thanks

**Comment by polybassa** [comment]
> LGTM. Could you rebase against master? Thanks

Done!

**Review by gpotter2 — APPROVED** [review]

**Pull request merged**
