### PR TITLE
Bugfix in automotive staged enumerators

### PR DESCRIPTION
**Pull request by polybassa**
Minor bug fixed that prevented certain parameters from being passed.

### CODE REVIEW

**Comment by polybassa** [comment]
@gpotter2 Apparently, flake8 doesn't like type hints anymore..

**Comment by gpotter2** [comment]
Yeah we're having a breakdown of tests caused by a flake8 update and the migration of Ubuntu to 22.04... we're working on that

**Comment by polydroi** [comment]
@guedou can this PR get into 2.5, please

**Comment by gpotter2** [comment]
Could you also add the `-K` to the matrix default? Thanks

**Comment by gpotter2** [comment]
Workflow didn't run

Error when evaluating 'continue-on-error' for job 'utscapy'. .github/workflows/unittests.yml (Line: 67, Col: 24): Unexpected type of value '', expected type: Boolean.

**Review by guedou — DISMISSED** [review]

**Comment by polybassa** [comment]
Can this PR get merged, please?

**Comment by guedou** [comment]
Do you why one test is not reporting any result ?

**Comment by polybassa** [comment]
No idea.. I was hoping that this would fix, during the merge. I hope its just a glitch in github actions... anyway. If it introduces a bug on master, I will create a new PR to fix it.

**Comment by polybassa** [comment]
These default values in the matrix are weird... I've now added the flag explicitly to remove the Scanner tests from all CI-machines that are not allowed to fail.

**Comment by polybassa** [comment]
@guedou 
These two CI-runs are not part of Actions... so it looks like a problem of github. 

```
ubuntu-latest 3.10 root Expected — Waiting for status to be reported 
ubuntu-latest libpcap 3.10 root Expected — Waiting for status to be reported
```

**Comment by gpotter2** [comment]
It's fine, this happens when we change what tests are considered "required". Ignore that :p

**Comment by guedou** [comment]
Do you want me tu squash these 11 commits ?

**Comment by polybassa** [comment]
That would be great 👍
-- 
Viele Grüße

Nils Weiß

**Pull request merged**
