### PR TITLE
Cert: Tests, Python 3 and Cryptography update

### PR DESCRIPTION
**Pull request by gpotter2**
For an unknown reason, a few tests are only working locally (not on Appveyor/Travis).
However, they work under Travis Python 3.3

I cannot explain why. They are disabled through the 2nd commit

### CODE REVIEW

**Comment by guedou** [comment]
@gpotter2 is it related to you cryptography module version ?

**Comment by gpotter2** [comment]
After testing, those tests work under crypgraphy 1.8, and fail with 2.1.4

**Comment by gpotter2** [comment]
@guedou You are right, the API has been updated, and our calls have been deprecated. I've updated the ECDSA functions

**Comment by gpotter2** [comment]
Could you please restart the failing build ? Thanks!

**Comment by gpotter2** [comment]
Well codecov is broken on OSX Python 3 :/ not related to me though

**Comment by guedou** [comment]
Awesome PR!

**Pull request merged**
