### PR TITLE
Added Dot11ProbeResp.network_stats and parse country code

### PR DESCRIPTION
**Pull request by qingxp9**
1.Added Dot11ProbeResp.network_stats
2.parse country code in Dot11ProbeResp.network_stats and Dot11Beacon.network_stats

### CODE REVIEW

**Comment by gpotter2** [comment]
Hi & thanks for the PR !

We could take this opportunity to merge `Dot11Beaco  `and `Dot11ProbeResp`. How about something like

```python
class _Dot11NetStats(Packet):
    fields_desc = [
        LELongField("timestamp", 0),
        LEShortField("beacon_interval", 0x0064),
        FlagsField("cap", 0, 16, capability_list)
    ]

    def network_stats(self):
         [...]


class Dot11Beacon(_Dot11NetStats):
    name = "802.11 Beacon"


class Dot11ProbeResp(_Dot11NetStats):
    name = "802.11 Probe Response"
```

**Comment by gpotter2** [comment]
After some digging, it appears that your proposal doesn't follow the RFC related to 802.11 country information element

RFC

**Comment by gpotter2** [comment]
See https://github.com/secdev/scapy/pull/1876

**Comment by qingxp9** [comment]
Nice, that's more suitable

**Pull request closed without merging**
