### PR TITLE
Handle Exceptions in rdpcap()

### PR DESCRIPTION
**Pull request by guedou**
The issue was reported via oss-fuzz.

### CODE REVIEW

**Comment by gpotter2** [comment]
This is going to conflict with https://github.com/secdev/scapy/pull/2895. I've added adapter the changes from this PR regarding the PCAPNG part (only).

**Comment by guedou** [comment]
If you agree with these changes, I will rather merge this PR asap, and before #2895.

**Comment by gpotter2** [comment]
I'd prefer to fix the conflicts on smaller PRs (this one), rather than on #2895. Some changes of this PR are completly rewritten in #2895

**Comment by guedou** [comment]
In that case, the best solution is likely to take all changes from this PR and moves them to #2895 including the unit test.

**Comment by guedou** [comment]
Fixed in #2895

**Comment by guedou** [comment]
Fixed in #2895

**Comment by guedou** [comment]
Fixed in #2895

**Pull request closed without merging**
