### PR TITLE
Implement Postgres line protocol 3.0

### PR DESCRIPTION
**Pull request by tonybaloney**
**Checklist:**

-   [x] If you are new to Scapy: I have checked [CONTRIBUTING.md](https://github.com/secdev/scapy/blob/master/CONTRIBUTING.md) (esp. section submitting-pull-requests)
-   [ ] I squashed commits belonging together (will do once review completed)
-   [x] I added unit tests or explained why they are not relevant
-   [x] I executed the regression tests for Python2 and Python3 (using `tox` or, `cd test && ./run_tests_py2, cd test && ./run_tests_py3`)

fixes #xxx

### CODE REVIEW

**Comment by tonybaloney** [comment]
Ready for review

**Review by gpotter2 — DISMISSED** [review]
Nice PR !

**Comment by tonybaloney** [comment]
@gpotter2 that should fix them

**Comment by polybassa** [comment]
Please rebase to make your failed unit-tests work.

**Comment by polybassa** [comment]
LGTM

**Review by gpotter2 — APPROVED** [review]

**Pull request merged**
