### PR TITLE
bluetooth: Add EIR appearance

### PR DESCRIPTION
**Pull request by antoniovazquezblanco**
Just another Bluetooth EIR type :)

**Checklist:**

-   [x] If you are new to Scapy: I have checked [CONTRIBUTING.md](https://github.com/secdev/scapy/blob/master/CONTRIBUTING.md) (esp. section submitting-pull-requests)
-   [x] I squashed commits belonging together
-   [x] I added unit tests or explained why they are not relevant
-   [x] I executed the regression tests (using `cd test && ./run_tests` or `tox`)
-   [x] If the PR is still not finished, please create a [Draft Pull Request](https://github.blog/2019-02-14-introducing-draft-pull-requests/)

### CODE REVIEW

**Comment by XenoKovah** [comment]
Once again I just want to support this PR and say that I'd find this capability valuable for Bluetooth parsing via Scapy.

**Comment by gpotter2** [comment]
FTR this kind of duplicated comments on multiple PRs make me wonder: is this another JiaT75? That's a total of 4 PRs on bluetooth with weird mysterious users commenting they like it.

https://github.com/secdev/scapy/pull/4602
https://github.com/secdev/scapy/pull/4603
https://github.com/secdev/scapy/pull/4610
https://github.com/secdev/scapy/pull/4612

PR looks fine, but from now on I'm expecting a backdoor in the unit tests.

@guedou @p-l- Probably nothing, but please be careful.

**Comment by XenoKovah** [comment]
I'm not a very weird or mysterious user. I have a very easily googleable real name which is the same as this account name which is very attributable to my interest in Bluetooth. And Antonio (who's name is also very easily tied to a real identity through simple googling) is doing the changes rather than me, to help me out because he's contributed to Scapy before and knows your regression testing methodology which I don't.

**Comment by gpotter2** [comment]
I must apologise, that was rude. Sorry about that I tried to fix my comment but it's a bit late.

Thank you both for your interest in Scapy. Those PRs both look good, we'll get to them very soon.

**Review by gpotter2 — APPROVED** [review]
Thanks for the PR & sorry again.

**Comment by gpotter2** [comment]
The 2 PRs conflicted so I took the liberty to rebase against master, fixing the conflicts.

**Review by gpotter2 — DISMISSED** [review]

**Review by gpotter2 — APPROVED** [review]

**Comment by antoniovazquezblanco** [comment]
Nothing to worry about. From my side, I tried to keep it in small changes to make it easy to review and also because I do not have big slots of time lately. That is also a reason why copy paste seemed to be a little bit faster than writting custom messages for each PR.

I personally think it is a good thing you were a little bit paranoid. That speaks good of the process review you carry out. Thanks for the involvement and do not apologise for that please. If you need anything to verify my identity I am at your disposal.

Thank you again! :)

**Comment by gpotter2** [comment]
My initial (before the edit) comment was inappropriate, so there's really no need to thank me.

I'm fine with very succinct descriptions of PRs when the content is very clear and tests are included, which is always the case here. You don't need to verify anything don't worry :)

Anyways, Merry Christmas to you all.

**Pull request merged**
