### PR TITLE
[General] Doc improvements + mercurial logs removed 

### PR DESCRIPTION
**Pull request by gpotter2**
This PR:
- makes it easier to use the nice cool sphinx style to build locally the doc
- removes old mercurial logs

**Please ignore codecov: it's due to some random coverage tests depending of the sniffing functions**

### CODE REVIEW

**Comment by gpotter2** [comment]
@guedou I'm pretty sure you have canceled the travis tests :/

**Comment by guedou** [comment]
@gpotter2 sorry for mistake !

**Comment by gpotter2** [comment]
@guedou Thanks !
BTW: we should try to improve the coverage of `inet6.py` and `dhcp.py`, because as show here:
[here](https://codecov.io/gh/secdev/scapy/compare/55f7c4d20b8c86531a2059d2120d8ddaf3bf391b...5fc3b84603288f3c31c1c302fd6c79a70a7e7dc6/src/scapy/layers/inet6.py) and [here](https://codecov.io/gh/secdev/scapy/compare/55f7c4d20b8c86531a2059d2120d8ddaf3bf391b...5fc3b84603288f3c31c1c302fd6c79a70a7e7dc6/src/scapy/layers/dhcp.py), because some of the functions are randomly triggered depending of what it sniffs during the sniffing tests

**Comment by guedou** [comment]
Thanks for your patch ! I am not planning to work on inet.py or dhcp.py in a near future. My current goal is to finish PR #522 and improve dhcp6.py coverage.

**Pull request merged**
