### PR TITLE
GTP improvements

### PR DESCRIPTION
**Pull request by alexsult**
We added messages to the GTPv1 layer and created the GTPv2 support.
We now have 117 tests for these procotols and they are all passing.

### CODE REVIEW

**Comment by guedou** [comment]
Could I be picky and ask for A PEP-08'ification of the files ? This is not the case for most of Scapy code, but we try to enforce it for new patches.

Moreover, I wonder if the old unit tests work with this PR ? In other words, does it change the API ?

**Comment by Osso** [comment]
Or you could just run auto-pep8 on the whole project like this https://github.com/Osso/scapy/commit/9866f38a8156a1c2f5ffcaa402da21bb2851a754 ?

The old tests are quite puzzling to me...it's testing for str(gtp) which is non-existing.
The code has moved from gtp.py to gtp_v1.py so it might break some code but I would expect people to import from scapy.all and that will still work.
There's also other changes like IE_Cause which is losing Response and Rejection fields which do not exist in practice and in my specs.

**Comment by p-l-** [comment]
You cannot expect that people will import scapy only with `from scapy.all import *`. Some people/project import only parts of Scapy and we should not break that.

**Comment by guedou** [comment]
Converting Scapy to PEP-08 in a single run will prevent us to do some useful investigations on the code =)

In the old gtp.uts file, the `str(gtp)` at [line 14](https://github.com/secdev/scapy/blob/master/scapy/contrib/gtp.uts#L14) corresponds to the definiton at [line 9](https://github.com/secdev/scapy/blob/master/scapy/contrib/gtp.uts#L9).

**Comment by benllech** [comment]
Hi,

I am new to scapy..and github.. but was trying to change some basic values in a gtpv2 packet using the layer that was implemented. I was attempting to change the GRE_Key in the GTP-C F-TEID and also the GTP-U F-TEID.

My changes appeared ot be working and were displayed in show() printout but when the packet was  written to and viewed in wireshark the GRE_Key nested under the Bearer Context did not change...

Other changes under the Bearer context e.g. IP Address, were also not written to the pcap.


```
#!/usr/bin/env python

from gtp import *
from gtp_v1 import *
from gtp_v2 import *
from scapy.all import * 

pcap=rdpcap('gtpv2_CreateSessionReq.pcap')

packet = pcap[0]

packet.show()

#Outer GTP-C F-TEID
packet[GTPV2CreateSessionRequest][IE_FTEID].GRE_Key = 10
packet[GTPV2CreateSessionRequest][IE_FTEID].ipv4 = '100.100.100.100'

#Bearer context GTP-U F-TEID 
packet[GTPV2CreateSessionRequest][IE_BearerContext][IE_FTEID].GRE_Key = 10
packet[GTPV2CreateSessionRequest][IE_BearerContext][IE_FTEID].ipv4 = '100.100.100.100'

wrpcap('gtpv2_CreateSessionReq_changed.pcap', packet)

packet.show()
```

 Original PCAP

###[ GTPv2 Create Session Request ]###
              teid      = 0
              seq       = 1563290
              SPARE     = 0
              \IE_list   \
               |###[ IE F-TEID ]###
               |  ietype    = F-TEID
               |  length    = 9
               |  CR_flag   = 0L
               |  instance  = 0L
               |  ipv4_present= 1L
               |  ipv6_present= 0L
               |  InterfaceType= 6L
               |  **GRE_Key   = 0xb331de3c**
               |  **ipv4      = 192.142.175.222**
               |  \IE_list   \
               |   |###[ IE F-TEID ]###
               |   |  ietype    = F-TEID
               |   |  length    = 9
               |   |  CR_flag   = 0L
               |   |  instance  = 2L
               |   |  ipv4_present= 1L
               |   |  ipv6_present= 0L
               |   |  InterfaceType= 4L
               |   |  **GRE_Key   = 0xafec270d**
               |   |  **ipv4      = 192.142.12.123**


Output

###[ GTPv2 Create Session Request ]###
              teid      = 0
              seq       = 1563290
              SPARE     = 0
              \IE_list   \
               |###[ IE F-TEID ]###
               |  ietype    = F-TEID
               |  length    = 9
               |  CR_flag   = 0L
               |  instance  = 0L
               |  ipv4_present= 1L
               |  ipv6_present= 0L
               |  InterfaceType= 6L
               |  **GRE_Key   = 0xa**
               |  **ipv4      = 100.100.100.100**
               |###[ IE Bearer Context ]###
               |  ietype    = Bearer Context
               |  length    = 44
               |  CR_flag   = 0L
               |  instance  = 0L
               |  \IE_list   \
               |   |###[ IE F-TEID ]###
               |   |  ietype    = F-TEID
               |   |  length    = 9
               |   |  CR_flag   = 0L
               |   |  instance  = 2L
               |   |  ipv4_present= 1L
               |   |  ipv6_present= 0L
               |   |  InterfaceType= 4L
               |   |  **GRE_Key   = 0xa**
               |   |  **ipv4      = 100.100.100.100**

But as I say - the final pcap output does not have the Bearer Context change written...

Any info appreciated

**Comment by guedou** [comment]
@alexsult it seems that your last commit breaks unit tests. Could you have a look ?

**Comment by Osso** [comment]
I disagree on the file investigations. You can still look up the whole history even after converting scapy to pep8. git log --patch will give you all the changes.

**Comment by guedou** [comment]
Sorry, we won't merge this patch if you don't want to follow the rules.

**Pull request closed without merging**
