### PR TITLE
Autodoc update

### PR DESCRIPTION
**Pull request by gpotter2**
- automatically regenerate the API tree with each read the docs build = remove the `scapy/doc/api` folder
- do not generate the API reference in the PDF version of the doc
- remove scada from autodoc (too noisy)

### CODE REVIEW

**Comment by polybassa** [comment]
Hi, what do you mean with to noisy?

**Comment by gpotter2** [comment]
We might want to keep automative included afterwards, I'm still unsure.

@polybassa We almost hit the RAM limit when building the docs, so I'm trying to make up some space.
If you have a look at [the PDF version of the doc](https://readthedocs.org/projects/scapy/downloads/pdf/latest/), it shows what takes up the most space. Currently we have a few hundreds of pages taken by some Scada variables (`QPA_FLAG_COMPATIBLE_RESERVED_1, 2, 3`) which is the main problem.
I also wondered if the many OBD_PIDA4-alike fields were necessary, so to try it out I also removed the Automative doc.

It isn't really decided yet what to keep

**Comment by polybassa** [comment]
Hi @gpotter2, thanks for this explanation.  I'm fine if you exclude some stuff. Some of my files just contain tons of definitions.

**Comment by gpotter2** [comment]
The Travis `docs` test emulates the ReadTheDocs build. It's working alright

**Comment by guedou** [comment]
@polybassa are you fine with theses changes?

**Comment by polybassa** [comment]
I would be happy, if uds would be included in the documentation.

**Comment by gpotter2** [comment]
It is. I've reversed the automotive change, only scada was removed

**Comment by polybassa** [comment]
Thanks

**Pull request merged**
