### PR TITLE
Added Authentication payload type 

### PR DESCRIPTION
**Pull request by 5hadawan**
Added Authentication payload type. Adding this payload type I introduce an error fixed by the second commit.

### CODE REVIEW

**Comment by 5hadawan** [comment]
Add authentication payload type

**Comment by p-l-** [comment]
Hi! Thanks for this work. You might want to rebase against master? Also, could you add some tests to prevent future regressions?

**Comment by 5hadawan** [comment]
Hi,

Actually I used another payload description to add a new one (IKEv2_payload_AUTH) but I mistakly modified the original one (IKEv2_payload_VendorID) and miswrite the payload name (IKEv2_payload_Auth).  With my last three commits together everything works and I've tested it:
>>> IKEv2_payload_AUTH(load='test', auth_type=1).show()
###[ IKEv2 Authentication ]###
  next_payload= None
  res       = 0
  length    = None
  auth_type = RSA Digital Signature
  res2      = 0x0
  load      = 'test' 

Sorry for this mistake. In the future I'll test more before commit.

**Comment by gpotter2** [comment]
@5hadawan Hello. If you still want this PR to be taken in consideration, please update your code to match the current scapy version's requirements, otherwise this will be closed for inactivity.

**Comment by gpotter2** [comment]
@guedou This can Ben closed through https://github.com/secdev/scapy/pull/661

**Pull request closed without merging**
