### PR TITLE
[coverage] Better unit tests for inet6.py

### PR DESCRIPTION
**Pull request by guedou**
These tests are improving the coverage of IPv6 related layers and tools. There are some more tests to write, but this PR is OK for now.

### CODE REVIEW

**Comment by gpotter2** [comment]
You should try with 1971 instead of 1951 (windows does not like dates before epoch)

**Comment by guedou** [comment]
@gpotter2 thanks ! I will try to use the TimStampField from ntp.py

**Comment by guedou** [comment]
@p-l- could you restart AppVeyor tests ? It seems that I am not authorised.

**Comment by gpotter2** [comment]
@guedou I think there's an issue in one of the tests, to make it crash like this...
In fact, I suspect the automaton tests to randomly become stuck...

We may want to migrate the automaton tests to a `automaton.uts` file, just to be sure

**Comment by gpotter2** [comment]
@guedou Once https://github.com/secdev/scapy/pull/526 is merged, you may re-run the appveyor tests=

**Comment by guedou** [comment]
@p-l- could you restart the appveyor tests ?

**Comment by gpotter2** [comment]
@guedou You should rebase your repositories, the code this one is using looks very old
(`git pull --rebase upstream master`)

**Pull request merged**
