### PR TITLE
Defer import of matplotlib until needed

### LINKED ISSUE #3578: matplotlib is loaded even if scapy is running headless
### Brief description

`matplotlib` is quite a heavy dep for  it not being used in this case.

Its only being loaded because of PYX
```
  File "/Users/bdraco/home-assistant/venv/lib/python3.9/site-packages/scapy/packet.py", line 49, in <module>
    from scapy.extlib import PYX
```

ps before loading `matplotlib`

root      4570  3.0  0.0  36552 12320 pts/1    T    14:40   0:00 python3

ps after loading `matplotlib`

root      4597 11.0  0.2 268380 43948 pts/1    Tl   14:41   0:00 python3

### Scapy version

2.4.5

### Python version

3.9

### Operating system

Linux

### Additional environment information

_No response_

### How to reproduce

import scapy.packet

### Actual result

_No response_

### Expected result

_No response_

### Related resources

_No response_

### PR DESCRIPTION
**Pull request by bdraco**
Similar to how `cartopy` and `geoip2` are handled, defer import of matplotlib until needed.  

Testing with `import scapy.packet` 

Before:
`bdraco           52845   0.0  0.2 409457040  61264 s004  T    10:00AM   0:00.22 /opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/Resources/Python.app/Contents/MacOS/Python`

After:
`bdraco           52900   0.0  0.1 409195664  46368 s004  T    10:01AM   0:00.17 /opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/Resources/Python.app/Contents/MacOS/Python`

fixes #3578

matplotlib has a heavy dep chain

I did manual testing to make sure I could still generate images when `matplotlib` installed, and verified the warning at `-H` startup still works when its not

### CODE REVIEW

**Review by polybassa — APPROVED** [review]

**Comment by bdraco** [comment]
Thanks !

**Review by gpotter2 — CHANGES_REQUESTED** [review]
Sorry for the delay.

- Could you move the new file to `scapy/libs/` ?
- Would you mind doing the same for PYX to remove `extlib` the remaining entirely?

Would be awesome, thanks a lot

**Comment by bdraco** [comment]
Retested to make sure I could still generate a plot with `a.plot(lambda x:x[1].id)`

**Comment by bdraco** [comment]
I've tried so many incantations with py27 but haven't been able to get it to patch correctly

**Comment by bdraco** [comment]
Should be good now. There was a name collision in the first refactor that py27 couldn't handle

**Review by gpotter2 — APPROVED** [review]
Thanks for the PR !

**Pull request merged**
