### PR TITLE
[Python 2 to 3] Add required b's

### PR DESCRIPTION
**Pull request by gpotter2**
As requested, first part of https://github.com/secdev/scapy/pull/674 splitted

This one:
- add most of the b"" required marks
- add some io.open imports

### CODE REVIEW

**Comment by p-l-** [comment]
Can you explain why the `from io import open` is needed?

**Comment by gpotter2** [comment]
Using the default open on python 3 requires either to use the 'encoding' parameter, which does not exist on python 2, or to set 'rb' but then we get Unicode in python 2.

The io.open returns the same encoding (UTF8) on python 2 and 3.

**Comment by p-l-** [comment]
@gpotter2 I don't think I get it. In Python 2, using `io.open(..., "rb")` seems to give the same results than `open(..., "rb")`:

```Python
import io
assert io.open('/etc/passwd', 'rb').readline() == open('/etc/passwd', 'rb').readline()
assert io.open('/etc/passwd', 'r').readline() == open('/etc/passwd', 'r').readline()
```

**Comment by gpotter2** [comment]
Oh you seems right. I guess simply adding the "rb" would do the trick.

**Comment by p-l-** [comment]
Ping me when you've updated the PR in that case!

**Comment by gpotter2** [comment]
@p-l- Updated

**Pull request merged**
