### PR TITLE
Parse MPLS in MPLS Payload

### PR DESCRIPTION
**Pull request by amitn**
1. Try to decode payload only if bottom of stack bit is set
2. Bind MPLS/MPLS with bottom of stack bit not set
3. Bind MPLS/IP with bottom of stack set

### CODE REVIEW

**Comment by gpotter2** [comment]
I've already seen that before:
https://github.com/secdev/scapy/pull/504

**Comment by amitn** [comment]
@gpotter2 I will modify the changes to be synced with #504 

I have also included tests, anything else is needed ?

**Comment by amitn** [comment]
@guedou I saw the comments in #504, regarding the code coverage, how do I cover guess_payload_class ? do I need to provide a raw and pass it to the class ?

    k = MPLS('\x00\x06@\xff\x00\x001\x00E\x00\x00\x14\x00\x01\x00\x00@\x00|\xe7\x7f\x00\x00\x01\x7f\x00\x00\x01')
    k.summary()
    'MPLS / MPLS / 127.0.0.1 > 127.0.0.1 hopopt'

**Comment by guedou** [comment]
To trigger it, you can create a packet with ../MPLS()/IP() for example, build it with str() then dissect it.

**Comment by amitn** [comment]
Tests added.

**Comment by guedou** [comment]
Could you rebase against HEAD ? A recent PR modified `guess_payload_class() `in a better way.

Also, could you rewrite your test sin to build an dissect (as it is done in mpls.uts for example),  remove calls to `.show()`, and move them to `mpls.uts` ?

Thanks.

**Comment by amitn** [comment]
Changes are already in by cc02b632bbf412f306df4bb609fbcb92ebf95283

**Pull request closed without merging**
