### PR TITLE
Remove FieldListField's i2m as discussed on #1661

### PR DESCRIPTION
**Pull request by gpotter2**
- fixes https://github.com/secdev/scapy/issues/1661

See this comment: https://github.com/secdev/scapy/issues/1661#issuecomment-694515723

### CODE REVIEW

**Review by guedou — CHANGES_REQUESTED** [review]
Could you add a unit test that triggers the original issue?

**Comment by guedou** [comment]
It looks like the provided example works fine on master.

**Comment by gpotter2** [comment]
Is this a problem?

**Comment by guedou** [comment]
No a problem, but I don't understand why you are adding a test that works on master. Could you add something that fails and that is fixed by this PR?

**Comment by gpotter2** [comment]
This PR removes something that was useless. It doesn't really change the behavior it was just inconsistent,

The linked issue was fixed by other previous commits (I suspect the new cache that you did). I just added the test to make sure we can close it safely.

**Comment by guedou** [comment]
Understood! Thanks for your explanation.

**Review by guedou — APPROVED** [review]

**Pull request merged**
