### PR TITLE
Fix operation when use_pcap and use_dnet are true

### PR DESCRIPTION
**Pull request by dhgutteridge**
Resolves a failure triggered by "make test" on NetBSD.

### CODE REVIEW

**Comment by dhgutteridge** [comment]
Sorry, this patch may not be sufficient; it may need further consideration. In the previous revision [(https://github.com/secdev/scapy/commit/4bd1d8f3e346c06f0251c4117ba0f6ef5c72d07a)](https://github.com/secdev/scapy/commit/4bd1d8f3e346c06f0251c4117ba0f6ef5c72d07a),
`from scapy.arch.bpf.core import *`
was moved so it's now called unconditionally for BSD. That kind of conflicts with the expression of the existing code block at line 26 that I'm proposing to change.

I should have also been more clear in my initial comment: the impetus for me looking into this was spurred by scapy 2.4.2 failing with "make test" on NetBSD. That won't be the case anymore with the current state of this code. But I raised this in case it was still relevant in other contexts, though I see dnet is deprecated.

**Comment by gpotter2** [comment]
Thanks for the PR, though I'm not sure if the fix is correct.

Calling @guedou for this one. He's done almost all *BSD integration, and has a worked intensively into improving the *BSD support since 2.4.2, and fixing the tests.

**Comment by dhgutteridge** [comment]
My impression is something like it may be needed for any OSes covered by your "SOLARIS" definition, rather than BSDs, at this point. Linux and BSDs end up getting the definition of get_if_raw_addr() as-is without it, but I don't see where that would be true if "SOLARIS" is set. Having said that, I don't have a SunOS environment to test in at present. And I'm far from an expert on your code base. (I'm looking at it from a downstream packager's perspective, for pkgsrc.org, which does support various SunOS contexts, as well as BSDs.)

**Comment by gpotter2** [comment]
I am almost convinced what is called "solaris" is broken.

There are some remains of what seems to have been merged before I even came on the project (2016), but it really never has been updated. And I don't think we've tested it since something like 2.3.3

**Comment by guedou** [comment]
Thanks for this PR.

What is “make test”? Could you describe what is the issue and how to reproduce it?

**Comment by dhgutteridge** [comment]
> Thanks for this PR. What is “make test”? Could you describe what is the issue and how to reproduce it?

First, my apologies, I was describing it from my perspective. What's to me "make test" is a wrapper that calls your regression test suite. So it's invoking your `test/run_tests` script, with SCAPY_USE_PCAPDNET=yes set, and a specific path to Python 2.7.16. (The wrapper environment pre-requisites include that the Python bindings for pcap and dnet are also installed and visible.)

With Scapy 2.4.2, this resulted in several different exceptions triggered, one of which was because `get_if_raw_addr()` was not defined anywhere. Since use_pcap and use_dnet were both true, it was not imported in `arch/__init__.py` in the block at line 26, nor in the block at line 57. As of the latest revision to `arch/__init__.py` (in Scapy 2.4.3rc3), this should no longer be the case for BSD, because
`from scapy.arch.bpf.core import *` was moved so it's now invoked unconditionally.

However, from code inspection, it appears if `test/run_tests` is called with SCAPY_USE_PCAPDNET=yes in Solaris environments, this same exception could still occur, since there's still no code path that would pull in a definition of `get_if_raw_addr()`. Having said that, I don't have such a test environment at present. But this is what I was trying to address: providing a guaranteed fallback definition.

Separately, the code that imports `get_if_raw_addr()` in this file is a bit contradictory. I'm not sure if it's intentional that there are duplicate points where the same definition or a different definition is included? With BSD, both line 28 and line 59 will pull in a definition of that function, assuming use_pcap and use_dnet were both false. That's harmless, but confusing to follow, given the intention in the block at line 26 is to only pull in that definition if use_pcap and use_dnet were both false, then the code does so regardless at line 59. Similarly, on Linux, line 28 may pull in `bpf.get_if_raw_addr()` and line 56 will pull in `linux.get_if_raw_addr()`, both into the same namespace. It's unclear to a prospective contributor what's intended.

Last, while a use_dnet=true use case may not be anticipated at this point on Linux, this pull request has revealed that one of your SCAPY_USE_PCAPDNET=yes Travis test targets doesn't install the necessary packages to exercise some related code paths in the environment that's defined. ([https://travis-ci.com/secdev/scapy/jobs/215941973](https://travis-ci.com/secdev/scapy/jobs/215941973) .) I'm going to add a fix for that to this PR, to confirm that resolves the test failure. If it does, you may want to add that separately. (Or I could just resubmit separately.)

I suppose, at this point, it would have made more sense for me to open this as an issue, rather than a pull request. I wasn't expecting this to get so complicated, sorry.

The original exception that started me looking into this, by the way, was this:

```
### Booting scapy...
[CRITICAL]: Cannot import Scapy: global name 'get_if_raw_addr' is not defined
Traceback (most recent call last):
  File "./../scapy/tools/UTscapy.py", line 882, in main
    from scapy import all as scapy
  File "/home/disciple/pkgsrc/net/scapy/work/scapy-2.4.2/scapy/all.py", line 27, in <module>
    from scapy.route import *
  File "/home/disciple/pkgsrc/net/scapy/work/scapy-2.4.2/scapy/route.py", line 194, in <module>
    conf.route = Route()
  File "/home/disciple/pkgsrc/net/scapy/work/scapy-2.4.2/scapy/route.py", line 27, in __init__
    self.resync()
  File "/home/disciple/pkgsrc/net/scapy/work/scapy-2.4.2/scapy/route.py", line 35, in resync
    self.routes = read_routes()
  File "/home/disciple/pkgsrc/net/scapy/work/scapy-2.4.2/scapy/arch/unix.py", line 104, in read_routes
    ifaddr = get_if_addr(netif)
  File "/home/disciple/pkgsrc/net/scapy/work/scapy-2.4.2/scapy/arch/__init__.py", line 31, in get_if_addr
    return inet_ntop(socket.AF_INET, get_if_raw_addr(iff))
NameError: global name 'get_if_raw_addr' is not defined
```

**Comment by dhgutteridge** [comment]
> Last, while a use_dnet=true use case may not be anticipated at this point on Linux, this pull request has revealed that one of your SCAPY_USE_PCAPDNET=yes Travis test targets doesn't install the necessary packages to exercise some related code paths in the environment that's defined. (https://travis-ci.com/secdev/scapy/jobs/215941973 .) I'm going to add a fix for that to this PR, to confirm that resolves the test failure. If it does, you may want to add that separately. (Or I could just resubmit separately.)

My second commit fixed that test environment failure: [https://travis-ci.com/secdev/scapy/jobs/217101965](https://travis-ci.com/secdev/scapy/jobs/217101965).

**Comment by gpotter2** [comment]
We now have https://github.com/secdev/scapy/pull/2145
For Solaris though. The PRs are going to conflict

**Comment by dhgutteridge** [comment]
> We now have #2145
> For Solaris though. The PRs are going to conflict

Hmm, I see you referenced this PR in #2145, but it GitHub didn't send me a notification about it.

What I'll do then is close this, and re-open parts of it as separate items. The questions about code style/inclusion should be an issue, not a PR. The Travis config item can be an isolated PR. (That is, there's nothing in your test coverage as-is that would demand it, but should you wish to cover dnet, you'd need it.)

**Pull request closed without merging**
