### PR TITLE
Scapy docs massive cleanup

### PR DESCRIPTION
**Pull request by gpotter2**
Massive doc overhaul:
- split the bottom of `Advanced usage` into separate layer-specific files
- Refactor the documentation sidebar (aka `:toctree:`)
- remove references to the deprecated Scapy 1.X
- fix permissions on polybassa 's `.svg` files + replace old `Usage` screenshot by fancy SVG animation in `Introduction`
- adds scapy versions / python version graph
- fixes windows logs when winpcap/npcap ins't installed + color of logs
- small fixes in doc
- remove the tiny "Python tutorial" from => it's not useful, and is incomplete. We're illegitimate to give this lesson (in `Introduction`)
- Document `#scapy.contrib.*`

SVGs animation are light, well-supported (except on Microsoft Edge, but it isn't used much, and will be soon switching to a Chromium implementation which supports it), and make the doc much more readable. It was first used in the Automative doc, and it's a great idea. I think we could try to implement them more often.

### Screenshots

image

### CODE REVIEW

**Comment by gpotter2** [comment]
This is ready to be merged.
The PR is simple enough, mostly doc fixes.

I first tried to make those really cool Gantt-alike graphs, that Ubuntu has for instance, but ended up with a more simple table

**Comment by gpotter2** [comment]
@guedou @p-l- That should be mergeable. What do you think of the table ? Any suggestions?

**Comment by gpotter2** [comment]
@guedou @p-l- Sorry for the ping, I'd like to have this merged.

**Comment by gpotter2** [comment]
I’ve rebased to fix the conflicts

**Comment by guedou** [comment]
As far as I remember, v2.3.3 was the latest version to support Python 2.5.

**Comment by gpotter2** [comment]
You are right
AADED430-74BD-41DE-BF9F-990F3530F42B
70356252-AD02-41CB-A1D3-97941B47B71E
I’ve included the .obs used to make the chart, and regenerate the image. I’ll update it when I get the time

**Comment by polybassa** [comment]
@epozzobon made a script to convert `svg` files from `termtosvg` to `webm` videos. If this is helpful, we can share these scripts for the documentation. On advantage of videos is play, pause and scrolling.

**Comment by polybassa** [comment]
Many hands on examples are similar to unit tests. Do you think, it would be possible to generate hands on examples from `uts` files? This would have the advantage, that even the code snippets in the documentation are checked from the CI environment. It's very annoying if code snippets in the documentation are outdated.

I could imagine something like a special tag on a unit test step. This will indicate a new script to export this test as example snippet. The test name could than be used as headline. Explanation can be between the code as comments.

**Comment by guedou** [comment]
@polybassa I like our idea of using the unit tests for the documentation!

**Comment by polybassa** [comment]
The easiest way would probably be a script, which checks for a specific tag and then copies the related unit test as `.rst` file into a specific folder. The documentation can then include this file as example snippet.

**Comment by guedou** [comment]
Can I merge this?

**Comment by gpotter2** [comment]
Should be mergeable !

**Pull request merged**
