### PR TITLE
Add reserved and user-defined function support

### PR DESCRIPTION
**Pull request by thmsaurel**

### CODE REVIEW

**Comment by p-l-** [comment]
I don't understand the point to have entries for "unknown" values in the enum fields.

**Comment by thmsaurel** [comment]
right now is for nothing. Lot of this entries are proprietary. So as long as nobody say for which resources it is, it have to stay as an unknown entry.

**Comment by thmsaurel** [comment]
People will can change the value of the dict directly from their application without modify scapy file structure. When more protocols will be discovered (for example, a Rockwell code function, or a Siemens one), all you have to do is change the string value. The object is already created.

**Comment by smainand** [comment]
Hello,
I think the goal of this is to give the information about which category a function code belongs to (even if its meaning is unknown for now) ;
A way to avoid adding all the duplicated lines would be to add the possibility to add an optional default value for the enum representation, by modifying the i2repr* of the *EnumField() classes. This could look like this (tested at line l.766 in "scapy/fields.py" ):
```python
def i2repr_one(self, pkt, x, default_val_enum=None):
    if self not in conf.noenum and not isinstance(x,VolatileValue) and x in self.i2s:
        return self.i2s[x]
    elif default_val_enum:
        return default_val_enum
    return repr(x)
```
and used as follow:
```python
class ModbusPDUUserDefinedFunctionCodeRequest(Packet):
    name = "User-Defined Function Code Request" 
    fields_desc = [ByteEnumField("funcCode", 0x00, _userdefined_funccode_request, 
                                 "Unknown UserDefined Function Code"),]
```
Does such a functionality would make sense in Scapy ?

ps: by the way, ```elif``` could be use at line 1088 and 1090 in scapy/contrib/modbus.py

**Comment by p-l-** [comment]
I think it's best to leave "unknown" entries undefined.

**Comment by thmsaurel** [comment]
I can remplace by `elif` in place of `if` at line 1088 and 1090 in `scapy/contrib/modbus`

**Comment by thmsaurel** [comment]
I can let empty the user-defined dictionary but i think it could be interesting to keep the "unknown" entries of the reserved one.

**Comment by guedou** [comment]
@p-l The unknown entries look weird, yet they are useful to identify the class of modbus functions. @smainand proposal seems legit. Another way to go could be to define ModbusByteEnumField to handle the "unknown" message.

**Comment by p-l-** [comment]
Maybe a specific field could be a better option, displaying "funCode 0xXX (user-defined)". I really don't like these huge dict objects with almost no information.

**Comment by thmsaurel** [comment]
I have change the `ByteEnumField` inside user-defined class by a `ModbusByteEnumField`.

```python
class ModbusByteEnumField(EnumField):
    __slots__ = "defEnum"

    def __init__(self, name, default, enum, defEnum):
        EnumField.__init__(self, name, default, enum, "B")
        defEnum = self.defEnum = defEnum

    def i2repr_one(self, pkt, x):
        if self not in conf.noenum and not isinstance(x, VolatileValue) \
                    and x in self.i2s:
            return self.i2s[x]
        if self.defEnum:
            return self.defEnum
        return repr(x)
```

**Comment by thmsaurel** [comment]
Hi guys,
Are you agree with the `ModbusByteEnumField` ?

**Comment by gpotter2** [comment]
@pbat0908 Hello. If you still want this PR to be taken in consideration, please update your code to match the current scapy version's requirements, otherwise this will be closed for inactivity.

**Comment by thmsaurel** [comment]
Sorry for the delay, an updated version of my code is used into the #374 PR. So if it is taken in consideration, there is no need to merge my PR with scapy.

**Comment by gpotter2** [comment]
Good then :)

**Comment by smainand** [comment]
Hello @guedou , this PR can be closed: its content has already been merged through the PR #716.

**Comment by thmsaurel** [comment]
I'm agree

**Comment by guedou** [comment]
Thanks both of you for your comments!

**Pull request closed without merging**
