### PR TITLE
Improve automotive related unit tests [ready for merge]

### PR DESCRIPTION
**Pull request by polybassa**
This PR

* refactors the `drain_bus` function
* ensures that all blocking calls like `wait()` or `join()` have a timeout set,
* ensures that all sockets will be closed after a test (using with)
* changes some timings in the hope that this will make some tests more reliable
* adds a minor improvement to ISOTPScan

### CODE REVIEW

**Comment by polybassa** [comment]
This is another refactoring PR. Sorry that I opened two PRs for the same stuff, but I wanted to see, if changes of this PR cause instability.

**Comment by gpotter2** [comment]
Could you remove all the `#noqa: E501` and keep the `#flake8: noqa` (for this PR only?)

I'll add the the noqa file-wise in https://github.com/secdev/scapy/pull/2438/files so those won't be required.

For now please only fix the non-E501 issues (there were padding spaces / missing spaces with operators)

**Comment by polybassa** [comment]
What do you mean with "keep the `#flake: noqa`"? I don't know what/how I should change that PR.

**Comment by gpotter2** [comment]
That's alright I've done what I wanted in https://github.com/secdev/scapy/pull/2438. You can drop the changes

**Comment by polybassa** [comment]
Thanks. Should I remove all trailing noqa: statements, since they are in the flake configuration of your PR?


On January 26, 2020 10:12:27 AM GMT+01:00, Gabriel <notifications@github.com> wrote:
>That's alright I've done what I wanted in
>https://github.com/secdev/scapy/pull/2438. You can drop the changes
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/secdev/scapy/pull/2428#issuecomment-578483968

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by gpotter2** [comment]
You can cancel all changes done to those files, I'll handle it.

**Comment by polybassa** [comment]
Thanks!
I'll remove all flake8 related changes from this PR.

**Comment by polybassa** [comment]
This PR is done from my side. The tests are failing because of other problems, at the moment

**Comment by polybassa** [comment]
Is it possible to increase the timeout time for appveyor? I recognize failed builds after 15 min.

**Comment by gpotter2** [comment]
It's now 25minutes

**Comment by polybassa** [comment]
Thanks. This should fix it

**Comment by polybassa** [comment]
Finally, this PR is ready for merge. Hopefully this fixes some errors during random builds. Please let me know, if automotive related tests go wrong after this PR is merged.

**Pull request merged**
