### PR TITLE
Avoid mutating globals - rework

### PR DESCRIPTION
**Pull request by gpotter2**
fix https://github.com/secdev/scapy/issues/2680
fix https://github.com/secdev/scapy/pull/2681

### CODE REVIEW

**Comment by graingert** [comment]
I don't understand why you'd *ever* want to mutate globals like this

Users in the interactive console can just import the features that they need and assign them

**Comment by guedou** [comment]
@graingert that's a very aggressive way of asking a simple question. Please be careful with the tone you use. Thanks.

**Comment by graingert** [comment]
@guedou apologies for the tone, I simply don't understand the design choice here.

mutating builtins effects every single module and can cause some strange errors, an alternative would be altering just the locals in `code.InteractiveInterpreter.locals`

**Comment by gpotter2** [comment]
- The `load_*` functions in Scapy are mostly historical, and have been tampering with the builtins for as long as I can remember. They are used as an alternative to `from scapy.layers.X import *`, especially in the unit tests and by users within the console. To work during the tests, you need them to inject things in the builtins. Most people won't use them anyways
- `conf.use_pcap` has a strange behavior because it replaces the sockets and low-level related functions to use Libpcap as a backend instead of the native backend. When used in real code, you are supposed to change it before importing anything else from scapy so that the imports are correct. However in the console it must be able to replace existing variables. Because the `load_*` functions are already available and fulfil this purpose, I didn't bother implementing an extra function only for this case that would use IPython specific variables.

**Pull request merged**
