### PR TITLE
Fix handle inheritance for py27 (more appropriate and save version of #1138 hack, fixes #1136)

### LINKED ISSUE #1136: [Windows] POWERSHELL_MANAGER is never closed explicitly
scapy-2.4.0rc4.dev58-py2.7
Windows 7

POWERSHELL_MANAGER isn't closed in arch/windows/__init__.py

That's a problem, because subprocess used inherits open files. The files can't be deleted without waiting for scapy to end (sleep-wait-repeat).

I've added POWERSHELL_MANAGER.close() near the bottom of __init__.py and it solved the problem.

Steps to reproduce:
1. Create a file.
2. Replace sys.stdout/stderr with it (I'm doing a tee)
3. Import scapy
4. Try to remove created file after closing it

Observed behaviour:
- exception - file in use, can't be deleted

Expected behaviour:
- file is deleted just fine

Reproducible:
- always

### PR DESCRIPTION
**Pull request by karpierz**
Work in progress...! Created for perform scapy tests.

### CODE REVIEW

**Comment by gpotter2** [comment]
Hi !
Could you share a case where this is real useful ?
This is the cornercase of a cornercase... If it takes that long to implement, I think we could skip it and tell people to use python 3...

**Comment by karpierz** [comment]
1. Unfortunately (current envs in our customers, backward compatibility etc) in our cases Python2 will be used for a years.
2. Your hack is limited for arbitrary/hardcoded count of descriptors
3. It applies only file descriptors, but each kind of descriptor should be taken into account.
4. It is not corner case. In our and our customers production environments it causes that each of the thousands tests has failed. It is significant regression in relation to scapy<=2.3.2
5. Your hack does not restore the previous settings. It causes a problem for descriptors which previously
was inherited by the other subprocesses so (not only theoretically - espoecially for stdin/out/err) can change behaviour of existing programs and its outputs.
PS: To avoid some problem also for Pyhon3 I suggest and vote to avoid support for very buggy Python3.3

**Comment by karpierz** [comment]
Gabriel
So maybe first more compromised ;) #1234

**Comment by karpierz** [comment]
Temporary close due to #1234 proposal

**Pull request closed without merging**
