### PR TITLE
Properly discard close_pipe on socket failure

### PR DESCRIPTION
**Pull request by gpotter2**
fix https://github.com/secdev/scapy/issues/3631

I tried to put this code in the place the if would be called the least often, yet work.

### CODE REVIEW

**Review by guedou — DISMISSED** [review]
Do you think that it is possible to test this?

**Comment by gpotter2** [comment]
It is actually, I've added a test.

**Comment by p-l-** [comment]
@gpotter2 looks like it does not work with Windows

**Comment by gpotter2** [comment]
@p-l- You're right. should be fixed by now.
Please ignore the pypy2 failure

**Pull request merged**
