### PR TITLE
Fix PyPi dist

### PR DESCRIPTION
**Pull request by gpotter2**
Should fix https://github.com/secdev/scapy/issues/1778

This PR:
- fixes `get_long_description`
- uses setuptools if available to get markdown working on PyPi
- fixes README.md
- adds a dist test using `twine check`

### CODE REVIEW

**Comment by gpotter2** [comment]
@guedou According to twine, if the markdown is not perfectly built (the spacing fixes count as errors), it won’t be rendered on Pypi

**Comment by guedou** [comment]
Good catch! I am afraid that the Scapy logo won't be rendered correctly. What do you think of the following patches ?

```
git diff README.md
diff --git a/README.md b/README.md
index 240b5547..14974bef 100644
--- a/README.md
+++ b/README.md
@@ -2,6 +2,8 @@
   <img src="doc/scapy_logo.png" width=200>
 </p>
 
+<!-- start_ppi_description -->
+
 # Scapy
 
 [![Travis Build Status](https://travis-ci.org/secdev/scapy.svg?branch=master)](https://travis-ci.org/secdev/scapy)
@@ -110,7 +112,7 @@ Python modules, such as `matplotlib` or `cryptography`. See the
 [documentation](http://scapy.readthedocs.io/en/latest/installation.html) and
 follow the instructions to install them.
 
-<!--- stop_ppi_description -->
+<!-- stop_ppi_description -->
 
 ## Contributing

```
```

git diff setup.py
diff --git a/setup.py b/setup.py
index c21e3eac..66dd674d 100755
--- a/setup.py
+++ b/setup.py
@@ -44,7 +44,9 @@ archive_util.ARCHIVE_FORMATS["ezip"] = (
 def get_long_description():
     try:
         with io.open(os.path.join(os.path.dirname(__file__), "README.md"), encoding="utf-8") as f:
-            return f.read().partition("<!--- stop_ppi_description -->")[0]
+            readme = f.read()
+            description = readme.partition("<!-- start_ppi_description -->")[2]
+            return description.partition("<!-- stop_ppi_description -->")[0]
     except IOError:
         return None
```

**Comment by guedou** [comment]
We could also apply this one:

```
git diff setup.py
diff --git a/setup.py b/setup.py
index c21e3eac..634842aa 100755
--- a/setup.py
+++ b/setup.py
@@ -41,13 +41,18 @@ def make_ezipfile(base_name, base_dir, verbose=0, dry_run=0, **kwargs):
 archive_util.ARCHIVE_FORMATS["ezip"] = (
     make_ezipfile, [], 'Executable ZIP file')
 
+
 def get_long_description():
     try:
-        with io.open(os.path.join(os.path.dirname(__file__), "README.md"), encoding="utf-8") as f:
-            return f.read().partition("<!--- stop_ppi_description -->")[0]
+        filename = os.path.join(os.path.dirname(__file__), "README.md")
+        with io.open(filename, encoding="utf-8") as f:
+            readme = f.read()
+            description = readme.partition("<!-- start_ppi_description -->")[2]
+            return description.partition("<!-- stop_ppi_description -->")[0]
     except IOError:
         return None
 
+
 SCRIPTS = ['bin/scapy', 'bin/UTscapy']
 # On Windows we also need additional batch files to run the above scripts
 if os.name == "nt":
```

**Comment by gpotter2** [comment]
@guedou Updated accordingly

**Comment by guedou** [comment]
Thanks for these commits!

**Pull request merged**
