### PR TITLE
Remove raw()

### PR DESCRIPTION
**Pull request by gpotter2**
*This PR is an old rebase*

The `raw` function is supper inefficient, and can quite easily be avoided. It was a bad idea

This PR comes with an average improvement of dissection speed of 8% 

TODO: fix last tests

### CODE REVIEW

**Comment by p-l-** [comment]
I don't get it. Why don't we just add `raw = bytes` to preserve the API?

**Comment by gpotter2** [comment]
What was nice about `raw` is that it handled both `bytes(IP())` and `bytes(“test”, encoding=“utf8”)` cases.

It’s a case by case :/

We can still set `raw=bytes` for people that used it on 2.4.0

**Comment by p-l-** [comment]
I think it would be great if we kept `raw()` for people using it, and I'd rather continue documenting it instead of `bytes()`: I like the idea that it is **not** a type, so that if Python 4 changes again how raw bytes are manipulated, or if one day we decide to use another type, we won't have any problem with that.

**Comment by guedou** [comment]
Can you explain the issue with the current `raw()` implementation?

**Comment by gpotter2** [comment]
It’s slow: we do a try except on so many calls:/

If you `cProfile.run` a dissection of a PCAP, the most time-consuming function is the `raw` call.

**Comment by guedou** [comment]
I understand. What is the improvement compared to the script used in #642 ?

**Comment by gpotter2** [comment]
This needs to be rethink. Dissection is about 8% faster but building is now slower.

**Pull request closed without merging**
