### PR TITLE
Fix ISOTP UnitTest

### PR DESCRIPTION
**Pull request by polybassa**
Revert "isotp test removed" and removed the automatic intallation of a Linux Kernel Module on Travis

This reverts commit 79aaf13903c1b4a2082654e0f7310d8ff8c6e1d8.

### CODE REVIEW

**Comment by guedou** [comment]
I think that this PR could be enhanced by locking `sr1()` when the module kernel is not present. This will make some of the tests work on Travis.

**Comment by polybassa** [comment]
Hi, this is a good idea. Where should the lock of sr1() happen? In the ISOTPSocket class or in the unit tests? I think it would be good to lock the send and receive functions in the class directly. But in this case, this lock would require a new PR. If you think so aswell, I would like to get this PR in, since it's not touching anything, when the kernel module isn't present. And I would come up with a new PR to improve the ISOTPSocket with a lock of the send and receive functions, it the kernel module is not present. If you want, I can create an issue as todo, to keep track of this enhancement.

**Comment by gpotter2** [comment]
He means `mocking`

**Comment by polybassa** [comment]
Could you please point me to an example how to mock correctly? Since I never did it, I want to do it the right way.

**Comment by gpotter2** [comment]
Here are a few advanced examples of what we have in the tests:


- Make `sr` return a specific list of packets:
```python
# The use of decorators is the easiest way: they are auto-created and stopped ==> active only from inside the function
@mock.patch("scapy.layers.inet.sr")
def test_report_ports(mock_sr):
    def sr(*args, **kargs):
        return [(IP()/TCP(dport=65081, flags="S"), IP()/TCP(sport=65081, flags="SA")),
                (IP()/TCP(dport=65082, flags="S"), IP()/ICMP(type=3, code=1)),
                (IP()/TCP(dport=65083, flags="S"), IP()/TCP(sport=65083, flags="R"))], [IP()/TCP(dport=65084, flags="S")]
    mock_sr.side_effect = sr
    # Below is the advanced test, not related
    report = "\\begin{tabular}{|r|l|l|}\n\hline\n65081 & open & SA \\\\\n\hline\n?? & closed & ICMP type dest-unreach/host-unreachable from 127.0.0.1 \\\\\n65083 & closed & TCP R \\\\\n\hline\n65084 & ? & unanswered \\\\\n\hline\n\end{tabular}\n"
    assert(report_ports("www.secdev.org", [65081,65082,65083,65084]) == report)

test_report_ports()
```

- Make any the socket return the same packet in loop:
```python
# Usage without decorators
mocked_l2listen = mock.patch("scapy.config.conf.L2listen", return_value=Bunch(close=lambda *args: None, fileno=lambda: r, recv=lambda *args: Raw("data")))
mocked_l2listen.start()
# Below is the advanced test, not related
try:
    p = PipeEngine()
    s = SniffSource()
    d1 = Drain(name="d1")
    c = QueueSink(name="c")
    s > d1 > c
    p.add(s)
    p.start()
    assert c.q.get(2)
    p.stop()
finally:
    mocked_l2listen.stop()  # Note the stop here
    os.close(r)
    os.close(w)
```

**Comment by polybassa** [comment]
Hi, 
thanks for your responses. I've considered mocking the unit tests. I could also remove some unnecessary code. Now my modifications inside the ISOTPSocket are even closer to the SuperSocket. 

Mocking the functions wouldn't lead to any relevant check at all. The ISOTP Packet is just a container for raw data at the moment. I will extend the functionality soon. If I mock send and receive in my socket, no new code at all will be testet. At the moment my unit test checks the installation, setup and function of a third party kernel module. If I would mock that, nothing besides the creation of a raw data packet is checked. 

Can I keep the unit tests like they are at the moment, that I can automatically check against a the third party kernel module if it is installed?

Cheers Nils

**Comment by polybassa** [comment]
Hi, how to continue with this PR?

**Comment by gpotter2** [comment]
@polybassa Correct me if i'm wrong, but this PR is overwritten by https://github.com/secdev/scapy/pull/1458 right ?

**Comment by polybassa** [comment]
I will maybe add some more unit tests to the master, when PR #1458 get's merged.

**Pull request closed without merging**
