### PR TITLE
Support bytearray in payload

### LINKED ISSUE #3015: Accept bytearray in place of bytes
#### Brief description

Currently, scapy does not accept `bytearray`s for payload data, likely among other things:

    from scapy.all import *
    pkt = Ether() / bytearray(10)

results in

    AttributeError: 'bytearray' object has no attribute '__rdiv__'

Manually casting to `bytes` works fine, but IMO `bytes` and `bytearray` should be interchangeable, not to mention other objects can implement `__bytes__`, so perhaps revisiting the implementation of `Packet.__div__` to either accept `bytearray`s in addition to `bytes`, or to attempt to cast the argument to `bytes` and only call `__rdiv__` if that fails.  

#### Environment

-   Scapy version: `2.4.3`
-   Python version: `3.9.0`
-   Operating System: `Arch`

#### How to reproduce

    from scapy.all import *
    Ether() / bytearray(10)

#### Actual result

    AttributeError: 'bytearray' object has no attribute '__rdiv__'

#### Expected result

    <Ether  |<Raw  load='\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' |>>

### PR DESCRIPTION
**Pull request by gpotter2**
- fix #3015

### CODE REVIEW

**Review by guedou — APPROVED** [review]
Thanks for this PR!

**Comment by alexforencich** [comment]
I guess I should have commented here instead of on the issue, this is incomplete. There are a few other places with the same issue.

**Comment by gpotter2** [comment]
Feel free to submit a PR for those. This is very low priority

**Comment by alexforencich** [comment]
Fair enough

**Pull request merged**
