### PR TITLE
Unbreak LaTeX output

### LINKED ISSUE #3359: UTscapy LaTeX output support is broken
### Brief description

When selecting `-f LaTeX` while running UTscapy tests I got the following error:

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/t/.tox/py39-linux_root/lib/python3.9/site-packages/scapy/tools/UTscapy.py", line 1227, in <module>
    sys.exit(main())
  File "/home/t/.tox/py39-linux_root/lib/python3.9/site-packages/scapy/tools/UTscapy.py", line 1156, in main
    output, result, campaign = execute_campaign(
  File "/home/t/.tox/py39-linux_root/lib/python3.9/site-packages/scapy/tools/UTscapy.py", line 921, in execute_campaign
    output = campaign_to_LATEX(test_campaign)
  File "/home/t/.tox/py39-linux_root/lib/python3.9/site-packages/scapy/tools/UTscapy.py", line 799, in campaign_to_LATEX
    output %= info_line(test_campaign)
TypeError: info_line() missing 1 required positional argument: 'theme'

```
Note: the campaign itself works fine (tests pass/fail as usual) - only the LaTeX output generation is borked, the ansi option works fine for example.

### Scapy version

2.4.5

### Python version

3.9

### Operating system

Ubuntu 21.04

### Additional environment information

I'm using tox to run UTscapy in isolated environment.

### How to reproduce

Run some *.uts with LaTeX output.

### Actual result

Exit code 1.

### Expected result

.tex files are generated.

### Related resources

_No response_

### PR DESCRIPTION
**Pull request by zabbal**
Fix LaTeX output generation.

**Checklist:**

-   [x] If you are new to Scapy: I have checked [CONTRIBUTING.md](https://github.com/secdev/scapy/blob/master/CONTRIBUTING.md) (esp. section submitting-pull-requests)
-   [x] I squashed commits belonging together
-   [ ] I added unit tests or explained why they are not relevant
-   [ ] I executed the regression tests for Python2 and Python3 (using `tox` or, `cd test && ./run_tests_py2, cd test && ./run_tests_py3`)
-   [ ] If the PR is still not finished, please create a [Draft Pull Request](https://github.blog/2019-02-14-introducing-draft-pull-requests/)

This PR fixes LaTeX output for UTscapy

Note: the added function is trivial - just to unbreak the LaTeX support. Feel free to expand with fancier formatting and so on.

fixes #3359

### CODE REVIEW

**Comment by zabbal** [comment]
Note: rendering the resulting files with `rubber -d` gives bunch of errors so it's a first step in implementing first-class LaTeX support.

**Comment by zabbal** [comment]
I suggest to disable macos py2.7 tests - they keep failing for no reason and python 2 is neither supported nor recommended by upstream for over an year already,

**Comment by guedou** [comment]
Could you rebase against the master branch? @gpotter2 solved the CI issues.

**Comment by zabbal** [comment]
Nice, seems like CI is indeed fixed :)

**Review by guedou — APPROVED** [review]
Thanks for this PR!

**Comment by guedou** [comment]
Concerning your remark on Python 2.7 and macOS: we decided to keep testing old Python versions as long as the CI and maintenance effort is low.

**Comment by zabbal** [comment]
Well, it's your call. I think it's worth letting users know that by using Python 2 they're potentially exposing themselves to security vulnerabilities which nobody is going to fix since py2 is deprecated upstream.

**Comment by gpotter2** [comment]
2.5.0 will be the last release supporting  Python 2, but we want to make a really stable version before dropping support.

**Pull request merged**
