### PR TITLE
Update tls module doc

### PR DESCRIPTION
**Pull request by gpotter2**
Fairly obvious PR

### CODE REVIEW

**Comment by guedou** [comment]
It seems that you have flake8 errors. It might be related to a new flake8 version.

**Comment by p-l-** [comment]
> It seems that you have flake8 errors. It might be related to a new flake8 version.

I have had the same issue with IVRE, it is entirely related to a new flake8 version. Do you want me to create a PR for that? Since that's a bit of (annoying) work, I'm OK to do it but in that case don't do it at the same time.

I'll let you know here when the PR is ready.

**Comment by p-l-** [comment]
> It seems that you have flake8 errors. It might be related to a new flake8 version.

It is indeed. In IVRE, I have used a temporary fix to use the previous version. This new version brings **a lot** of new issues...

**Comment by guedou** [comment]
@p-l- do you mean ensuring that the code will be tested with an *old* flake* version or fixing the issue?

**Comment by p-l-** [comment]
> @p-l- do you mean ensuring that the code will be tested with an _old_ flake* version or fixing the issue?

As a temporary fix, I'd suggest to force the old flake8 version...

**Pull request merged**
