### PR TITLE
Changed readline system

### PR DESCRIPTION
**Pull request by gpotter2**
I've introduced a bug in https://github.com/secdev/scapy/pull/454
The auto-completion was not working anymore.

We got a problem:
- the autocompletion system works with pyreadline, BUT there is a bug on pyreadline and functions are not detected (see https://github.com/secdev/scapy/pull/454)
- the default interpreter (so not pyreadline) detects the functions, BUT doesn't support autocompletion

This is a custom created function that handle both of the functions...

Tiny problem: i have not managed to print the color of `>>>` (it used to be in blue)
@guedou Can you check if it works for you too, as the tests doesn't run it ?

Do you think that it's important to keep the colors ? If yes, any idea?

### CODE REVIEW

**Comment by gpotter2** [comment]
I've added some tests for windows... I'm just waiting for https://github.com/secdev/scapy/pull/398 to be approved before adding them...

**Comment by p-l-** [comment]
I don't like the idea to change the main Scapy code just because completion is broken on Windows. Shouldn't we find a way to adapt `code.interact` on Windows rather than rewriting it?

**Comment by gpotter2** [comment]
@p-l- You're right.

**Comment by gpotter2** [comment]
See https://github.com/secdev/scapy/pull/465

**Pull request closed without merging**
