### PR TITLE
PPTP support (Enhanced GRE, PPP LCP, PPTP Control Connection)

### PR DESCRIPTION
**Pull request by jsebechlebsky**
Hello, I've implemented support for protocols used with PPTP VPN.
This includes support for Enhanced GRE headers defined in RFC 2637, PPP Link Control Protocol and PPTP Control Connection Protocol defined in RFC 2637.
I will be glad if these will became part of Scapy project.

### CODE REVIEW

**Comment by p-l-** [comment]
Hi,

Thanks for this contribution! Could you add unit tests (perhaps creating `test/pptp.uts` or `test/ppp.uts`)?

**Comment by jsebechlebsky** [comment]
Sure, I'll try to create tests and push it in this branch this week.

**Comment by jsebechlebsky** [comment]
Hi, sorry for a delay, I've added `test/pptp.uts` covering newly added layers.

**Comment by jsebechlebsky** [comment]
... I think the test failure is unrelated to the patch (It seems that test machine was unable to download dependecy).

**Comment by p-l-** [comment]
Hi,

Thanks for the test. Could you replace `x.haslayer(y)` by `y in x`?

Also, I'm not sure if we want PPTP auto-loaded. @guedou what do you think?

**Comment by guedou** [comment]
@p-l- I am ok with loading it by default, as this is something that you can encounter while sniffing a network.

**Comment by jsebechlebsky** [comment]
@p-l- I've replaced `x.haslayer(y)` by `y in x` in `pptp.uts`.

**Comment by p-l-** [comment]
@jsebechlebsky thanks!

**Pull request merged**
