### PR TITLE
Cleanup CI setup

### PR DESCRIPTION
**Pull request by polybassa**
Mirroring Scapy on gitlab to test gitlab-ci: https://gitlab.com/polybassa/scapy_gitlab_ci/-/tree/gitlabci

### CODE REVIEW

**Comment by polybassa** [comment]
This PR enables some basic non_root tests on gitlab-ci. Some minor cleanups to `install.sh` are contained as well.

There is currently no need to have gitlab-ci for Scapy, but this could be a fallback CI system. 
Also, I would like to experiment with some hardware-in-the-loop tests in the near future, and gitlab is simpler for me.

**Comment by guedou** [comment]
I don't think that we should merge this upstream. As gitlab ci is not used in our testing, I am afraid that this file will end up not being accurate and ultimately won't work.

**Comment by polybassa** [comment]
Ok, sad. We could easily connect the gitlab fork to this github repo in order to work as a build environment in pull requests. Otherwise, I'll remove the gitlab-ci.yml file from this PR, but I still would like to merge the cleanups.

**Comment by guedou** [comment]
What is the benefit of using gitlab-ci on top of GitHub?

**Comment by polybassa** [comment]
gitlab-ci would be a second source for all non_root CI tests, if we may finish the GitHub quota in the future. Besides that, I only have personal interests in performing some automated tests against hardware-in-the-loop setups over gitlab-ci. This PR has some cleanups which help me to run the tests on gitlab-ci.

If it's not too much effort to maintain, my personal opinion is, that it's in general valuable to run tests on different “infrastructure”, since it may uncover some problems or flaky tests. Also, it may lead to a better code quality. This PR, for example, proofs that  there was some left-over code in the CI setup which was actually not necessary the entire time. I only found this because of the port to gitlab-ci.

**Comment by gpotter2** [comment]
Is there a Github quota?

The cleanups LGTM ! I personally also like having different infras but for different reasons: it help us go through outages. There have been times where Github actions were KO and we were quite happy to have the AppVeyor ones running.

**Review by gpotter2 — APPROVED** [review]

**Comment by polybassa** [comment]
Thanks for your response. Well the gitlab-ci file is now in the git-history. If you like, I can create a "draft" PR or I can store it somewhere else, if we may use it in the future (or on the next outage).

**Comment by gpotter2** [comment]
History is fine (enough) IMHO 🙂

**Pull request merged**
