### PR TITLE
NTLM relaying - SMB / LDAP

### PR DESCRIPTION
**Pull request by gpotter2**
This PR implements some *basic* NTLM relaying functions & attacks, around the SMB and LDAP protocols

- `ntlm_relay` function and automatons: highly customizable Automatons
- SMB1/SMB2 relay
  - Support for Signature downgrade
  - Support for SMB2->SMB1 downgrade
  - Support for SMB1Extended->SMB1 downgrade
  - Support for SMB2<->SMB2
- Support for SMB2->LDAP(S) channel binding

**You'll find a few samples below, please note a fuller version of the doc with more examples is available in `doc/scapy/layers/ntlm.rst`**

(for all the examples below, we have a `netbios_announce(iface="virbr0")` running in the background to answer all netbios requests, allowing us to access `\\SCAPYWASHERE` freely)

### SMB2 downgrade to SMB1 - relay
```python
ntlm_relay(NTLM_SMB_Server, "192.168.122.4", NTLM_SMB_Client, iface="virbr0", ALLOW_SMB2=False, server_kwargs={"REAL_HOSTNAME":"WIN1"})
```
image
image
image
image

### SMB2 <-> SMB2 relay

We close the legitimate client as soon as we are authenticated, and run a custom script:

```python
    ntlm_relay(NTLM_SMB_Server, "192.168.122.156", NTLM_SMB_Client, iface="virbr0", server_kwargs={"ECHO": False}, client_kwargs={"REAL_HOSTNAME": "WIN1", "RUN_SCRIPT": True})
```
image

### SMB2 <-> LDAP channel binding
```python
load_layer("ldap")
ntlm_relay(NTLM_SMB_Server, "192.168.122.156", NTLM_LDAP_Client, iface="virbr0")
```
image

### CODE REVIEW

**Comment by gpotter2** [comment]
Need this for work !

**Comment by polybassa** [comment]
I'm sorry, but I have to admit that I'm not so happy that such a big PR got merged without review.

**Comment by gpotter2** [comment]
You are very right, this is not okay. I thought I had asked for review (which I had not)

**Comment by polybassa** [comment]
Please don't get me wrong.. I've no doubts that your code has a very high quality.. it's just about the four eyes principle.

**Pull request merged**
