### PR TITLE
Backup & restore conf.route.routes

### PR DESCRIPTION
**Pull request by guedou**
This fixes failing tests on OpenBSD.

### CODE REVIEW

**Comment by gpotter2** [comment]
How is that possible ?
The routes where loaded using `resync()` anyways, so how come is it that reloading them this way fails?

**Comment by guedou** [comment]
@gpotter2 `conf.route.routes` was empty during the unit tests run. `conf.route.routes` is populated with `resync()` at startup, so I don't know what is going on =/

**Comment by guedou** [comment]
@gpotter2 everything is fine with Python2 & Python3, both in interactive mode and from a script:
```
>>> len(conf.route.routes)
7
>>> conf.route.resync()
>>> len(conf.route.routes)
7
```

Am I not convinced that we should spend time trying to debug this edge case. I could add a comment in the UTS file to explain why `resync()` is not used.

**Comment by guedou** [comment]
This PR makes everything works fine on NetBSD too.

**Comment by gpotter2** [comment]
All right then

**Pull request merged**
