### PR TITLE
Minor cleanups (contrib, typing)

### PR DESCRIPTION
**Pull request by gpotter2**
Minor cleanups in various files:
- base_clases typing
- a few contrib layers that had a duplicated field name
- vqp tests

### CODE REVIEW

**Review by p-l- — APPROVED** [review]

**Review by p-l- — CHANGES_REQUESTED** [review]
Hi,

Apart from the failing CI, looks good to me.

**Comment by polydroi** [comment]
Hi, could you please allow isotp.uts to run on all systems. The file 'interface_mockup.py' ensures the correct configuration and the tests are intent to run on window, osx and non root systems, as well.

**Comment by polybassa** [comment]
> Hi, could you please allow isotp.uts to run on all systems. The file 'interface_mockup.py' ensures the correct configuration and the tests are intent to run on window, osx and non root systems, as well.

This comment was made by me. This is just my mobile account.

**Comment by gpotter2** [comment]
I don't believe we're disabling them here? I could be wrong.
I'm just making sure tests that are long aren't run from `./run_tests` with no options, which is supposed to be a fast-tests only.

**Comment by polybassa** [comment]
Alright. As far as I remember, vcan_socket is only present on Linux with root and python 3. Therefore I don't like this tag on isotp.uts.

The campaign isotp.uts doesn't require that much execution time.

-- 
Viele Grüße

Nils Weiß

**Comment by gpotter2** [comment]
It still spawns sockets and hangs for quite some time. `./run_tests` is a convenience to devs

**Comment by polybassa** [comment]
Ok, no problem. But could you please check if it still runs on windows CI after adding this tag? 

Sorry for the inconveniences, but this test is important for the automotive stuff.

**Comment by gpotter2** [comment]
If you're talking about the windows fix we're just making sure libpcap was properly installed on root builds, else fail. It doesn't change the behavior of anything else

**Comment by polybassa** [comment]
No, this was not what I meant. I can truly understand your intention to have run_tests as a convenience function with fast execution times. From that perspective it's alright to disable these tests. 

But the tag vcan_socket is not suitable for that, In my opinion. 

Only the ci machines with Linux and root have the tag vcan_socket present. This has the side effect, that isotp.uts will not run on appveyor and macos ci machines. From my perspective, this is undesired, since I want to ensure that isotp runs on any platform. 
--

**Pull request merged**
