### PR TITLE
Fix sendpfast() for Python 2 & 3

### LINKED ISSUE #1798: sendpfast() not working with Python 2.7
#### Brief description

Part of the changes from 2.3 to 2.4 included `sendpfast()` changing from using `subprocess.check_call()` to `subprocess.Popen()`.

The `subprocess.Popen()` call is using a context object form for automatic closing of the handle:

```python
        with subprocess.Popen(argv, stdout=subprocess.PIPE, stderr=subprocess.PIPE) as cmd:  # noqa: E501
            stdout, stderr = cmd.communicate()
```

I believe this context object form wasn't introduced to Popen until Python 3.

In Python 2.7, this raises `AttributeError: __exit__`, which causes an error message in interactive mode and the packet is not sent.

#### Environment

-   Scapy version: confirmed with both 2.4.2 release as well as latest master `e5a9b82f`
-   Python version: `Python 2.7.14`
-   Operating System: Docker image based on `Debian GNU/Linux 8 (jessie)`

#### How to reproduce

```bash
docker run --rm -it python:2 bash
apt-get update && apt-get install -y tcpreplay
pip install scapy==2.4.2
scapy
sendpfast(Ether() / IP(proto='udp', dst='233.43.202.24') / UDP(dport=11124) / 'TEST', iface='eth0')
```

#### Actual result

```
INFO: ['tcpreplay', '--intf1=eth0', '--topspeed', '/tmp/scapyoGcRCI']
ERROR: Cannot execute [tcpreplay]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/scapy/sendrecv.py", line 371, in sendpfast
    with subprocess.Popen(argv, stdout=subprocess.PIPE, stderr=subprocess.PIPE) as cmd:  # noqa: E501
AttributeError: __exit__
```

#### Expected result

```
WARNING: Mac address to reach destination not found. Using broadcast.
.
Sent 1 packets.
```

### PR DESCRIPTION
**Pull request by p-l-**
`with subprocess.Popen()` is not supported in Python 2 (fixes #1798).

Output from `sendpfast()` was not converted from `bytes` to `str` in Python 3.

### CODE REVIEW

**Comment by gpotter2** [comment]
@p-l- I fixed the parser to something consistent / non version-dependent.
Hope you don’t mind the commit

Otherwise all good to me

**Comment by p-l-** [comment]
@gpotter2 of course I don't mind! Thanks!

**Comment by badcodebuilder** [comment]
I think the popen object `cmd` created in `sendpfast` is not terminated when KeyboardInterrupt is caught. As we known that, `else` block in try environment will be executed only if no exception happens. And KeyboardInterrupt is not raised like other exceptions, which are meant to be processed in `ContextManagerSubprocess`

I found this bug when I used my tool, which uses scapy, in a subprocess. When I terminated the subprocess, it worked, but the `tcpreplay` was still running in background.

I think it is better to move code fron line 594 to 600 into try-catch block, and terminate cmd properly in KeyboardInterrupt processing block.

https://github.com/secdev/scapy/blob/20a3468a1043108676219b3629c735c06fab181f/scapy/sendrecv.py#L584-L600

**Comment by gpotter2** [comment]
Hi, feel free to submit a PR ! Thanks for spotting this.

**Pull request merged**
