### PR TITLE
Add SSHv2

### PR DESCRIPTION
**Pull request by gpotter2**
- add a basic SSHv2 implementation (not loaded by default)
- tests

### CODE REVIEW

**Comment by gpotter2** [comment]
@guedou @p-l- @polybassa Ready for review :D

**Review by guedou — APPROVED** [review]
Really cool PR! I reviewed and tested it with https://github.com/features/codespaces It is a game changer =)

Will it be difficult to support encryption/decryption ?

**Comment by gpotter2** [comment]
Thanks !

Probably not that hard. I'm still hesitant regarding what would be the cleanest way of implementing it.

Either:
- something like the SecurityAssociation we have for Ipsec
- something like using a Session
- just an automaton

**Comment by guedou** [comment]
SSHSessions like TLSSessions will be my favorite.

**Pull request merged**
