### PR TITLE
Split of #3054: Implementation of Enumerator and Executor base classes

### PR DESCRIPTION
**Pull request by polybassa**
Another split of #3054.
This PR introduces new classes, Enumerator and Executor. Both classes will be used for UDS, OBD and GMLAN scanner in a following PR.

### CODE REVIEW

**Comment by polybassa** [comment]
Could this one please get merged, so that I can finalize #3054

**Comment by polybassa** [comment]
@gpotter2 Could you please have a look at this PR, so that I can finalize #3054

**Comment by polybassa** [comment]
@gpotter2 Rebased

**Review by gpotter2 — APPROVED** [review]

**Comment by gpotter2** [comment]
Thanks for the PR and very sorry for the delay.

**Pull request merged**
