### PR TITLE
Fix ICMPv6MLQuery().hashret()

### LINKED ISSUE #334: RFC error (from stack over flow)
What do you guys think of this:
http://stackoverflow.com/a/39439585/5459467

> That struct.pack has no chance of working, it at least should be:
> 
> return struct.pack("HH", *self.mladdr)+self.payload.hashnet()
> So that struct.pack has no chance of receiving the two arguments needed for "HH". That is a bug.

### PR DESCRIPTION
**Pull request by p-l-**
This should fix #334.

### CODE REVIEW

**Comment by gpotter2** [comment]
This is so weird

**Comment by p-l-** [comment]
**DO NOT MERGE**: currently investigating Travis CI fails.

**Comment by p-l-** [comment]
@gpotter2 can you confirm this fix works for you?

**Comment by gpotter2** [comment]
It looks so:
```
>>> router_advertisement = scapy.IPv6(src=ra_src_addr, dst='FF02::1')/scapy.ICMPv6ND_RA(routerlifetime=0, reachabletime=0)/scapy.ICMPv6NDOptSrcLLAddr(lladdr=hw_addr)/scapy.ICMPv6NDOptPrefixInfo(prefixlen=64, validlifetime=0x6, preferredlifetime=0x6, prefix='dead::')
>>> answer, unanswer = sr(router_advertisement, timeout=10, multi=True)
Begin emission:
WARNING: No route found for IPv6 destination ff02::1 (no default route?)
Finished to send 1 packets.
.............................................................................................................................................................................................................................................................................WARNING: DNS RR prematured end (ofs=28078, len=297)
.WARNING: DNS RR prematured end (ofs=28078, len=297)
.WARNING: more DNS RR prematured end (ofs=28038, len=217)
...................................................WARNING: DNS decompression loop detected
WARNING: DNS decompression loop detected
.WARNING: more DNS decompression loop detected
..........................................................................................................................................................................................................................................................................................................................................................................................................................WARNING: DNS RR prematured end (ofs=28078, len=297)
.WARNING: DNS RR prematured end (ofs=28078, len=297)
.WARNING: more DNS RR prematured end (ofs=28038, len=217)
..............................................................................................................................................................................................................................
Received 957 packets, got 0 answers, remaining 1 packets
```

**Comment by p-l-** [comment]
Is it expected that you don't get any answer?

**Comment by gpotter2** [comment]
Yes, as every thing in the request is fake

**Comment by guedou** [comment]
This patch is correct, however the proposed test does not trigger the issue. The SO issue is caused during hashret computations based on packets received.

```
# Before the patch
>>> ICMPv6MLQuery(mladdr="::1").hashret()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "scapy/layers/inet6.py", line 1355, in hashret
    return struct.pack("HH",self.mladdr)+self.payload.hashret()
error: pack expected 2 items for packing (got 1)

# After the patch
>>> ICMPv6MLQuery(mladdr="::1").hashret()
'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01'
```

**Pull request merged**
