### PR TITLE
added CANFD support

### PR DESCRIPTION
**Pull request by superuserx**
Added CANFD support to CAN and native ISOTP socket.

### CODE REVIEW

**Comment by polydroi** [comment]
Thanks for this PR. I'm missing some isotpnativesocket unit Tests. Could you please add some?

**Comment by polybassa** [comment]
could you please rebase against master

**Comment by superuserx** [comment]
Sorry for this mess. Is it correct what I did?

**Comment by polybassa** [comment]
No, that doesn't look right. 

Usually you need to do git pull -r origin master, where origin is the name of your git remote pointing to secdev scapy 
-- 
Viele Grüße

Nils Weiß

**Pull request closed without merging**
