### PR TITLE
Fixed some Windows crashes (arch + tests)

### PR DESCRIPTION
**Pull request by gpotter2**
Well this fixed https://github.com/secdev/scapy/issues/277

### CODE REVIEW

**Comment by gpotter2** [comment]
Well i cannot manage to pass the last live check of edns0.uts..... Is it still working ? or am i breaking anything ?

**Comment by p-l-** [comment]
Thanks. Is'nt it possible to keep the `from scapy import arch` and fix the `arch.*` uses in the code rather than importing `from scapy.arch import *`?

**Comment by gpotter2** [comment]
Yeah sure... Better idea I guess :)

Btw have you seen how random the Travis ci build was ????!! I literally changed nothing between the last two builds but one work and not the other one... The failing check should be removed or modified (a live one)...

**Comment by robin-jarry** [comment]
I think the real error is that there is a circular import in `scapy/arch/windows/__init__.py`.

A more correct fix would be:

```diff
diff --git a/scapy/arch/windows/__init__.py b/scapy/arch/windows/__init__.py
index 3884dac7d715..9a4142d8b1c2 100755
--- a/scapy/arch/windows/__init__.py
+++ b/scapy/arch/windows/__init__.py
@@ -18,7 +18,6 @@ from scapy.error import Scapy_Exception,log_loading,log_runtime
 from scapy.utils import atol, itom, inet_aton, inet_ntoa, PcapReader
 from scapy.base_classes import Gen, Net, SetGen
 import scapy.plist as plist
-from scapy.sendrecv import debug, srp1
 from scapy.data import MTU, ETHER_BROADCAST, ETH_P_ARP
 
 conf.use_pcap = False
@@ -461,6 +460,7 @@ def sndrcv(pks, pkt, timeout = 2, inter = 0, verbose=None, chainCC=0, retry=0, m
         
     if verbose is None:
         verbose = conf.verb
+    from scapy.sendrecv import debug
     debug.recv = plist.PacketList([],"Unanswered")
     debug.sent = plist.PacketList([],"Sent")
     debug.match = plist.SndRcvList([])
```

I don't have any windows machine to check if that is enough. Can you verify if that works?

**Comment by gpotter2** [comment]
Right that's working :)

**Comment by p-l-** [comment]
@robin-jarry would you like to submit a PR for this one?

**Comment by robin-jarry** [comment]
Done :) See #293

**Pull request closed without merging**
