### PR TITLE
fixed KeyError on timessent in sndrcv when an error happens during a send

### PR DESCRIPTION
**Pull request by epozzobon**
Currently, in sndrcv, when an error happens during the send operation it gets logged and execution continues. However, since timessent is not populated, a KeyError will be raised at the line `p.sent_time = timessent[i]`. I added a check to verify that the key is present in the timessent dict.
This PR also fixes ISOTPSoftSocket.sr1 not returning after the specified timeout, and I added 2 unit tests for that.

### CODE REVIEW

**Comment by gpotter2** [comment]
Thanks for the PR & sorry for the late reply.
This entire mechanic will be changed in https://github.com/secdev/scapy/pull/1999, therefore I hope you don't mind if we don't merge this one :)

**Comment by guedou** [comment]
@gpotter2 should we close this PR?

**Comment by gpotter2** [comment]
It will be closed by #1999

**Comment by guedou** [comment]
OK, I will close it as this PR will never be merged.

**Pull request closed without merging**
