### PR TITLE
fix SOME/IP transport protocol message types

### LINKED ISSUE #3008: Wrong message type for SOME/IP transport protocol responses
#### Brief description

Scapy automotive uses wrong message type for SOME/IP transport protocol responses and error messages.

#### Environment

-   Scapy version: `2.4.4`
-   Python version: ` 3.8`
-   Operating System: `Win 10`

I'm trying to receive a SOME/IP transport protocol response. My simulated ECU (using vsomeip) sends the response with a message type of `0xa0`. This is according to the SOME/IP spec correct ([SOME/IP classic transport protocol spec](https://www.autosar.org/fileadmin/user_upload/standards/classic/19-11/AUTOSAR_SWS_SOMEIPTransportProtocol.pdf), [SOME/IP foundation spec](https://www.autosar.org/fileadmin/user_upload/standards/foundation/19-11/AUTOSAR_PRS_SOMEIPProtocol.pdf)).

scapy_bug_spec

The problem seems to be in the [SOMEIP](https://github.com/secdev/scapy/blob/master/scapy/contrib/automotive/someip.py) class. The [TYPE_TP_RESPONSE](https://github.com/secdev/scapy/blob/ee21931bbbbe94f801a6e44031cb117eba141e16/scapy/contrib/automotive/someip.py#L67) is wrong (set to `0x23`). It should be `0xa0` instead.

Same thing for the [TYPE_TP_ERROR ](https://github.com/secdev/scapy/blob/ee21931bbbbe94f801a6e44031cb117eba141e16/scapy/contrib/automotive/someip.py#L68). It is set to `0x24`. This variable should be (according to SOME/IP transport protocol spec) set to `0xa1`.
 

#### How to reproduce

Send a SOME/IP RPC call to a transport protocol enabled service and wait for the response. The response needs to be above the max payload size for SOME/IP messages.

#### Actual result

Transport protocol response are not recognized correctly. Therefore the receiving part is not working.
The defined [conditional fields](https://github.com/secdev/scapy/blob/ee21931bbbbe94f801a6e44031cb117eba141e16/scapy/contrib/automotive/someip.py#L127) are always `None`

```
        ConditionalField(BitField("offset", 0, 28),
                         lambda pkt: SOMEIP._is_tp(pkt)),
        ConditionalField(BitField("res", 0, 3),
                         lambda pkt: SOMEIP._is_tp(pkt)),
        ConditionalField(BitField("more_seg", 0, 1),
                         lambda pkt: SOMEIP._is_tp(pkt))
```

Debugging the code, the static `_is_tp()` method inside the `SOMEIP` class returns always `False` for transport protocol responses.

#### Expected result

The `_is_tp()` method inside the `SOMEIP` class  should return `True` for transport protocol responses.

scapy_bug_wire

### PR DESCRIPTION
**Pull request by tobibrb**
fixes #3008

### CODE REVIEW

**Comment by polybassa** [comment]
Thanks for this PR

**Comment by polybassa** [comment]
could you please rebase

**Comment by tobibrb** [comment]
> could you please rebase

Damn it. I made a big mess. I'll create a new PR.

**Comment by gpotter2** [comment]
The commands that'll save you most of the time are
```
git pull --rebase upstream master
git push -f
```

**Pull request closed without merging**
