### PR TITLE
Bluetooth LE: Add support for iBeacon

### PR DESCRIPTION
**Pull request by micolous**
ibeacon: New layer!

- Decodes iBeacon as a submessage of Apple's BLE broadcast frame format. Does not implement support for other types of Apple BLE broadcasts.
- Adds tests and example documentation.
- Moves some beacon-building functionality into `scapy.layers.bluetooth`.

This also includes some minor documentation changes for Eddystone, in order to reference the same `Beacon Locator` Android app used for testing iBeacons (as it can handle both -- whereas the Eddystone Validator only handles Eddystone).

~This PR requires #1892 to be merged first, as it requires `UUIDField`.~ **Done!**

### CODE REVIEW

**Comment by micolous** [comment]
Now that #1892 is merged, I've rebased on `master`, and squashed the fix-up commits in this, please take a look!

**Comment by gpotter2** [comment]
Hi, I’ve cleaned up the doc, and moved all layer-specific docs. This PR now conflicts.

Otherwise all good to me

**Comment by micolous** [comment]
Rebased on master. Codacy was sad about changes introduced by this PR when checking #1957, so lets see how this goes...

**Comment by micolous** [comment]
OK, looks like Codacy and the Travis CI linters are happy now!  The AppVeyor issues look like you're trying to resolve them in another PR.

**Comment by guedou** [comment]
Nice PR!

From a usage point of view. do you think that IBeacon_Data could be integrated intp Apple_BLE_Submessage?

**Comment by micolous** [comment]
> From a usage point of view. do you think that IBeacon_Data could be integrated into Apple_BLE_Submessage?

They're intentionally split -- [the structure is described in the documentation](https://github.com/micolous/scapy/blob/ibeacon/doc/scapy/layers/bluetooth.rst#appleibeacon-broadcast-frames).

This allows the non-iBeacon Apple BLE frames to be implemented later, if/when the format becomes publicly known.  Right now, they're just `Raw`, which is consistent with how Scapy handles other unknown payloads.

Merging them would cause any capture containing a frame from some _other_ Apple BLE device to have some unexpected behaviour.  And who knows, someone might want to fuzz this protocol...

**Comment by micolous** [comment]
This is now rebased such that common changes needed for #1957 are in both PRs, and the iBeacon-specific changes are in one (squashed) commit.  Hopefully won't conflict if both are merged...

**Comment by gpotter2** [comment]
Rebased against master to fix the doc conflicts

**Pull request merged**
