### PR TITLE
[radius.py] fix  fields** not passes

### PR DESCRIPTION
**Pull request by Matheus-Garbelini**
This commit is to fix the problem related to issue #2095 
Since @lidllohntsich is not responding, I'm just passing on the commit.

Thanks.

### CODE REVIEW

**Comment by Matheus-Garbelini** [comment]
Tests failed:
failed F3CD8BCE RADIUS - Access-Request - Dissection (3)
failed 048944DD RADIUS - Access-Request - Dissection (1)

**Comment by gpotter2** [comment]
Thanks for your work on this btw ! :smile:

**Comment by guedou** [comment]
@Matheus-Garbelini this PR breaks unit tests. Could you also modify the following lines?
https://github.com/secdev/scapy/blob/master/test/regression.uts#L10564
https://github.com/secdev/scapy/blob/master/test/regression.uts#L10564https://github.com/secdev/scapy/blob/master/test/regression.uts#L10564

Thanks!

**Comment by Matheus-Garbelini** [comment]
@guedou thanks for point it out. I'll give it a look.

**Comment by guedou** [comment]
Unit tests added in #2365

**Pull request closed without merging**
