### PR TITLE
Fix the race condition

### LINKED ISSUE #4546: Hitting "File exists" on 2.6.0
### Brief description

Scapy doesn't check if the `.config` directory already exists. 
```
    from scapy.all import *  # noqa: F401,F403
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/scapy/all.py", line 13, in <module>
    from scapy.data import *
  File "/usr/local/lib/python3.12/site-packages/scapy/data.py", line 415, in <module>
    @scapy_data_cache("ethertypes")
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/scapy/data.py", line 301, in scapy_data_cache
    from scapy.main import SCAPY_CACHE_FOLDER
  File "/usr/local/lib/python3.12/site-packages/scapy/main.py", line 165, in <module>
    SCAPY_CONFIG_FOLDER = _probe_config_folder("scapy")
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/scapy/main.py", line 82, in _probe_config_folder
    return _probe_xdg_folder(
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/scapy/main.py", line 76, in _probe_xdg_folder
    path.mkdir(mode=0o700)
  File "/usr/lib64/python3.12/pathlib.py", line 1311, in mkdir
    os.mkdir(self, mode)
FileExistsError: [Errno 17] File exists: '/root/.config'
```

### Scapy version

2.6.0

### Python version

3.12

### Operating system

Linux 6.10.6

### Additional environment information

_No response_

### How to reproduce

Just importing `from scapy.all import *` is enough.

### Actual result

_No response_

### Expected result

_No response_

### Related resources

_No response_

### PR DESCRIPTION
**Pull request by guedou**
Fixes #4546

### CODE REVIEW

**Review by gpotter2 — APPROVED** [review]

**Comment by gpotter2** [comment]
This issue is a bit ridiculous. But alright.

**Comment by KepptnKool** [comment]
Will there be a patch level release containing the fix in the near future?

**Comment by gpotter2** [comment]
The code is

```
if not path.exists():
    path.mkdir()
```

How can the path already exist?

**Comment by whoisxy** [comment]
> The code is
> 
> ```
> if not path.exists():
>     path.mkdir()
> ```
> 
> The fact that this can fail with an "already exists" error is ridiculous to me.

@gpotter2 TOCTOU

**Comment by gpotter2** [comment]
If we were in a multi processed code, sure. If you somehow managed to start multiple instances of Scapy, maybe. But that's not the case isn't it?


Closing though.

**Pull request merged**
