### PR TITLE
Rewrite arch/bpf

### PR DESCRIPTION
**Pull request by gpotter2**
This rewrites most of the arch/bpf code that handles the loading of `conf.ifaces`, `conf.route` and `conf.route6`, in order to use `PF_ROUTE` (instead of the current reading involving subprocess, parsing ifconfig, and other kinda crappy stuff).

This should:
- add support for multiple IPv4 on interfaces
- add proper support for multicast routes
- stabilize the API by not relying on ifconfig changes.

Also:
- fixes https://github.com/secdev/scapy/issues/4498
- fixes https://github.com/secdev/scapy/issues/4312 and fixes https://github.com/secdev/scapy/issues/4304
- `conf.iface` no longer takes a bigger role on IPv6 routing. Considering the Scoped IPs PR, it wasn't necessary anymore.
- remove usages to `get_if_raw_hwaddr` where not necessary. This is only really needed on Linux, not other plateforms.
- remove the fact that `conf.iface` is used in `conf.route6.route()`. Now that we support scoped IPs, this isn't needed and adds confusion.
- adds a 'type' attribute to `NetworkInterface` to remember the interface type (first parameter that get_if_raw_hwaddr returned). This IS cross plateform (that being said, if Windows uses standard IANA types, most other plateforms, linux included, use custom garbage (e.g. ARPHRD... constants))

(yeah this is a followup to https://github.com/secdev/scapy/pull/4352)

### TESTED ON:
- FreeBSD 14.1
- OpenBSD 7.5
- NetBSD 10.0
- MacOS 14

Annoyingly it seems every BSD (at least FreeBSD, OpenBSD and NetBSD) have different rt_* structures. Ugh.

### CODE REVIEW

**Comment by gpotter2** [comment]
@dhgutteridge Hi & sorry for bothering. I was wondering if you'd have some advices regarding making this PR work on NetBSD.

Unlike OpenBSD and FreeBSD, NetBSD has chosen to versionize the `NET_RT_IFLIST` const. In your humble opinion, which version should we be using? From what I understand, some are more compatible than others.

Also if you have something to say regarding this PR in general, feel free to give your opinion :)

Thanks for the help, cheers

**Comment by dhgutteridge** [comment]
> @dhgutteridge Hi & sorry for bothering. I was wondering if you'd have some advices regarding making this PR work on NetBSD.

Sure, my pleasure. Thanks for supporting us. :)

> Unlike OpenBSD and FreeBSD, NetBSD has chosen to versionize the `NET_RT_IFLIST` const. In your humble opinion, which version should we be using? From what I understand, some are more compatible than others.

I think you'd want the magic number 6 here, in other words, the current value of NET_RT_IFLIST. The other values are versioned for compatibility with old NetBSD binaries from EOL releases. Since you're tracking NetBSD 10, I believe, you'd want the most current value. (Now, whether that gives you any additional output needed for your purposes is another matter, I suppose. "3" may "just work" for you. Here I don't know how OpenBSD and FreeBSD vary in their content.)
 
> Also if you have something to say regarding this PR in general, feel free to give your opinion :)

I could test it for you on NetBSD and/or gather input for any other questions you have.

> Thanks for the help, cheers

**Comment by gpotter2** [comment]
> I think you'd want the magic number 6 here, in other words, the current value of NET_RT_IFLIST.

Thanks a lot ! I tried using that in the latest commit. It should now almost support NetBSD.

> I could test it for you on NetBSD and/or gather input for any other questions you have.

Thanks !

I've taken inspiration from `sbin/route/rtutil.c` for some parts. I however don't really understand how the blob of data returned for IPv6 netmask in routes should be interpreted. (see the todo on line 922). `rtutil.c` seems to do some very weird stuff. If you have an idea I'm open for it, otherwise I'll get back to this eventually :)

**Comment by gpotter2** [comment]
> I however don't really understand how the blob of data returned for IPv6 netmask in routes should be interpreted. (see the todo on line 922)

Apparently the first 6 octets are garbage (always 0xFFFFFFFFFF), followed by the actual IPv6 netmask. As far as my understanding goes at least. The netmask payload generally looks broken, unless I missed something, as the sockaddr type is also FF.

**Comment by gpotter2** [comment]
@p-l- @guedou @polybassa 
This is ready for review. Was kind of a nightmare to make, and is probably also a nightmare to review.

It however works in its latest commit on all *BSDs mentionned above.

**Comment by polybassa** [comment]
Looks good to me.

**Review by polybassa — APPROVED** [review]

**Comment by gpotter2** [comment]
Then let's merge that monster and go for 2.6.0.

**Comment by dhgutteridge** [comment]
> > I however don't really understand how the blob of data returned for IPv6 netmask in routes should be interpreted. (see the todo on line 922)
> 
> Apparently the first 6 octets of the sockaddr data are garbage (always 0xFFFFFFFFFF), followed by the actual IPv6 netmask. As far as my understanding goes at least. The netmask payload generally looks kinda malformed, unless I missed something, as the sockaddr type is also FF. On other BSDs, it was either AF_INET6 or 0.

I have it on my list to look into this for you, just haven't got around to it yet.

**Pull request merged**
