### PR TITLE
Fix flake8 errors

### PR DESCRIPTION
**Pull request by polybassa**
This PR should fix all flake8 issues which appeared from the version change

### CODE REVIEW

**Comment by polybassa** [comment]
Codacy is not happy, but I think that's unrelated.

**Comment by gpotter2** [comment]
While you're at it
https://github.com/secdev/scapy/blob/988bdef701e1cf81e7d61b0a7e04ae810884ae9f/scapy/contrib/isotp.py#L876

**Comment by polybassa** [comment]
should I add this ISOTP fix to this PR?

**Comment by polybassa** [comment]
since this issues from lgtm break something, I will change that in an additional PR. This PR is reverted back to flake8 issues only.

**Comment by polybassa** [comment]
#2645 handles the isotp issue

**Comment by gpotter2** [comment]
Thanks again for the PR

**Comment by polybassa** [comment]
Your welcome :-)

Seeing CI tests becoming green makes me happy.

**Pull request merged**
