### PR TITLE
Add optional parameter plot_xy to .plot() and .multiplot()

### PR DESCRIPTION
**Pull request by p-l-**
This way, it is possible with both methods to specify values for the
"x" coordinate. By default, `plot_xy` is False and the "x" coordinate
is the index of the packet in the list.

Examples:

    >>> ans.plot(lambda x: x[1].id)
    >>> ans.plot(lambda x: (x[1].time, x[1].id), plot_xy=True)
    >>> ans.multiplot(lambda x: (x[1][IP].src, x[1].id))
    >>> ans.multiplot(lambda x: (x[1][IP].src, (x[1].time, x[1].id)), plot_xy=True)

This is related to #27.

### CODE REVIEW

**Comment by p-l-** [comment]
I have updated the PR to include a [notebook](https://github.com/p-l-/scapy/blob/feature-plot-xy/doc/notebooks/graphs-ipids.ipynb) to explain the syntax

**Comment by guedou** [comment]
This PR is OK for me. However, I might rename/edit this PR to add more examples.

**Comment by techtonik** [comment]
I wonder if it is possible to keep custom pieces of API that are absent from matplotlib compatible with D3.js rather than inventing own stuff.

**Comment by p-l-** [comment]
@guedou: sure thing! This example is only here to show the `plot_xy` use. That would be great to have other examples!

**Pull request merged**
