### PR TITLE
Fix unit-test of CANSignals, add documentation and minor improvements.

### PR DESCRIPTION
**Pull request by polybassa**
This fixes the unit-tests, hopefully.

https://ci.appveyor.com/project/secdev/scapy/builds/25096483/job/btoh71rf5hdbrx8f

### CODE REVIEW

**Comment by guedou** [comment]
You must set `random.seed()` before calling `fuzz()` or when _random_ values are expected. That will make the results reproducible.

**Comment by polybassa** [comment]
Thanks for this hint.

**Comment by gpotter2** [comment]
Just bumped into https://ci.appveyor.com/project/secdev/scapy/builds/25096483/job/btoh71rf5hdbrx8f

**Comment by polybassa** [comment]
Sorry. I will remove that unit test.

**Comment by gpotter2** [comment]
Sorry I wasn't clear, this happened before your fix :-)
This is why I fast-tracked it

**Comment by cameronstubber** [comment]
Can I make a comment, that I dont think the documentation on the DBC Implementation is adequate. When I figure out how to make it actually work, I could update it perhaps. Any thoughts on expanding the example there @polybassa ?

**Comment by polybassa** [comment]
Hi @cameronstubber thanks for your request. Your absolutely right, and the point you mentioned is a bug, that I just found through your request.

**Comment by polybassa** [comment]
I've made a pull request to fix the SignalFields. #2253 Please have a look. This provides also some proper documentation and a `SignalHeader` packet.

**Comment by cameronstubber** [comment]
Hi @polybassa I have made changes to my scapy can file based on your fix, and also updated my class with suggested changes to the packet build process and the binding layer etc. I now have multiplexor values being populated as expected, and various fields in the multiplexor being set to 1. I have sent the output from my script to a subject matter expert for verification of the output values, but so far I would say that the changes look good.

**Comment by polybassa** [comment]
resolves issue #2252

**Pull request merged**
