### PR TITLE
Fix NTP TimeStampField.any2i()

### LINKED ISSUE #135: Unable to Accurately Set Time Fields in NTP Layer
I'm trying to modify the time fields in the NTP layer, and not having any luck. I've tried setting packet.recv to an integer value and a string representation of time, but no matter what I try, when I send the packet, this field is always set to the default 0. Is there any example code that I just missed that would show me how to do this? Thank you in advance.

### PR DESCRIPTION
**Pull request by p-l-**
Fixes #135.

### CODE REVIEW

**Comment by guedou** [comment]
Is this a fix for Issue #137 ?

**Comment by p-l-** [comment]
Yes, partly (see my comment there). So I add this: fixes #135.

**Comment by colleen15** [comment]
Can I suggest changing the following?

Instead of 
```
elif isinstance(val, datetime.datetime):
     val = int(datetime.datetime.now().strftime("%s")) + _NTP_BASETIME
```

```
elif isinstance(val, datetime.datetime):
    val = int(val.strftime(%s)) + _NTP_BASETIME
```

**Comment by p-l-** [comment]
@colleen15 obviously! thanks!

**Pull request merged**
