### PR TITLE
Add pytest for dhcp6 tests

### PR DESCRIPTION
**Pull request by polybassa**

### CODE REVIEW

**Comment by guedou** [comment]
Sorry, I could not answer earlier to the question in #2779.

The maintainers need to discuss if we want to switch to pytest and remove UTScapy. I do not want to use and maintain both at the same time.

The first step is to make the .uts files hierarchy similar to the scapy Python file.

I will reference this PR in #2550 and close it when the tests are all completed (I am curious).

**Comment by polybassa** [comment]
I can understand that. I personally don't think, that the two test systems in parallel would cause more maintaining effort, but I'm also not a maintainer, so I better keep my mouth shut. A certain period of parallel test systems would maybe allow a smooth transition. Another thing to concern, UTscapy is kinda simulation inputs into a shell, while pytest is executing the entire file as script. This might also have some effects.

**Comment by polybassa** [comment]
This is interesting:
Pytest
```============================= 309 passed in 3.02s =============================```
UTscapy
```Campaign CRC=A4C19646 in 000.16s SHA=96C29544F52DEB1A5CBA8782F9E17D108D23A41B``` 

But maybe pytest has some on-time effort

**Comment by guedou** [comment]
We definitely to investigate =)

**Comment by polybassa** [comment]
I merged this into #2550

**Pull request closed without merging**
