### PR TITLE
Started with typing of Supersocket

### PR DESCRIPTION
**Pull request by polybassa**

### CODE REVIEW

**Comment by gpotter2** [comment]
Thanks for looking into this. I expected this one to be a pain, same applies to `arch/` :/

we should however probably do `interfaces` first

**Comment by polybassa** [comment]
Yes, it's a pain and I don't know how to solve some issues. I will come back if I finished with the easy ones.
-- 
Viele Grüße

Nils Weiß

**Comment by gpotter2** [comment]
I'll share my offline progress so that you don't start working on the same things (if you want to of course. This is pretty boring)
- I already have [a PR for `utils6.py`](https://github.com/gpotter2/scapy/tree/mypy-utils6) but it has to wait for at least https://github.com/secdev/scapy/pull/2865
- I was planning to tackle `base_classes`, `extlib`, `error`, `themes` next (they're all pretty simple but I want to make sure ` base_classes` is done right. metaclasses are a pain to type)
- `interfaces` and `sessions.py` need to be done to continue typing the IO stack and are pretty much standalones
- low priority are `automaton`, `pipetools`, `scapypipes`, `asn1*`, `autorun`
- high priority is obviously `sndrcv` but to do that we have to do `supersocket` first, and probably `arch` even before that. and `arch` will definetly require `utils6` to be done first 😄

**Comment by polybassa** [comment]
Thanks for sharing :-)

**Comment by gpotter2** [comment]
I've included this in https://github.com/gpotter2/scapy/tree/mypy-arch if you don't mind. It's not ready to merge yet but it's getting somewhere

**Comment by polybassa** [comment]
Thanks. as soon as I continue, I will rebase on that branch.

**Comment by gpotter2** [comment]
Superseeded by https://github.com/secdev/scapy/pull/2951

**Comment by polybassa** [comment]
I will close this one. Thanks for taking over!

**Pull request closed without merging**
