### PR TITLE
Automatically check SPDX identifiers

### PR DESCRIPTION
**Pull request by guedou**
This PR adds a check of SPDX identifiers with GitHub Actions, see #4263.

### CODE REVIEW

**Comment by guedou** [comment]
@polybassa the commit only changes the permissions of the script that was commited by @gpotter2

**Comment by polybassa** [comment]
Sorry, my bad!

**Review by polybassa — APPROVED** [review]

**Review by gpotter2 — APPROVED** [review]
Thanks for the PR. Could you rebase against master? I've updated the script to exit 1 on failure.

**Comment by guedou** [comment]
@gpotter2 done!

**Pull request merged**
