### PR TITLE
Try to make CANSocket unit tests more reliable

### PR DESCRIPTION
**Pull request by polybassa**
This PR tries to make CANSocket unit tests more reliable. 

Since there is a sporadic error in this tests, I don't know how effective this changes are.

### CODE REVIEW

**Comment by gpotter2** [comment]
Thanks for the update ! Looking good (TBH I didnt check it precisely :smile:)

**Comment by polybassa** [comment]
Thanks. If you discover further sporadic errors, please let me know.

**Comment by gpotter2** [comment]
Hi @polybassa, here’s another one
https://api.travis-ci.org/v3/job/510864342/log.txt
From
https://github.com/secdev/scapy/pull/1930

**Comment by polybassa** [comment]
thanks. I'll dig into that as soon as I find some free time

**Pull request merged**
