### PR TITLE
Added a vs code extension for syntax highlighting of uts files

### PR DESCRIPTION
**Pull request by TH-eMundo**

### CODE REVIEW

**Comment by gpotter2** [comment]
Not sure if we want this (thanks for the PR).
That's just a copy pasted version of the Python one with uts instead of py.

**Comment by TH-eMundo** [comment]
Well yeah, what else would you expect syntax highlighting for uts files to look like? I added a few rules to highlight the uts directives and I registered it on the .uts extension so that it is loaded when editing uts files. I'd be surprised if the vim plugin that's already in here does something more/else than this.

**Comment by gpotter2** [comment]
Yeah the vim plugin is also a copy pasted. I'm not a fan of it either TBH.
But if we start doing all the IDEs it's never ending. Not many people will ever write UTS files, and we were even thinking dropping them eventually.

**Comment by guedou** [comment]
IMHO, this should be added to the wiki and not the source code.

**Comment by TH-eMundo** [comment]
I'll assume you closed this because you're dropping UTS in favour of something more standard like pytest?

**Comment by gpotter2** [comment]
Correct. Will take time to migrate everything though, we'll have a project setup sometimes soon.

**Comment by TH-eMundo** [comment]
Nice, that's the solution I prefer the most :)

**Pull request closed without merging**
