### PR TITLE
Standalone TFTP unit tests

### PR DESCRIPTION
**Pull request by polybassa**
Co-authored-by: Gabriel Potter <gabriel@potter.fr>
Co-authored-by: Phil <phil@secdev.org>

### CODE REVIEW

**Comment by polybassa** [comment]
@guedou What's next?

**Comment by guedou** [comment]
Could you rebase against master?

**Comment by polybassa** [comment]
Done

**Comment by gpotter2** [comment]
Ahh, the coverage test. Throw in all possible options (`blksize`...) and try to reach the highest score 😄

**Review by gpotter2 — APPROVED** [review]

**Comment by guedou** [comment]
Could you do sctp.py next?

**Pull request merged**
