### PR TITLE
MACsec: Add support for XPN

### PR DESCRIPTION
**Pull request by g-mahieux**
This is a proposal of support for Extended Packet Numbering (XPN) in Scapy's MACsec, as described in the MACsec specification.

XPN adds support for 64 bit packet numbers instead of 32 bit, while still sending only the 32 LSB in the packet's sectag.

This proposal adds the additional parameters (Salt, SSCI) to the SA object along with an enable flag. Most of the changes affect the make_iv() function.
When encoding a packet, the LSBs of the SA's PN are used in the sectag.
When decoding a packet, the actual PN is recovered from the embedded 32 LSBs and the MSBs stored in the SA object.

I added as unittests some of the tests from the MACsec specification annex to exhibit encoding/decoding compliance with the expected behavior (both for XPN and non-XPN cases).

Thank you for your feedback.

### CODE REVIEW

**Comment by p-l-** [comment]
Hi,

Could you have a look at the failing tests? flask8 should be easy to fix, at least.

**Comment by g-mahieux** [comment]
@p-l- : Hello! I fixed the flake8 issue. It looks like the additional unit tests are not passing on some of the test setups. Any idea what could go wrong? Tests are passing fine on my desktop with both Python 2.7 and 3.

**Comment by guedou** [comment]
It looks like some of your tests are randomly failing:
https://travis-ci.org/secdev/scapy/jobs/361666843
https://travis-ci.org/secdev/scapy/jobs/361666849
https://travis-ci.org/secdev/scapy/jobs/361666851

**Comment by g-mahieux** [comment]
@guedou Well it looks like it always the same setups which are failing (OSX and one Linux). I don't know what's happening, there is nothing which should be non-deterministic in these tests. I can try on OSX later at home, but I can't reproduce that on my work setup.

**Comment by g-mahieux** [comment]
I dont understand, it looks like on some of the build configs the macsec tests are not run at all (this is not specific to my branch, it happens on successful builds of the master):
```
### Loading: scapy/contrib/macsec.uts
Campaign CRC=4778AC5E  SHA=1D1AAB0DDC94A2269584184CE3830639722D0D2B
PASSED=0 FAILED=0
```

On my computer I get :
```
$ test/run_tests_py3  -P "load_contrib('macsec')" -t scapy/contrib/macsec.uts -F
### Booting scapy...
### Starting tests...
### Loading: scapy/contrib/macsec.uts
passed 2B3A721B MACsec - basic encap - encrypted
passed 196D93C5 MACsec - basic encryption - encrypted
passed 5C23C2F1 MACsec - basic decryption - encrypted
passed E4B190BA MACsec - basic decap - decrypted
passed 399DE717 MACsec - basic encap - integrity only
passed C019E0DC MACsec - basic encryption - integrity only
passed B7992A7C MACsec - basic decryption - integrity only
passed 4C24A304 MACsec - basic decap - integrity only
passed E690E944 MACsec - encap - shortlen 2
passed AADF6437 MACsec - encap - shortlen 10
passed EB048049 MACsec - encap - shortlen 18
passed DEEC66D4 MACsec - encap - shortlen 32
passed F92EA610 MACsec - encap - shortlen 40
passed BA2CC9A8 MACsec - encap - shortlen 47
passed 661F45FC MACsec - encap - shortlen 0 (48)
passed 3821B35B MACsec - encap - shortlen 2/nosci
passed F432DC4F MACsec - encap - shortlen 32/nosci
passed 90F27333 MACsec - encap - shortlen 47/nosci
passed A70C387E MACsec - authenticate
passed 5E7C7F0B MACsec - authenticate - invalid packet
passed 4D4CEA0F MACsec - decrypt
passed 629E0231 MACsec - decrypt - invalid packet
passed 942F9D63 MACsec - decap - non-Ethernet
passed 25C2737D MACsec - decap - non-MACsec
passed 15DB0FB2 MACsec - encap - non-Ethernet
passed C642B636 MACsec - Standard Test Vectors - C.1.1 GCM-AES-128 (54-octet frame integrity protection)
passed 731E1902 MACsec - Standard Test Vectors - C.1.2 GCM-AES-256 (54-octet frame integrity protection)
passed E631457D MACsec - Standard Test Vectors - C.1.3 GCM-AES-XPN-128 (54-octet frame integrity protection)
passed 38AF9C1A MACsec - Standard Test Vectors - C.1.4 GCM-AES-XPN-256 (54-octet frame integrity protection)
passed AF1621BA MACsec - Standard Test Vectors - C.5.1 GCM-AES-128 (54-octet frame confidentiality protection)
passed 90F8D9CC MACsec - Standard Test Vectors - C.5.2 GCM-AES-256 (54-octet frame confidentiality protection)
passed DD4A2952 MACsec - Standard Test Vectors - C.5.3 GCM-AES-XPN-128 (54-octet frame confidentiality protection)
Campaign CRC=4778AC5E  SHA=1D1AAB0DDC94A2269584184CE3830639722D0D2B
PASSED=32 FAILED=0
### Writing output...
Test campaign
-- Run Fri Apr  6 16:02:04 2018 from [scapy/contrib/macsec.uts] by UTscapy

Passed=32
Failed=0
```

It doesn't really explain why the PR's tests are not passing ; but it looks like there is a configuration issue which prevents the tests from being executed in most cases.

**Comment by gpotter2** [comment]
The testing software handles flags.
For instance, here’s the one at the top of macsec.uts

~ crypto not_pypy

If cryptography could not be installed on the build, if the python version is not supported by it, if it’s using pypy... the tests will be ignored.

You have to look at the sudo enabled builds, with cryptography installed and a correct python version :)

**Comment by g-mahieux** [comment]
Ok, so I am able to reproduce the issue in the travis environment.
The issue happens in the following method:
```
    def decap(self, orig_pkt):
        """decapsulate a MACsec frame"""
        if orig_pkt.name != Ether().name or orig_pkt.payload.name != MACsec().name:
            raise TypeError('cannot decapsulate MACsec packet, must be Ethernet/MACsec')
        packet = copy.deepcopy(orig_pkt)
        prev_layer = packet[MACsec].underlayer
        prev_layer.type = packet[MACsec].type
        next_layer = packet[MACsec].payload
        del prev_layer.payload
        if prev_layer.name == Ether().name:
            return Ether(raw(prev_layer/next_layer)) <<<<< HERE
        return prev_layer/next_layer
```
It looks like this case is not covered by the existing unit tests.
I am not sure why it fails though, because "prev_layer/next_layer" does yield a correct Ether packet, but the double casting "Ether(raw())" then fails.
But anyway the condition looks unnecessary to me ; and skipping it fixes the issue.

I could make a separate PR adding a dedicated test and removing the condition to show that it's ok. Let me know.

**Comment by plorinquer** [comment]
@guedou The Extended Packet Numbering implementation looks good.

Thanks for this PR !

**Comment by guedou** [comment]
You can try to set conf.debug_dissector to False for your tests and set it back to the previous value at the end.

**Comment by guedou** [comment]
Could you rebase against master? I have seen some code patterns that will make the current flake8 tests fail. Otherwise, you PR seems OK to merge. Thanks.

**Comment by g-mahieux** [comment]
@guedou : Done :-)

**Comment by guedou** [comment]
You have new issues with flake8 =/ The other errors are not related to your PR

**Comment by g-mahieux** [comment]
Flake issue fixed, looks good now.

**Comment by g-mahieux** [comment]
@guedou Thank you!

**Pull request merged**
