### PR TITLE
Added AEAD digest support to IPSec layer, specifically for GCM and CC…

### PR DESCRIPTION
**Pull request by kinap**
…M modes.

### CODE REVIEW

**Comment by kinap** [comment]
Pycrypto AEAD API reference:

https://github.com/dlitz/pycrypto/blob/master/Doc/AEAD_API.txt

**Comment by p-l-** [comment]
Hi,

Thank you for this fix. A few comments:
  - We try to keep (when possible) the commit history as clean as possible. When you have trivial fixes, please consider `commit`-ing `--amend` or `rebase`-ing `-i`.
  - We also try to comply with PEP8 for new code, even though the old code is far from that standard.
  - Maybe it would be better to have an attribute `.is_aead` set during `__init__()` and just access it instead of calling a function and doing the checks each time you need the value:

```python
class CryptAlgo(object):
    [...]
    def __init__(self, name, cipher, mode, block_size=None, iv_size=None, key_size=None, icv_size=None):
        [...]
        self.is_aead = (hasattr(self.cipher, 'MODE_GCM') and
                        self.mode == self.cipher.MODE_GCM) or \
            (hasattr(self.cipher, 'MODE_CCM') and
             self.mode == self.cipher.MODE_CCM)
```
(then you just have to replace `.is_aead()` by `.is_aead`)

**Comment by kinap** [comment]
Hi,

Thanks for the comments. I've moved the is_aead check into __init__(), squashed the trivial fixes into one commit, and attempted compliance with PEP8. Let mew know how it looks.

**Comment by p-l-** [comment]
Hi,

Thanks, that's perfect for me. @guedou, OK to merge?

**Pull request merged**
