### PR TITLE
allow custom binding to usb sublayers fixed #3534

### LINKED ISSUE #3534: usb layer forces raw payload instead of allowing custom layers
### Brief description

in the guess_payload_class() methon of usb.py if the payload can not be determined, it returns a raw_layer type. it should return super(USBpcap,self).guess_payload_class(payload) to allow custom layers to exist below the usb layer. 

### Scapy version

4f42d252

### Python version

3.9.5

### Operating system

windows 11

### Additional environment information

_No response_

### How to reproduce

```
from scapy.all import PcapReader,Packet,bind_layers,ByteField,PadField
from scapy.layers.usb import USBpcap

class DAP_CMD(Packet):
    name = "DapCMD "
    fields_desc= [
      ByteField("cmd",0),
      #PadField("dummy", align=64, padwith=0)
    ]

bind_layers(USBpcap,DAP_CMD, endpoint=0x2)    

    
p = b'\x1b\x00\xa0\t\xd6\xe2\x88\xb6\xff\xff\x00\x00\x00\x00\t\x00\x00\x01\x00\x0b\x00\x02\x01@\x00\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'

pak = USBpcap(p)
pak.show()```

### Actual result

###[ USBpcap URB ]### 
  headerLen = 27
  res       = 0
  irpId     = 0xffffb688e2d609a0
  usbd_status= Success
  function  = URB_FUNCTION_BULK_OR_INTERRUPT_TRANSFER
  info      = 0x0
  bus       = 1
  device    = 11
  endpoint  = 0x2
  transfer  = Interrupt
  dataLength= 64
###[ Raw ]###
     load      = '\x00\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'

### Expected result

###[ USBpcap URB ]### 
  headerLen = 27
  res       = 0
  irpId     = 0xffffb688e2d609a0
  usbd_status= Success
  function  = URB_FUNCTION_BULK_OR_INTERRUPT_TRANSFER
  info      = 0x0
  bus       = 1
  device    = 11
  endpoint  = 0x2
  transfer  = Interrupt
  dataLength= 64
###[ DapCMD  ]###
     cmd       = 0
###[ Raw ]###
        load      = '\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'

### Related resources

_No response_

### PR DESCRIPTION
**Pull request by bveina**
**Checklist:**

-   [X] If you are new to Scapy: I have checked [CONTRIBUTING.md](https://github.com/secdev/scapy/blob/master/CONTRIBUTING.md) (esp. section submitting-pull-requests)
-   [X] I squashed commits belonging together
-   [ ] I added unit tests or explained why they are not relevant
-   [ ] I executed the regression tests for Python2 and Python3 (using `tox` or, `cd test && ./run_tests_py2, cd test && ./run_tests_py3`)
-   [ ] If the PR is still not finished, please create a [Draft Pull Request](https://github.blog/2019-02-14-introducing-draft-pull-requests/)

allow custom binding to usb sublayers fixed #3534

fixes #xxx 
#3534

### CODE REVIEW

**Review by KhazAkar — CHANGES_REQUESTED** [review]
One excess return, please update that :)

**Comment by bveina** [comment]
i think that is required. there is no else clause just an elif. so if nothing matchs you need to return *something*

**Comment by KhazAkar** [comment]
> i think that is required. there is no else clause just an elif. so if nothing matchs you need to return _something_

I know, but please read carefully this line again, it states: return return [...], not return [...] ☺️

**Comment by bveina** [comment]
oh man, how embarrassing. updated.

**Review by gpotter2 — APPROVED** [review]

**Pull request merged**
